#!/usr/bin/env python3
"""Generate the paper's LaTeX tables from the frozen measurement JSONs (stdlib-only).

Inputs (paper/data/): wcet.json (replay timing, both engines), wcet_rust.json (counters),
wcet_alloc.json (LD_PRELOAD allocation pass); optionally wcet_psweep.json + psweep_rust.json
(the P-sweep replay + counters).
Outputs (paper/tables/): counters.tex, tails.tex, alloc.tex, regression.tex;
prose-macro files (*_macros.tex: tails, regression, legal, realdata, psweep, env,
oneoff) so no measurement number is ever hand-typed in the .tex sources; with psweep data
also tables/psweep.tex and figures/psweep.tex (pgfplots).

Regenerate after any re-measurement:  python3 scripts/gen_tables.py
Never hand-edit tables/*.tex or figures/*.tex — they are build products (kept in git so the
paper builds without re-running the benchmark).

The generator also *asserts* the rounded qualitative claims the prose makes (the intro
spread claim, "grazing the 100 ms budget", "the same per-point constant", the search-log kd
baseline): if a re-measurement falsifies one, generation fails instead of leaving stale prose.
wcet.json must carry the Profile-B meta.manifest emitted by scripts/integrate_campaign.py.
"""

import json
import math
import pathlib
import random

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "tables"

EULER_GAMMA = 0.5772156649015329
# Display order: worst first.
ORDER = [
    "search_00",
    "search_01",
    "dense_neighbors",
    "max_iterations",
    "cache_hostile",
    "subnormal",
    "legal_worst",
    "legal_osc",
]
LABEL = {
    "search_00": r"\emph{search-00}",
    "search_01": r"\emph{search-01}",
    "dense_neighbors": r"\emph{dense-nbrs}",
    "max_iterations": r"\emph{max-iters}",
    "cache_hostile": r"\emph{cache-hostile}",
    "subnormal": r"\emph{subnormal}",
    "legal_worst": r"\emph{legal-worst}$^\dagger$",
    "legal_osc": r"\emph{legal-osc}$^\dagger$",
}
# Shared table footnote for the tier markers.
TIER_NOTE = (r"\emph{search-00} is the union-worst search output; "
             r"$^\dagger$\,deployment-tier fixtures.")

# One-off side measurements quoted in the prose but not captured in data/*.json.
# Each entry documents its source; C1 of plan/paper_fix.md re-measures or archives them.
# Emitted as \oneoff* macros (tables/oneoff_macros.tex) so the .tex sources never hand-type
# them; where a derived quantity depends on one (kd growth %, allocator share), the
# derivation lives here too and is guarded by an assertion against the frozen data.
ONEOFF = {
    # Counter-guided search log (2026-07-10 session, not archived): kd_nodes_visited of the
    # generation-0 candidate. The gen-23 output is the frozen search-00; its kd value is
    # derived from wcet_rust.json and asserted below so this baseline cannot silently pair
    # with a different search run.
    "kd_gen_zero_m": 8.88,
    # Subnormal A/B (2026-07-10 session): same fixture regenerated with the source shell at
    # 1.69 m instead of 1.99 m, moving every kernel exp() result out of the f64 subnormal
    # band; p50 ms per engine, same replay protocol as wcet.json.
    "shell_sub_cpp_ms": 57.6,
    "shell_ctrl_cpp_ms": 58.6,
    "shell_sub_rust_ms": 8.0,
    "shell_ctrl_rust_ms": 8.9,
    # exp() microbenchmark (2026-07-10 session): subnormal-result vs normal-result cost per
    # call, glibc exp vs the port's pure-Rust libm.
    "exp_sub_ratio_glibc": 2.9,
    "exp_sub_ratio_libm": 5.1,
    # Allocator fast-path microbenchmark (2026-07-10 session): one malloc/free pair, ns,
    # thread-cache hit, same host.
    "malloc_pair_ns": 11.3,
    # Iterative vs recursive kd radius search (port development, same day / same core), %.
    "kd_iter_speedup_pct": 12,
    # legal-worst rerun at the shipped epsilon = 0.01: converges in this many iterations
    # (2026-07-10 session; motivates the epsilon-pinned iteration axis).
    "legal_worst_prod_eps_iters": 2,
    # Differential-test bound on the eigensolver deviation over the inverse covariances
    # (glibc/LAPACK vs the port), from the divergence root-cause session (2026-07-10).
    "eigensolver_bound": r"2\times10^{-15}",
}


def pct(sorted_xs, p):
    return sorted_xs[min(int(p * (len(sorted_xs) - 1)), len(sorted_xs) - 1)]


def num(x):
    """LaTeX-format an integer with thin-space thousands separators via siunitx."""
    return rf"\num{{{x}}}"


def write(name, caption, label, colspec, header, rows, note=None, tabcolsep="4pt"):
    lines = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\footnotesize",
        rf"\setlength{{\tabcolsep}}{{{tabcolsep}}}",
        rf"\begin{{tabular}}{{{colspec}}}",
        r"\toprule",
        header + r" \\",
        r"\midrule",
    ]
    lines += [r + r" \\" for r in rows]
    lines += [r"\bottomrule", r"\end{tabular}"]
    if note:
        lines.append(rf"\par\smallskip\footnotesize {note}")
    lines.append(r"\end{table}")
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote tables/{name}")


def tex_escape(s):
    """Escape the characters that actually occur in the env strings."""
    return s.replace("~", r"\textasciitilde{}").replace("_", r"\_")


def provenance(manifest, meta):
    """One generated sentence carried by every timing-table note (review #8).

    Built from the policy-schema meta.manifest of the campaign integration; names the
    measurement profile so no table can be read without its protocol.
    """
    sessions = manifest.get("sessions") or [manifest.get("experiment_id", "?")]
    dates = sorted({m["run_timestamp"][:10]
                    for m in manifest.get("session_manifests", [manifest])})
    return (
        rf"Profile {manifest['measurement_profile']} "
        rf"(\texttt{{plan/ndt\_timing\_measurement\_policy.md}}): {len(sessions)} "
        rf"session(s), {'/'.join(dates)}, isolated pinned core "
        rf"(\texttt{{{tex_escape(manifest.get('affinity_mask', '?'))}}}), "
        rf"{meta['iters']} aligns/fixture."
    )


def kernel_disp(v):
    """'Linux <hostname> <release>' -> 'Linux <release>' for display."""
    parts = v.split()
    return f"{parts[0]} {parts[-1]}" if len(parts) == 3 else v


def env_macros(manifest, meta):
    """Measurement-environment macros so Sec. V-A can never drift from the data."""
    cv = manifest.get("compiler_versions") or {}
    dates = sorted({m["run_timestamp"][:10]
                    for m in manifest.get("session_manifests", [manifest])})
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\envCpu}}{{{tex_escape(manifest.get('cpu_model') or '?')}}}",
        rf"\newcommand{{\envKernel}}{{{tex_escape(kernel_disp(manifest.get('kernel_version') or '?'))}}}",
        rf"\newcommand{{\envCppCompiler}}{{{tex_escape(cv.get('cxx') or '?')}}}",
        rf"\newcommand{{\envRustCompiler}}{{{tex_escape(cv.get('rustc') or '?')}}}",
        rf"\newcommand{{\envGovernor}}{{{manifest.get('governor') or '?'}}}",
        rf"\newcommand{{\envPinning}}{{\texttt{{{tex_escape(manifest.get('affinity_mask') or '?')}}}}}",
        rf"\newcommand{{\envDate}}{{{'/'.join(dates)}}}",
        rf"\newcommand{{\envIters}}{{{meta['iters']}}}",
        rf"\newcommand{{\envWarmup}}{{{meta['warmup']}}}",
        rf"\newcommand{{\envSessions}}{{{len(manifest.get('sessions', [1]))}}}",
        rf"\newcommand{{\envIsolated}}{{{manifest.get('isolated_cpus') or 'none'}}}",
        rf"\newcommand{{\envCommit}}{{{(manifest.get('cpp_commit') or '?')[:8]}}}",
    ]
    (OUT / "env_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/env_macros.tex")


def oneoff_macros():
    """Macros for the one-off side measurements (see the ONEOFF dict for provenance)."""
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        "% One-off side measurements not in data/*.json; sources documented at the ONEOFF",
        "% dict in scripts/gen_tables.py. C1 of plan/paper_fix.md re-measures/archives them.",
        rf"\newcommand{{\oneoffKdGenZeroM}}{{{ONEOFF['kd_gen_zero_m']:.2f}}}",
        rf"\newcommand{{\oneoffShellSubCpp}}{{{ONEOFF['shell_sub_cpp_ms']:.1f}}}",
        rf"\newcommand{{\oneoffShellCtrlCpp}}{{{ONEOFF['shell_ctrl_cpp_ms']:.1f}}}",
        rf"\newcommand{{\oneoffShellSubRust}}{{{ONEOFF['shell_sub_rust_ms']:.1f}}}",
        rf"\newcommand{{\oneoffShellCtrlRust}}{{{ONEOFF['shell_ctrl_rust_ms']:.1f}}}",
        rf"\newcommand{{\oneoffExpSubGlibc}}{{{ONEOFF['exp_sub_ratio_glibc']:.1f}}}",
        rf"\newcommand{{\oneoffExpSubLibm}}{{{ONEOFF['exp_sub_ratio_libm']:.1f}}}",
        rf"\newcommand{{\oneoffMallocPairNs}}{{{ONEOFF['malloc_pair_ns']:.1f}}}",
        rf"\newcommand{{\oneoffKdIterSpeedup}}{{{ONEOFF['kd_iter_speedup_pct']}}}",
        rf"\newcommand{{\oneoffLegalWorstProdEpsIters}}{{{ONEOFF['legal_worst_prod_eps_iters']}}}",
        rf"\newcommand{{\oneoffEigensolverBound}}{{{ONEOFF['eigensolver_bound']}}}",
    ]
    (OUT / "oneoff_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/oneoff_macros.tex")


def legal_k_macros():
    """Macros for the max-K legal-search result (skipped if absent)."""
    kj = DATA / "legal_k_search.json"
    if not kj.exists():
        print("legal_k_search absent -- skipping max-K search macros")
        return
    r = json.loads(kj.read_text())["result"]
    seeds = len(json.loads(kj.read_text())["meta"]["seeds"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\legalKSearchMax}}{{{r['max_k_reached']}}}",
        rf"\newcommand{{\legalKSearchSeeds}}{{{seeds}}}",
    ]
    (OUT / "legal_k_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/legal_k_macros.tex")


def ablation():
    """Search-ablation table + macros (review #9) from data/search_ablation.json:
    hill vs budget-matched random over seeds, wall-clock-fitness reproducibility, and
    Profile-B timing of the counter-Pareto frontier against an in-session search-00 anchor."""
    doc = json.loads((DATA / "search_ablation.json").read_text())
    meta, runs = doc["meta"], doc["runs"]
    nbr_max = meta["analytic_nbr_max"]
    if nbr_max != 2000 * 64 * 31:
        raise SystemExit("search_ablation.json: analytic nbr max != 2000*64*31 -- "
                         "budget/fixture family changed; regenerate the ablation data")
    # Guard: the frontier's search_00 triple must match the frozen counter baseline.
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]["search_00"]
    f00 = next(f for f in doc["frontier"] if f["name"] == "search_00")
    if (f00["iter"], f00["nbr"], f00["kd"]) != (
            rust["iteration_num"], rust["counters"]["sum_neighbors"],
            rust["counters"]["kd_nodes_visited"]):
        raise SystemExit("search_ablation.json frontier search_00 counters != wcet_rust.json "
                         "-- stale ablation data; regenerate")
    for r in runs:
        if r["mode"] == "hill" and r["fitness"] == "counters" and r["best"]["nbr"] != nbr_max:
            raise SystemExit(f"hill run seed={r['seed']} did not saturate sum-neighbors -- "
                             "the saturation claim in the prose is void; re-examine")

    rows = []
    for r in runs:
        mode = {"counters": r["mode"], "time": "hill (time)"}[r["fitness"]]
        sat = str(r["saturation_eval"])
        pct_max = f"{r['nbr_pct_of_max']:.1f}"
        rows.append(f"{mode} & \\texttt{{{r['seed']:#010x}}} & {sat} & {pct_max} "
                    f"& {num(r['best']['kd'])}")
    write(
        "ablation.tex",
        r"Search ablation: hill-climb vs budget-matched random sampling "
        rf"({meta['budget_evaluations']} evaluations each) and wall-clock fitness, per seed. "
        r"``at final \sumnbr{}'' = first evaluation reaching the run's final \sumnbr{}.",
        "tab:ablation",
        "llrrr",
        r"mode & seed & at final \sumnbr & \sumnbr{} (\% of max) & \kdnodes",
        rows,
        note=r"Hill-climb saturates \sumnbr{} at the analytic maximum on every seed (the "
        r"domain-informed seed genome already attains it; the search then grows \kdnodes); "
        r"random sampling never reaches it. The two wall-clock-fitness runs share a seed "
        r"yet return different champions --- counter fitness is bit-reproducible.",
    )

    # Frontier timing macros, anchored on the same-series search_00 cells.
    ft = doc["frontier_timing"]
    anchor = ft["search_00"]
    cand_names = [n for n in ft if n != "search_00"]
    for n, fx in ft.items():
        if not fx["iter_match"]:
            raise SystemExit(f"frontier timing {n}: engine iteration mismatch -- "
                             "equal-work certificate violated; investigate before publishing")
    ratios = {eng: max(ft[n][eng]["max_ms"] / anchor[eng]["max_ms"] for n in cand_names)
              for eng in ("cpp", "rust")}
    t1, t2 = doc["time_fitness_ablation"]["champion_kd"]
    if doc["time_fitness_ablation"]["reproducible"]:
        raise SystemExit("time-fitness runs reproduced identically -- the irreproducibility "
                         "sentence in the prose is void; re-examine")
    rand_pcts = [r["nbr_pct_of_max"] for r in runs
                 if r["mode"] == "random" and r["fitness"] == "counters"]
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\ablationBudget}}{{{meta['budget_evaluations']}}}",
        rf"\newcommand{{\ablationSeeds}}{{{len([r for r in runs if r['mode'] == 'hill' and r['fitness'] == 'counters'])}}}",
        rf"\newcommand{{\ablationRandomWorstPct}}{{{min(rand_pcts):.1f}}}",
        rf"\newcommand{{\ablationRandomBestPct}}{{{max(rand_pcts):.1f}}}",
        rf"\newcommand{{\ablationFrontierSize}}{{{len(doc['frontier'])}}}",
        rf"\newcommand{{\ablationFrontierCppRatio}}{{{ratios['cpp']:.3f}}}",
        rf"\newcommand{{\ablationFrontierRustRatio}}{{{ratios['rust']:.3f}}}",
        rf"\newcommand{{\ablationFrontierRustExcessPct}}{{{(ratios['rust'] - 1) * 100:.1f}}}",
        rf"\newcommand{{\ablationTimeKdA}}{{{num(t1)}}}",
        rf"\newcommand{{\ablationTimeKdB}}{{{num(t2)}}}",
    ]
    (OUT / "ablation_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/ablation.tex + ablation_macros.tex")


def raspi4():
    """On-target counter check (Raspberry Pi 4, bare-metal): table + macros from the
    frozen serial log data/raspi4.txt (skipped if absent).

    Guards recompute the host comparison from wcet_rust.json (the app's own OK verdicts
    are not trusted) and pin the known divergence to exactly search_01 with the exact
    deltas the prose documents; anything else fails generation.
    """
    rj = DATA / "raspi4.txt"
    if not rj.exists():
        print("raspi4 log absent -- skipping on-target outputs")
        return
    import re

    host = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    line_re = re.compile(
        r"NDT (\w+): iter=(\d+) passes=(\d+) pts=(\d+) nbr=(\d+) kd=(\d+) maxk=(\d+) "
        r"build_ms=(\d+) align_ms=(\d+) (OK|MISMATCH)"
    )
    target = {}
    summary = None
    for line in rj.read_text().splitlines():
        m = line_re.search(line)
        if m:
            target[m.group(1)] = {
                "iter": int(m.group(2)),
                "passes": int(m.group(3)),
                "pts": int(m.group(4)),
                "nbr": int(m.group(5)),
                "kd": int(m.group(6)),
                "maxk": int(m.group(7)),
                "align_ms": int(m.group(9)),
            }
        s = re.search(r"NDT COUNTER CHECK: (\d+)/(\d+) OK", line)
        if s:
            summary = (int(s.group(1)), int(s.group(2)))
    if summary is None or len(target) != summary[1]:
        raise SystemExit("raspi4: log truncated or summary missing")
    # Recompute equality against the (current) host baseline. The log's own OK/MISMATCH
    # verdicts are historical: the on-device expected table at run time was the stale
    # 2026-07-10 snapshot, which predated the two port-fidelity fixes; against the refreshed
    # baseline (see data/wcet_rust.json meta) every fixture is exact.
    mismatch = {}
    for n, t in target.items():
        h = host[n]
        hc = h["counters"]
        deltas = {
            "iter": t["iter"] - h["iteration_num"],
            "passes": t["passes"] - hc["derivative_passes"],
            "pts": t["pts"] - hc["points_processed"],
            "nbr": t["nbr"] - hc["sum_neighbors"],
            "kd": t["kd"] - hc["kd_nodes_visited"],
        }
        if any(v != 0 for v in deltas.values()):
            mismatch[n] = deltas
    if mismatch:
        raise SystemExit(
            f"raspi4: target counters diverge from the host baseline ({mismatch}) -- "
            "the Secs. III-E/V/VI prose claims exact transfer on every fixture"
        )
    # Pin the on-device verdict of the frozen log (re-captured 2026-07-12 after the
    # baseline refresh -> 8/8; the first run's 7/8 log lives in git history and is narrated
    # as history in Sec. V).
    if summary != (8, 8):
        raise SystemExit(
            f"raspi4: on-device summary changed to {summary} -- update the pinned "
            "verdict and the Sec. V prose"
        )
    # The historical skew the on-device check flagged (target/current values vs the stale
    # 2026-07-10 baseline; bisected to commit 7caf44d7 -- see data/wcet_rust.json meta).
    hist_nbr_delta = 2
    hist_kd_delta = -1

    rows = []
    for n in ORDER:
        if n not in target:
            continue
        rows.append(f"{LABEL[n]} & {target[n]['align_ms']} & exact")
    write(
        "raspi4.tex",
        r"On-target counter check: Raspberry Pi 4 (Cortex-A72), bare-metal \texttt{no\_std} "
        r"kernel, one align per fixture (serial log frozen as \texttt{data/raspi4.txt}).",
        "tab:raspi4",
        "lrl",
        r"fixture & align (\si{ms}) & counters vs.\ host",
        rows,
        note=r"Times are single-shot and informational (no warmup, $n{=}1$; an idle "
        r"bare-metal core, but not the measurement protocol of "
        r"Sec.~\ref{sec:evaluation}). Counter comparison is recomputed against "
        r"\texttt{wcet\_rust.json} at generation time; the on-device verdict is 8/8 "
        r"(re-captured after the baseline refresh of Sec.~\ref{sec:eval-raspi4}).",
    )
    worst_s = max(t["align_ms"] for t in target.values()) / 1000.0
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\raspiTotal}}{{{len(target)}}}",
        rf"\newcommand{{\raspiExact}}{{{len(target) - len(mismatch)}}}",
        rf"\newcommand{{\raspiDeviceOk}}{{{summary[0]}}}",
        rf"\newcommand{{\raspiNbrDelta}}{{{hist_nbr_delta}}}",
        rf"\newcommand{{\raspiKdDelta}}{{{-hist_kd_delta}}}",
        rf"\newcommand{{\raspiMismatchNbrM}}{{{host['search_01']['counters']['sum_neighbors'] / 1e6:.1f}}}",
        rf"\newcommand{{\raspiAlignWorstS}}{{{worst_s:.1f}}}",
    ]
    (OUT / "raspi4_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/raspi4_macros.tex")


def interference():
    """Cache- and interference-sensitivity table + macros from the campaign's cold and
    co-runner series (skipped if the files are absent)."""
    cj, oj = DATA / "wcet_cold.json", DATA / "wcet_corunner.json"
    if not (cj.exists() and oj.exists()):
        print("cold/corunner data absent -- skipping interference outputs")
        return
    warm = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    cold = json.loads(cj.read_text())["fixtures"]
    co = json.loads(oj.read_text())["modes"]

    def med(fx, eng):
        xs = sorted(fx[eng]["samples_ms"])
        return xs[len(xs) // 2]

    # Table: the two co-runner fixtures, delta of median and max vs the warm series.
    rows = []
    co_worst = {}
    for n in ("search_00", "legal_worst"):
        cells = [LABEL[n]]
        for eng in ("cpp", "rust"):
            base_max = max(warm[n][eng]["samples_ms"])
            dc = 100.0 * (med(cold[n], eng) / med(warm[n], eng) - 1.0)
            cells.append(f"{dc:+.1f}")
            for mode in ("membw", "llc", "fp"):
                dm = 100.0 * (max(co[mode][n][eng]["samples_ms"]) / base_max - 1.0)
                cells.append(f"{dm:+.1f}")
                co_worst[n] = max(co_worst.get(n, 0.0), dm)
        rows.append(" & ".join(cells))
    write(
        "interference.tex",
        r"Cache and interference sensitivity: relative change vs.\ the warm series "
        r"(\%; cold = median shift under between-sample eviction; co-runner columns = "
        r"max shift with the named one-resource co-runner on an L3-sharing core).",
        "tab:interference",
        "lrrrrrrrr",
        r"fixture & \multicolumn{4}{c}{C++ (cold/membw/llc/fp)} "
        r"& \multicolumn{4}{c}{Rust (cold/membw/llc/fp)}",
        rows,
        tabcolsep="2pt",
        note=r"Positive = slower than warm. \emph{search-00} is kernel-evaluation-bound "
        r"(cache-resident); \emph{legal-worst} is kd-traversal/memory-bound --- the "
        r"deployment tier is the interference-sensitive one.",
    )
    # Cold worst across ALL fixtures (prose macro).
    cold_worst = 0.0
    for n in cold:
        for eng in ("cpp", "rust"):
            cold_worst = max(
                cold_worst, 100.0 * (med(cold[n], eng) / med(warm[n], eng) - 1.0))
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\coldWorstPct}}{{{cold_worst:.1f}}}",
        rf"\newcommand{{\coWorstSearch}}{{{co_worst.get('search_00', 0):.1f}}}",
        rf"\newcommand{{\coWorstLegal}}{{{co_worst.get('legal_worst', 0):.1f}}}",
    ]
    (OUT / "interference_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/interference_macros.tex")


def cert_macros():
    """Pose/score certificate macros from wcet_cert.json (skipped if absent).

    The certificate is deterministic per input (poses do not depend on the timing-run
    sample count), so it is re-runnable independently of the frozen timing data.
    """
    cj = DATA / "wcet_cert.json"
    if not cj.exists():
        print("wcet_cert absent -- skipping certificate macros")
        return
    fx = json.loads(cj.read_text())["fixtures"]
    bad = [n for n, c in fx.items() if not c["pose_match"]]
    if bad:
        raise SystemExit(
            f"pose/score certificate FAILED on {bad} -- "
            "the Sec. III-C/V-B certificate claims no longer hold"
        )
    max_trans = max(c["trans_delta_m"] for c in fx.values())
    max_score = max(max(c["tp_delta"], c["nvtl_delta"]) for c in fx.values())
    score_exact = sum(
        1 for c in fx.values() if c["tp_delta"] == 0.0 and c["nvtl_delta"] == 0.0
    )
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\certFixtures}}{{{len(fx)}}}",
        rf"\newcommand{{\certScoreExact}}{{{score_exact}}}",
        rf"\newcommand{{\certMaxTransDelta}}{{\num{{{max_trans:.0e}}}}}",
        rf"\newcommand{{\certMaxScoreDelta}}{{\num{{{max_score:.0e}}}}}",
    ]
    (OUT / "cert_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/cert_macros.tex")


def main():
    doc = json.loads((DATA / "wcet.json").read_text())
    timing = doc["fixtures"]
    meta = doc.get("meta", {})
    manifest = meta.get("manifest")
    if not manifest or manifest.get("measurement_profile") != "B":
        raise SystemExit(
            "wcet.json lacks a Profile-B meta.manifest -- regenerate it via "
            "scripts/integrate_campaign.py (tables must not mix measurement profiles)")
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    alloc = json.loads((DATA / "wcet_alloc.json").read_text())["fixtures"]
    names = [n for n in ORDER if n in timing]
    prov = provenance(manifest, meta)
    env_macros(manifest, meta)
    oneoff_macros()

    # ---- counters.tex ----
    rows = []
    for n in names:
        c = rust[n]["counters"]
        rows.append(
            f"{LABEL[n]} & {rust[n]['iteration_num']} & {num(c['sum_neighbors'])} "
            f"& {num(c['kd_nodes_visited'])} & {num(rust[n]['n_map'])} & {rust[n]['n_tiles']}"
        )
    write(
        "counters.tex",
        r"Frozen fixtures: deterministic work counters (platform-independent; "
        r"$P=2000$ for the search outputs).",
        "tab:counters",
        "lrrrrr",
        r"fixture & $N_{\mathrm{iter}}$ & \sumnbr{} & \kdnodes{} & map pts & tiles",
        rows,
        note=r"$\sumnbr = \num{3968000} = 2000 \cdot 64 \cdot 31$ on "
        r"\emph{search-00}: the analytic kernel-evaluation maximum, reached exactly. " + TIER_NOTE,
    )

    # ---- tails.tex ----
    rows = []
    ratios = {}
    p50 = {}  # (fixture, engine) -> p50 ms
    mx = {}  # (fixture, engine) -> max ms
    for n in names:
        fx = timing[n]
        cs = sorted(fx["cpp"]["samples_ms"])
        rs = sorted(fx["rust"]["samples_ms"])
        p50[(n, "cpp")], p50[(n, "rust")] = pct(cs, 0.5), pct(rs, 0.5)
        mx[(n, "cpp")], mx[(n, "rust")] = cs[-1], rs[-1]
        ratios[n] = rs[-1] / cs[-1]
        rows.append(
            f"{LABEL[n]} & {pct(cs, 0.5):.1f} & {cs[-1]:.1f} & {pct(rs, 0.5):.1f} "
            f"& {rs[-1]:.1f} & \\textbf{{{ratios[n]:.2f}}}"
        )
    write(
        "tails.tex",
        rf"Frame time per engine (\si{{ms}}; {meta['iters']} samples/fixture, serial, "
        r"isolated pinned core). Equal work certified per fixture (identical "
        r"\texttt{iteration\_num}).",
        "tab:tails",
        "lrrrrr",
        r"fixture & \multicolumn{2}{c}{C++ (p50 / max)} "
        r"& \multicolumn{2}{c}{Rust (p50 / max)} & ratio",
        rows,
        note=r"ratio = Rust max / C++ max; $<1$ everywhere. " + TIER_NOTE + " " + prov,
    )

    # ---- tails_macros.tex: timing/counter/alloc-derived prose numbers ----
    # Per-point-per-pass cost (us) on the neighbor-sparse fixtures; points_processed
    # already equals passes * P.
    def pt_pass_us(n, eng):
        return p50[(n, eng)] * 1000.0 / rust[n]["counters"]["points_processed"]

    def kbar_of(n):
        c = rust[n]["counters"]
        return c["sum_neighbors"] / c["points_processed"]

    gap_sub = pt_pass_us("subnormal", "cpp") - pt_pass_us("subnormal", "rust")
    gap_ch = pt_pass_us("cache_hostile", "cpp") - pt_pass_us("cache_hostile", "rust")
    # "reappears as the same constant on cache-hostile": the two gaps must stay close.
    if abs(gap_sub - gap_ch) > 0.15 * gap_sub:
        raise SystemExit(
            f"per-point overhead gap diverged (subnormal {gap_sub:.2f} vs "
            f"cache-hostile {gap_ch:.2f} us) -- prose claims 'the same constant'"
        )
    # Allocator share of the gap: ONEOFF fast-path pair cost x measured pairs per pt-pass.
    sub_pairs = alloc["subnormal"]["cpp"]["allocs_per_align"] / rust["subnormal"]["counters"][
        "points_processed"
    ]
    alloc_share = 100.0 * ONEOFF["malloc_pair_ns"] * sub_pairs / (gap_sub * 1000.0)
    # search-00 kd term and its growth over the ONEOFF search-log gen-0 baseline.
    kd_m = rust["search_00"]["counters"]["kd_nodes_visited"] / 1e6
    if abs(kd_m - 12.01) > 0.005:
        raise SystemExit(
            f"search-00 kd = {kd_m:.2f} M: fixture changed; the ONEOFF kd_gen_zero_m "
            "search-log baseline (and the derived growth %) no longer applies"
        )
    kd_growth = 100.0 * (kd_m / ONEOFF["kd_gen_zero_m"] - 1.0)
    # Two-tier kernel-evaluation drop.
    nbr_search = rust["search_00"]["counters"]["sum_neighbors"]
    nbr_legal = rust["legal_worst"]["counters"]["sum_neighbors"]
    # Alloc headline: worst fixture per align, and the per-(pt.pass) constant.
    alloc_worst = max(alloc[n]["cpp"]["allocs_per_align"] for n in names)
    app = alloc["search_00"]["cpp"]["allocs_per_align"] / rust["search_00"]["counters"][
        "points_processed"
    ]
    # B1a: the interposer counts double as an independent C++-side work certificate ---
    # allocs/(pt.pass) must be constant wherever radius queries return neighbors, since the
    # numerator comes from the untouched C++ binary and the denominator from Rust counters.
    cert = {
        n: alloc[n]["cpp"]["allocs_per_align"]
        / rust[n]["counters"]["points_processed"]
        for n in names
    }
    cert_dense = [
        v
        for n, v in cert.items()
        if rust[n]["counters"]["sum_neighbors"] >= rust[n]["counters"]["points_processed"]
    ]
    cert_lo, cert_hi = min(cert_dense), max(cert_dense)
    if (cert_hi - cert_lo) / cert_lo > 0.005:
        raise SystemExit(
            f"alloc work-certificate spread {(cert_hi - cert_lo) / cert_lo:.3%} > 0.5% -- "
            "the C++-side P*N_pass cross-check claim in Secs. III-C/V-C no longer holds"
        )
    # Intro spread claim: "from under 10 ms to nearly a second ... two orders of magnitude".
    spread = max(mx.values()) / min(p50.values())
    if not (min(p50.values()) < 10.0 and max(mx.values()) > 900.0 and spread > 100.0):
        raise SystemExit(
            f"intro spread claim is stale (min p50 {min(p50.values()):.1f} ms, "
            f"max {max(mx.values()):.1f} ms, spread {spread:.0f}x)")
    # Cross-session stability (review #8): worst relative spread of per-session medians,
    # and the spread of the Rust/C++ max ratio, across the campaign sessions.
    med_spread_worst = 0.0
    ratio_spread_worst = 0.0
    for n in names:
        psm = timing[n].get("per_session_median")
        if not psm:
            continue
        for eng in ("cpp", "rust"):
            ms = psm[eng]
            med_spread_worst = max(
                med_spread_worst, 100.0 * (max(ms) - min(ms)) / min(ms))
        # ratio per session from the per-session medians
        rr = [r / c for c, r in zip(psm["cpp"], psm["rust"])]
        ratio_spread_worst = max(ratio_spread_worst, max(rr) - min(rr))
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\tailsRatioMin}}{{{min(ratios.values()):.2f}}}",
        rf"\newcommand{{\tailsRatioMax}}{{{max(ratios.values()):.2f}}}",
        rf"\newcommand{{\sessMedSpreadWorstPct}}{{{med_spread_worst:.1f}}}",
        rf"\newcommand{{\sessRatioSpreadWorst}}{{{ratio_spread_worst:.2f}}}",
        rf"\newcommand{{\tailsSearchMaxCpp}}{{{mx[('search_00', 'cpp')]:.1f}}}",
        rf"\newcommand{{\tailsSearchMaxRust}}{{{mx[('search_00', 'rust')]:.1f}}}",
        rf"\newcommand{{\subnormalMedianRatio}}{{{p50[('subnormal', 'cpp')] / p50[('subnormal', 'rust')]:.1f}}}",
        rf"\newcommand{{\subnormalPtPassCppUs}}{{{pt_pass_us('subnormal', 'cpp'):.1f}}}",
        rf"\newcommand{{\subnormalPtPassRustUs}}{{{pt_pass_us('subnormal', 'rust'):.2f}}}",
        rf"\newcommand{{\ptPassGapUs}}{{{gap_sub:.1f}}}",
        rf"\newcommand{{\subnormalKbar}}{{{kbar_of('subnormal'):.1f}}}",
        rf"\newcommand{{\cacheHostileKbar}}{{{kbar_of('cache_hostile'):.1f}}}",
        rf"\newcommand{{\subnormalAllocPairs}}{{{sub_pairs:.0f}}}",
        rf"\newcommand{{\subnormalAllocSharePct}}{{{alloc_share:.0f}}}",
        rf"\newcommand{{\searchZeroKdM}}{{{kd_m:.2f}}}",
        rf"\newcommand{{\searchKdGrowthPct}}{{{kd_growth:.0f}}}",
        rf"\newcommand{{\searchZeroSumNbrM}}{{{nbr_search / 1e6:.2f}}}",
        rf"\newcommand{{\legalWorstSumNbrK}}{{{nbr_legal / 1e3:.0f}}}",
        rf"\newcommand{{\twoTierKernelDrop}}{{{nbr_search / nbr_legal:.1f}}}",
        rf"\newcommand{{\allocWorstPerAlign}}{{\num{{{alloc_worst}}}}}",
        rf"\newcommand{{\allocPerPtPass}}{{{app:.0f}}}",
        rf"\newcommand{{\allocPerPtPassExact}}{{{app:.1f}}}",
        rf"\newcommand{{\allocCertMin}}{{{cert_lo:.3f}}}",
        rf"\newcommand{{\allocCertMax}}{{{cert_hi:.3f}}}",
        rf"\newcommand{{\allocCertSpreadPct}}{{{100.0 * (cert_hi - cert_lo) / cert_lo:.2f}}}",
        rf"\newcommand{{\allocCertSparse}}{{{cert['subnormal']:.1f}}}",
    ]
    (OUT / "tails_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/tails_macros.tex")

    # ---- alloc.tex ----
    rows = []
    for n in names:
        fx = alloc[n]
        c = rust[n]["counters"]
        per_pp = fx["cpp"]["allocs_per_align"] / (
            c["derivative_passes"] * rust[n]["n_source"]
        )
        rows.append(
            f"{LABEL[n]} & {num(fx['cpp']['allocs_per_align'])} & {per_pp:.1f} "
            f"& {fx['rust']['allocs_per_align']}"
        )
    write(
        "alloc.tex",
        r"Heap allocations per align (\texttt{LD\_PRELOAD} interposer).",
        "tab:alloc",
        "lrrr",
        r"fixture & C++ / align & C++ / (pt$\cdot$pass) & Rust / align",
        rows,
        note=r"The constant ${\approx}11$ per point per pass locates the source in the "
        r"per-point inner loop (Sec.~\ref{sec:eval-alloc}). Rust: zero, matching the "
        r"counting-allocator-verified allocation-freedom contract. " + TIER_NOTE + " " + prov,
    )

    # ---- regression.tex ----
    # Pooled design (review #11): the 8 fixtures plus the 6 P-sweep points (same counters/
    # timing protocol) -> n = 14 per engine, with bootstrap CIs, leave-one-out prediction
    # error, and the sum_neighbors/kd_nodes collinearity reported honestly.
    def reg_rows(engine):
        rows_ = []
        for n in names:
            c = rust[n]["counters"]
            t50 = pct(sorted(timing[n][engine]["samples_ms"]), 0.5)
            rows_.append((float(c["sum_neighbors"]), float(c["kd_nodes_visited"]), t50, n))
        pj, prj = DATA / "wcet_psweep.json", DATA / "psweep_rust.json"
        if pj.exists() and prj.exists():
            pt = json.loads(pj.read_text())["fixtures"]
            pr = json.loads(prj.read_text())["fixtures"]
            for n in pt:
                c = pr[n]["counters"]
                t50 = pct(sorted(pt[n][engine]["samples_ms"]), 0.5)
                rows_.append(
                    (float(c["sum_neighbors"]), float(c["kd_nodes_visited"]), t50, n)
                )
        return rows_

    def fit(rows_):
        ata = [[0.0] * 3 for _ in range(3)]
        atb = [0.0] * 3
        for nbr, kd, t, _ in rows_:
            x = (nbr, kd, 1.0)
            for i in range(3):
                for j in range(3):
                    ata[i][j] += x[i] * x[j]
                atb[i] += x[i] * t
        m = [row[:] + [atb[i]] for i, row in enumerate(ata)]
        for col in range(3):
            piv = max(range(col, 3), key=lambda r: abs(m[r][col]))
            m[col], m[piv] = m[piv], m[col]
            for r in range(3):
                if r != col:
                    f = m[r][col] / m[col][col]
                    for cc in range(col, 4):
                        m[r][cc] -= f * m[col][cc]
        a, b, c0 = (m[i][3] / m[i][i] for i in range(3))
        mean_t = sum(t for _, _, t, _ in rows_) / len(rows_)
        ss_tot = sum((t - mean_t) ** 2 for _, _, t, _ in rows_)
        ss_res = sum((t - (a * nbr + b * kd + c0)) ** 2 for nbr, kd, t, _ in rows_)
        return a, b, c0, 1.0 - ss_res / ss_tot

    rows = []
    reg_macros = ["% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit."]
    reg_a = {}
    reg_n = None
    for eng, lab in (("cpp", "C++"), ("rust", "Rust")):
        data_rows = reg_rows(eng)
        reg_n = len(data_rows)
        a, b, c0, r2 = fit(data_rows)
        # Seeded bootstrap (row resampling) for 95% coefficient CIs.
        rng = random.Random(20260712)
        boots = {"a": [], "b": [], "c": []}
        for _ in range(2000):
            sample = [data_rows[rng.randrange(reg_n)] for _ in range(reg_n)]
            try:
                aa, bb, cc, _ = fit(sample)
            except ZeroDivisionError:
                continue  # degenerate resample
            boots["a"].append(aa)
            boots["b"].append(bb)
            boots["c"].append(cc)
        for k in boots:
            boots[k].sort()

        def ci(k):
            xs = boots[k]
            return xs[int(0.025 * len(xs))], xs[int(0.975 * len(xs))]

        a_lo, a_hi = ci("a")
        b_lo, b_hi = ci("b")
        c_lo, c_hi = ci("c")
        # Leave-one-out prediction error.
        loo = []
        for i in range(reg_n):
            a2, b2, c2, _ = fit(data_rows[:i] + data_rows[i + 1 :])
            nbr, kd, t, name = data_rows[i]
            loo.append((100.0 * abs(a2 * nbr + b2 * kd + c2 - t) / t, name))
        loo.sort()
        loo_med, loo_max, loo_worst = loo[reg_n // 2][0], loo[-1][0], loo[-1][1]
        rows.append(
            f"{lab} & {a * 1e6:.1f} [{a_lo * 1e6:.0f},\\,{a_hi * 1e6:.0f}] "
            f"& {b * 1e6:.1f} [{b_lo * 1e6:.0f},\\,{b_hi * 1e6:.0f}] "
            f"& {c0:.1f} [{c_lo:.0f},\\,{c_hi:.0f}] & {r2:.4f}"
        )
        cap = "Cpp" if eng == "cpp" else "Rust"
        reg_a[eng] = a
        reg_macros.append(rf"\newcommand{{\regKernelNs{cap}}}{{{a * 1e6:.0f}}}")
        reg_macros.append(rf"\newcommand{{\regKdNs{cap}}}{{{b * 1e6:.0f}}}")
        reg_macros.append(rf"\newcommand{{\regRsq{cap}}}{{{r2:.4f}}}")
        reg_macros.append(rf"\newcommand{{\regLooMed{cap}}}{{{loo_med:.0f}}}")
        reg_macros.append(rf"\newcommand{{\regLooMax{cap}}}{{{loo_max:.0f}}}")
        reg_macros.append(
            rf"\newcommand{{\regLooWorst{cap}}}{{{LABEL.get(loo_worst, loo_worst)}}}"
        )
        # NOTE: on the Profile-B data the C++/Rust kernel-cost CIs overlap (collinearity
        # 0.99 leaves the individual coefficients under-identified); Sec. V-D therefore
        # treats the coefficient gap as indicative only and defers the engine comparison
        # to the direct per-fixture ratios of Table II. No disjointness guard.
    # Collinearity between the two regressors over the pooled design (engine-independent).
    xs = [r[0] for r in reg_rows("cpp")]
    ys = [r[1] for r in reg_rows("cpp")]
    mx, my = sum(xs) / len(xs), sum(ys) / len(ys)
    corr = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / math.sqrt(
        sum((x - mx) ** 2 for x in xs) * sum((y - my) ** 2 for y in ys)
    )
    reg_macros.append(rf"\newcommand{{\regN}}{{{reg_n}}}")
    reg_macros.append(rf"\newcommand{{\regCorr}}{{{corr:.2f}}}")
    reg_macros.append(
        rf"\newcommand{{\regKernelRatio}}{{{reg_a['cpp'] / reg_a['rust']:.1f}}}"
    )
    (OUT / "regression_macros.tex").write_text("\n".join(reg_macros) + "\n", encoding="utf-8")
    print("wrote tables/regression_macros.tex")
    write(
        "regression.tex",
        rf"Unit-cost regression $T_{{p50}} \approx a\cdot\sumnbr + b\cdot\kdnodes + c$ "
        rf"over the fixtures pooled with the $P$-sweep points ($n={reg_n}$; brackets: "
        rf"95\% bootstrap CIs; regressor correlation {corr:.2f}).",
        "tab:regression",
        "lrrrr",
        r"engine & $a$ (\si{ns}/kernel eval) & $b$ (\si{ns}/kd node) & $c$ (\si{ms}) & $R^2$",
        rows,
        note=prov,
    )
    # (The exploratory Gumbel block-maxima table was replaced by scripts/evt.py's
    # diagnostics-gated POT/GPD analysis -- roadmap C2.)


def legal_macros(timing, rust):
    """Prose macros for the two-tier bound (skipped when legal_worst is absent)."""
    if "legal_worst" not in timing or "search_00" not in timing:
        print("legal_worst absent -- skipping legal macros")
        return
    lw = timing["legal_worst"]
    un = timing["search_00"]
    c = rust["legal_worst"]["counters"]
    kbar = c["sum_neighbors"] / c["points_processed"]
    lw_cpp = max(lw["cpp"]["samples_ms"])
    lw_rust = max(lw["rust"]["samples_ms"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\legalWorstMaxCpp}}{{{lw_cpp:.1f}}}",
        rf"\newcommand{{\legalWorstMaxRust}}{{{lw_rust:.1f}}}",
        rf"\newcommand{{\legalWorstKbar}}{{{kbar:.1f}}}",
        rf"\newcommand{{\legalWorstRatioRust}}{{{max(un['rust']['samples_ms']) / lw_rust:.1f}}}",
        rf"\newcommand{{\legalWorstRatioCpp}}{{{max(un['cpp']['samples_ms']) / lw_cpp:.1f}}}",
    ]
    if "legal_osc" in timing:
        lo = timing["legal_osc"]
        oc = rust["legal_osc"]["counters"]
        macros += [
            rf"\newcommand{{\legalOscMaxCpp}}{{{max(lo['cpp']['samples_ms']):.1f}}}",
            rf"\newcommand{{\legalOscMaxRust}}{{{max(lo['rust']['samples_ms']):.1f}}}",
            rf"\newcommand{{\legalOscKbar}}{{{oc['sum_neighbors'] / oc['points_processed']:.1f}}}",
        ]
    (OUT / "legal_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/legal_macros.tex")


def realdata():
    """Operational-envelope table + macros from the real-drive capture (skipped if absent)."""
    rj = DATA / "realdata.json"
    if not rj.exists():
        print("realdata absent -- skipping operational-envelope outputs")
        return
    rdoc = json.loads(rj.read_text())
    if rdoc.get("meta", {}).get("measurement_profile") != "A":
        raise SystemExit(
            "realdata.json lacks the Profile-A meta -- Sec. V-G presents Profile-A results; "
            "regenerate via the open-loop replay protocol (tables must not mix profiles)")
    allframes = rdoc["frames"]
    timing = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    # Envelope rows use the on-map frames (the vehicle leaves the benchmark's cropped map for
    # most of the 57-min bag); P and max-K contract checks use ALL frames.
    frames = [f for f in allframes if f["counters"]["sum_neighbors"] > 0]

    def series(f):
        return sorted(f(x) for x in frames)

    p = sorted(x["n_source"] for x in allframes)
    it = series(lambda x: x["iteration_num"])
    kbar = series(
        lambda x: x["counters"]["sum_neighbors"] / max(x["counters"]["points_processed"], 1)
    )
    kmax = sorted(x["counters"]["max_neighbors"] for x in allframes)
    kd = series(
        lambda x: x["counters"]["kd_nodes_visited"] / max(x["counters"]["points_processed"], 1)
    )
    cpp = series(lambda x: x["cpp_ms"])
    rust = series(lambda x: x["rust_ms"])
    match = sum(1 for x in allframes if x["match"])
    # Honest-denominator split (review #10): divergences counted against the on-map subset.
    onmap_match = sum(1 for x in frames if x["match"])
    div_all = len(allframes) - match
    div_onmap = len(frames) - onmap_match
    if div_onmap != div_all:
        # The prose claims every divergence is on-map; regenerate-or-break, never stale.
        raise SystemExit(
            f"realdata: {div_all - div_onmap} divergence(s) off-map -- "
            "prose claims all divergences are on-map; update the paper text"
        )
    offmap = [x for x in allframes if x["counters"]["sum_neighbors"] == 0]
    offmap_iter = sorted(x["iteration_num"] for x in offmap)
    offmap_cpp = sorted(x["cpp_ms"] for x in offmap)
    onmap_seq_max = max(x["seq"] for x in frames)
    # Share of on-map frames that hit the iteration cap (prose: "routinely reached").
    itercap = sum(1 for x in frames if x["iteration_num"] >= it[-1])
    # B5 scenario breakdown: on-map segment structure + where the divergences sit.
    seqs = sorted(x["seq"] for x in frames)
    seg_bounds = []
    start = prev = seqs[0]
    for s in seqs[1:]:
        if s == prev + 1:
            prev = s
            continue
        seg_bounds.append((start, prev))
        start = prev = s
    seg_bounds.append((start, prev))
    mism = [x for x in allframes if not x["match"]]
    div_segs = len(
        {
            next(i for i, (a, b) in enumerate(seg_bounds) if a <= x["seq"] <= b)
            for x in mism
        }
    )
    mism_iters = sorted(x["iteration_num"] for x in mism)
    mism_at_cap = sum(1 for x in mism if x["iteration_num"] >= it[-1])
    mism_cpp_max = max(x["cpp_ms"] for x in mism)
    # Deadline overruns at 10 Hz (policy: report frames > 100 ms). The prose claims C++
    # overruns exist under Profile A while Rust never overruns; regenerate-or-break.
    over_cpp = sum(1 for x in allframes if x["cpp_ms"] > 100.0)
    over_cpp_onmap = sum(1 for x in frames if x["cpp_ms"] > 100.0)
    over_rust = sum(1 for x in allframes if x["rust_ms"] > 100.0)
    if over_cpp == 0:
        raise SystemExit(
            "no C++ frame exceeds 100 ms in realdata.json -- the Sec. V-G Profile-A "
            "overrun paragraph is stale; update the prose")
    if over_rust != 0:
        raise SystemExit(
            f"{over_rust} Rust frames exceed 100 ms -- the prose claims zero Rust "
            "overruns; update Sec. V-G")

    rows = []
    for label, xs, fmt in (
        (r"$P$ (points)", p, "{:.0f}"),
        (r"$N_{\mathrm{iter}}$", it, "{:.0f}"),
        (r"$\bar{K}$ (mean neighbors/pt)", kbar, "{:.2f}"),
        (r"max $K$ (per point)", kmax, "{:.0f}"),
        (r"kd nodes / pt", kd, "{:.1f}"),
        (r"C++ align (\si{ms})", cpp, "{:.2f}"),
        (r"Rust align (\si{ms})", rust, "{:.2f}"),
    ):
        rows.append(
            f"{label} & {fmt.format(pct(xs, 0.5))} & {fmt.format(pct(xs, 0.99))} "
            f"& {fmt.format(xs[-1])}"
        )
    write(
        "realdata.tex",
        rf"Real-data replay (İstanbul urban drive, open-loop frozen guess track), "
        r"\textbf{Profile A} (production-representative: CFS, unpinned, one align per "
        r"frame): per-frame distributions.",
        "tab:realdata",
        "lrrr",
        r"metric & p50 & p99 & max",
        rows,
        note=rf"$P$ and max $K$ over all \num{{{len(allframes)}}} frames; other rows over the "
        rf"\num{{{len(frames)}}} on-map frames (frames whose radius searches return any "
        rf"neighbor; the drive leaves the benchmark's cropped map after frame "
        rf"\num{{{onmap_seq_max}}}). Equal work: \num{{{match}}}/\num{{{len(allframes)}}} "
        rf"overall, on-map \num{{{onmap_match}}}/\num{{{len(frames)}}} "
        rf"({100.0 * onmap_match / len(frames):.1f}\%) --- all {div_all} divergences are "
        rf"on-map.",
    )

    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\realFrames}}{{\num{{{len(allframes)}}}}}",
        rf"\newcommand{{\realOnMap}}{{{len(frames)}}}",
        rf"\newcommand{{\realOffMap}}{{\num{{{len(allframes) - len(frames)}}}}}",
        rf"\newcommand{{\realMatch}}{{\num{{{match}}}}}",
        rf"\newcommand{{\realMatchPct}}{{{100.0 * match / len(allframes):.1f}}}",
        rf"\newcommand{{\realDivergences}}{{{div_all}}}",
        rf"\newcommand{{\realDivPctAll}}{{{100.0 * div_all / len(allframes):.2f}}}",
        rf"\newcommand{{\realOnMapMatch}}{{{onmap_match}}}",
        rf"\newcommand{{\realOnMapMatchPct}}{{{100.0 * onmap_match / len(frames):.1f}}}",
        rf"\newcommand{{\realOnMapDivPct}}{{{100.0 * div_onmap / len(frames):.1f}}}",
        rf"\newcommand{{\realOffMapIterMed}}{{{pct(offmap_iter, 0.5):.0f}}}",
        rf"\newcommand{{\realOffMapCppMed}}{{{pct(offmap_cpp, 0.5):.1f}}}",
        rf"\newcommand{{\realOnMapSeqMax}}{{{onmap_seq_max}}}",
        rf"\newcommand{{\realIterCapPct}}{{{100.0 * itercap / len(frames):.0f}}}",
        rf"\newcommand{{\realSegments}}{{{len(seg_bounds)}}}",
        rf"\newcommand{{\realDivSegments}}{{{div_segs}}}",
        rf"\newcommand{{\realDivIterMin}}{{{mism_iters[0]}}}",
        rf"\newcommand{{\realDivIterMax}}{{{mism_iters[-1]}}}",
        rf"\newcommand{{\realDivAtCap}}{{{mism_at_cap}}}",
        rf"\newcommand{{\realDivCppMax}}{{{mism_cpp_max:.1f}}}",
        rf"\newcommand{{\realIterMax}}{{{it[-1]}}}",
        rf"\newcommand{{\realKmaxMax}}{{{kmax[-1]}}}",
        rf"\newcommand{{\realPMax}}{{{p[-1]}}}",
        rf"\newcommand{{\realRustMax}}{{{rust[-1]:.1f}}}",
        rf"\newcommand{{\realCppMax}}{{{cpp[-1]:.1f}}}",
        rf"\newcommand{{\realOverrunsCpp}}{{{over_cpp}}}",
        rf"\newcommand{{\realOverrunsCppOnMapPct}}{{{100.0 * over_cpp_onmap / len(frames):.0f}}}",
        rf"\newcommand{{\realCppMedOnMap}}{{{pct(cpp, 0.5):.1f}}}",
    ]
    if "legal_worst" in timing and "search_00" in timing:
        lw = max(timing["legal_worst"]["rust"]["samples_ms"])
        un = max(timing["search_00"]["rust"]["samples_ms"])
        macros += [
            rf"\newcommand{{\realMarginDeploy}}{{{lw / rust[-1]:.1f}}}",
            rf"\newcommand{{\realMarginEngine}}{{{un / rust[-1]:.0f}}}",
        ]
    (OUT / "realdata_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/realdata_macros.tex")


def bridge():
    """A/B bridge table + macros (policy: Bridge Experiment) from data/bridge.json
    (skipped if absent): the same five frozen inputs under Profile A (production CFS)
    and Profile B (isolated core), per-engine inflation ratios."""
    bj = DATA / "bridge.json"
    if not bj.exists():
        print("bridge data absent -- skipping bridge outputs")
        return
    doc = json.loads(bj.read_text())
    inputs = doc["inputs"]
    order = ["search_00", "legal_worst", "legal_osc", "real_slowest", "real_median"]
    label = {"search_00": r"\emph{search-00}", "legal_worst": r"\emph{legal-worst}",
             "legal_osc": r"\emph{legal-osc}", "real_slowest": r"\emph{real-slowest}",
             "real_median": r"\emph{real-median}"}
    rows = []
    infl = {"cpp": [], "rust": []}
    for fx in order:
        e = inputs[fx]
        for eng in ("cpp", "rust"):
            v = e[eng]
            infl[eng].append(v["inflation_max"])
            a, b = v["profile_a"], v["profile_b"]
            rows.append(
                f"{label[fx] if eng == 'cpp' else ''} & {eng} & "
                f"{b['p50_ms']:.1f} & {b['max_ms']:.1f} & "
                f"{a['p50_ms']:.1f} & {a['max_ms']:.1f} & "
                f"\\textbf{{{v['inflation_max']:.2f}}}"
            )
    # Guards: the prose claims Rust A/B ~= 1 and a C++ controlled-environment tax (< 1).
    if not all(0.95 <= r <= 1.05 for r in infl["rust"]):
        raise SystemExit(f"bridge: Rust inflation outside ~1 ({infl['rust']}) -- "
                         "the Sec. V bridge prose claims ~=1.01; update it")
    if not all(r < 1.0 for r in infl["cpp"]):
        raise SystemExit(f"bridge: C++ inflation not uniformly < 1 ({infl['cpp']}) -- "
                         "the controlled-environment-tax story is stale; update the prose")
    write(
        "bridge.tex",
        r"Bridge experiment: the same frozen inputs under \textbf{Profile B} (controlled: "
        r"isolated core, SMT sibling offline, IRQs moved) and \textbf{Profile A} "
        r"(production-representative: normal CFS, unpinned, SMT on), same "
        r"\SI{3.2}{GHz} reference clock. inflation = A/B at the maximum (descriptive only).",
        "tab:bridge",
        "llrrrrr",
        r"input & engine & \multicolumn{2}{c}{B p50 / max (ms)} "
        r"& \multicolumn{2}{c}{A p50 / max (ms)} & infl.",
        rows,
        note=r"Iteration counts identical across profiles on every input (equal work). "
        r"Synthetic Profile-B legs: pooled 3-session campaign; real-frame legs: dedicated "
        r"controlled session; Profile A: one session, 100 samples per cell.",
    )
    # C++ per-align controlled-environment tax on the three P=2000/31-pass synthetics.
    syn = ["search_00", "legal_worst", "legal_osc"]
    taxes = [inputs[fx]["cpp"]["profile_b"]["max_ms"] - inputs[fx]["cpp"]["profile_a"]["max_ms"]
             for fx in syn]
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\bridgeCppInflMin}}{{{min(infl['cpp']):.2f}}}",
        rf"\newcommand{{\bridgeCppInflMax}}{{{max(infl['cpp']):.2f}}}",
        rf"\newcommand{{\bridgeRustInflMin}}{{{min(infl['rust']):.2f}}}",
        rf"\newcommand{{\bridgeRustInflMax}}{{{max(infl['rust']):.2f}}}",
        rf"\newcommand{{\bridgeCppTaxMinMs}}{{{min(taxes):.0f}}}",
        rf"\newcommand{{\bridgeCppTaxMaxMs}}{{{max(taxes):.0f}}}",
    ]
    (OUT / "bridge_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/bridge.tex + bridge_macros.tex")


def linfit(xs, ys):
    """Least-squares y = m*x + b; returns (m, b, r2)."""
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    m = sxy / sxx
    b = my - m * mx
    ss_res = sum((y - (m * x + b)) ** 2 for x, y in zip(xs, ys))
    ss_tot = sum((y - my) ** 2 for y in ys)
    return m, b, 1.0 - (ss_res / ss_tot if ss_tot > 0 else 0.0)


def psweep():
    """P-sweep table + pgfplots figure + prose macros (skipped if the data is absent)."""
    tj = DATA / "wcet_psweep.json"
    rj = DATA / "psweep_rust.json"
    if not (tj.exists() and rj.exists()):
        print("psweep data absent -- skipping psweep outputs")
        return
    timing = json.loads(tj.read_text())["fixtures"]
    rust = json.loads(rj.read_text())["fixtures"]
    names = sorted(timing, key=lambda n: rust[n]["n_source"])
    ps = [rust[n]["n_source"] for n in names]

    # Work-invariance check: sum_neighbors == P * 64 * 31 at every P.
    for n in names:
        c = rust[n]["counters"]
        assert c["sum_neighbors"] == rust[n]["n_source"] * 64 * 31, n
        assert rust[n]["iteration_num"] == 30, n

    stats = {}  # engine -> (p50s, maxs)
    for eng in ("cpp", "rust"):
        p50s, maxs = [], []
        for n in names:
            xs = sorted(timing[n][eng]["samples_ms"])
            p50s.append(pct(xs, 0.5))
            maxs.append(xs[-1])
        stats[eng] = (p50s, maxs)

    rows = []
    for i, n in enumerate(names):
        rows.append(
            f"{num(ps[i])} & {stats['cpp'][0][i]:.1f} & {stats['cpp'][1][i]:.1f} "
            f"& {stats['rust'][0][i]:.1f} & {stats['rust'][1][i]:.1f}"
        )
    write(
        "psweep.tex",
        r"$P$-sweep on the union-worst geometry (\si{ms}; work invariance verified: "
        r"$N_{\mathrm{iter}}{=}30$, $\sumnbr = P \cdot 64 \cdot 31$ exactly at every $P$).",
        "tab:psweep",
        "rrrrr",
        r"$P$ & \multicolumn{2}{c}{C++ (p50 / max)} & \multicolumn{2}{c}{Rust (p50 / max)}",
        rows,
        note=r"The sweep \emph{regenerates} the union-worst geometry at each $P$; its "
        r"$P{=}2000$ row is a distinct fixture instance from --- and so differs slightly "
        r"from --- the frozen \emph{search-00} of Table~\ref{tab:tails}. Same host and "
        r"protocol as Table~\ref{tab:tails} (Sec.~\ref{sec:evaluation}).",
    )

    # Fits on the max series (the WCET-relevant one) and p50 for the macros.
    fits = {}
    for eng in ("cpp", "rust"):
        m50, b50, r50 = linfit(ps, stats[eng][0])
        mmx, bmx, rmx = linfit(ps, stats[eng][1])
        fits[eng] = {"m50": m50, "b50": b50, "r50": r50, "mmx": mmx, "bmx": bmx, "rmx": rmx}

    # Prose macros (\psweep...) so the section text never hand-types a number.
    def us_per_pt(m):
        return f"{m * 1000:.0f}"

    pmax_cpp = int((100.0 - fits["cpp"]["bmx"]) / fits["cpp"]["mmx"])
    pmax_rust = int((100.0 - fits["rust"]["bmx"]) / fits["rust"]["mmx"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\psweepSlopeCpp}}{{{us_per_pt(fits['cpp']['mmx'])}}}",
        rf"\newcommand{{\psweepSlopeRust}}{{{us_per_pt(fits['rust']['mmx'])}}}",
        rf"\newcommand{{\psweepInterceptCpp}}{{{fits['cpp']['bmx']:.1f}}}",
        rf"\newcommand{{\psweepInterceptRust}}{{{fits['rust']['bmx']:.1f}}}",
        rf"\newcommand{{\psweepRsqCpp}}{{{fits['cpp']['rmx']:.4f}}}",
        rf"\newcommand{{\psweepRsqRust}}{{{fits['rust']['rmx']:.4f}}}",
        rf"\newcommand{{\psweepPmaxCpp}}{{{num(pmax_cpp)}}}",
        rf"\newcommand{{\psweepPmaxRust}}{{{num(pmax_rust)}}}",
        rf"\newcommand{{\psweepPmin}}{{{num(min(ps))}}}",
        rf"\newcommand{{\psweepPmax}}{{{num(max(ps))}}}",
    ]
    (OUT / "psweep_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/psweep_macros.tex")

    # pgfplots figure: max latency vs P, measured points + fitted lines.
    fig_dir = ROOT / "figures"
    fig_dir.mkdir(exist_ok=True)

    def coords(ys):
        return " ".join(f"({p},{y:.2f})" for p, y in zip(ps, ys))

    def fitline(f):
        return f"({min(ps)},{f['mmx'] * min(ps) + f['bmx']:.2f}) ({max(ps)},{f['mmx'] * max(ps) + f['bmx']:.2f})"

    fig = rf"""% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.
\begin{{figure}}[t]
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
  width=\columnwidth, height=0.62\columnwidth,
  xlabel={{source points $P$}}, ylabel={{max align time (ms)}},
  xmin=0, ymin=0, legend pos=north west, legend cell align=left,
  grid=major, tick label style={{font=\footnotesize}}, label style={{font=\footnotesize}},
  legend style={{font=\footnotesize}},
]
\addplot[only marks, mark=square*, color=blue] coordinates {{ {coords(stats['cpp'][1])} }};
\addlegendentry{{C++ (measured max)}}
\addplot[no marks, color=blue, dashed] coordinates {{ {fitline(fits['cpp'])} }};
\addlegendentry{{C++ fit ($R^2={fits['cpp']['rmx']:.4f}$)}}
\addplot[only marks, mark=*, color=red] coordinates {{ {coords(stats['rust'][1])} }};
\addlegendentry{{Rust (measured max)}}
\addplot[no marks, color=red, dashed] coordinates {{ {fitline(fits['rust'])} }};
\addlegendentry{{Rust fit ($R^2={fits['rust']['rmx']:.4f}$)}}
\end{{axis}}
\end{{tikzpicture}}
\caption{{Max align latency vs.\ source-point count $P$ on the union-worst geometry
(work per point held invariant; counters verified). Both engines are affine in $P$.}}
\label{{fig:psweep}}
\end{{figure}}
"""
    (fig_dir / "psweep.tex").write_text(fig, encoding="utf-8")
    print("wrote figures/psweep.tex")

    # Residual report (stdout only): flag a cache knee if the largest relative residual is big.
    for eng in ("cpp", "rust"):
        f = fits[eng]
        res = [
            (p, y - (f["mmx"] * p + f["bmx"])) for p, y in zip(ps, stats[eng][1])
        ]
        worst = max(res, key=lambda t: abs(t[1]))
        print(f"psweep {eng}: slope {f['mmx']*1000:.0f} us/pt, intercept {f['bmx']:.1f} ms, "
              f"R2(max) {f['rmx']:.4f}, worst residual {worst[1]:+.1f} ms at P={worst[0]}")


def main_extra():
    timing = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    legal_macros(timing, rust)


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    main()
    main_extra()
    realdata()
    psweep()
    cert_macros()
    legal_k_macros()
    ablation()
    bridge()
    raspi4()
    interference()
