#!/usr/bin/env python3
"""Generate the paper's LaTeX tables from the frozen measurement JSONs (stdlib-only).

Inputs (paper/data/): wcet.json (replay timing, both engines), wcet_rust.json (counters),
wcet_alloc.json (LD_PRELOAD allocation pass); optionally wcet_psweep.json + psweep_rust.json
(the P-sweep replay + counters).
Outputs (paper/tables/): counters.tex, tails.tex, alloc.tex, regression.tex, gumbel.tex;
prose-macro files (*_macros.tex: tails, gumbel, regression, legal, realdata, psweep, env,
oneoff) so no measurement number is ever hand-typed in the .tex sources; with psweep data
also tables/psweep.tex and figures/psweep.tex (pgfplots).

Regenerate after any re-measurement:  python3 scripts/gen_tables.py
Never hand-edit tables/*.tex or figures/*.tex — they are build products (kept in git so the
paper builds without re-running the benchmark).

The generator also *asserts* the rounded qualitative claims the prose makes ("under 10 ms to
over 600 ms", "grazing the 100 ms budget", "the same per-point constant", the search-log kd
baseline): if a re-measurement falsifies one, generation fails instead of leaving stale prose.
"""

import json
import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "tables"

EULER_GAMMA = 0.5772156649015329
# Display order: worst first.
ORDER = [
    "search_00",
    "search_01",
    "dense_neighbors",
    "max_iterations",
    "cache_hostile",
    "subnormal",
    "legal_worst",
    "legal_osc",
]
LABEL = {
    "search_00": r"\emph{search-00}",
    "search_01": r"\emph{search-01}",
    "dense_neighbors": r"\emph{dense-nbrs}",
    "max_iterations": r"\emph{max-iters}",
    "cache_hostile": r"\emph{cache-hostile}",
    "subnormal": r"\emph{subnormal}",
    "legal_worst": r"\emph{legal-worst}$^\dagger$",
    "legal_osc": r"\emph{legal-osc}$^\dagger$",
}
# Shared table footnote for the tier markers.
TIER_NOTE = (r"\emph{search-00} is the union-worst search output; "
             r"$^\dagger$\,deployment-tier fixtures.")

# One-off side measurements quoted in the prose but not captured in data/*.json.
# Each entry documents its source; C1 of plan/paper_fix.md re-measures or archives them.
# Emitted as \oneoff* macros (tables/oneoff_macros.tex) so the .tex sources never hand-type
# them; where a derived quantity depends on one (kd growth %, allocator share), the
# derivation lives here too and is guarded by an assertion against the frozen data.
ONEOFF = {
    # Counter-guided search log (2026-07-10 session, not archived): kd_nodes_visited of the
    # generation-0 candidate. The gen-23 output is the frozen search-00; its kd value is
    # derived from wcet_rust.json and asserted below so this baseline cannot silently pair
    # with a different search run.
    "kd_gen_zero_m": 8.88,
    # Subnormal A/B (2026-07-10 session): same fixture regenerated with the source shell at
    # 1.69 m instead of 1.99 m, moving every kernel exp() result out of the f64 subnormal
    # band; p50 ms per engine, same replay protocol as wcet.json.
    "shell_sub_cpp_ms": 57.6,
    "shell_ctrl_cpp_ms": 58.6,
    "shell_sub_rust_ms": 8.0,
    "shell_ctrl_rust_ms": 8.9,
    # exp() microbenchmark (2026-07-10 session): subnormal-result vs normal-result cost per
    # call, glibc exp vs the port's pure-Rust libm.
    "exp_sub_ratio_glibc": 2.9,
    "exp_sub_ratio_libm": 5.1,
    # Allocator fast-path microbenchmark (2026-07-10 session): one malloc/free pair, ns,
    # thread-cache hit, same host.
    "malloc_pair_ns": 11.3,
    # Iterative vs recursive kd radius search (port development, same day / same core), %.
    "kd_iter_speedup_pct": 12,
    # legal-worst rerun at the shipped epsilon = 0.01: converges in this many iterations
    # (2026-07-10 session; motivates the epsilon-pinned iteration axis).
    "legal_worst_prod_eps_iters": 2,
    # Differential-test bound on the eigensolver deviation over the inverse covariances
    # (glibc/LAPACK vs the port), from the divergence root-cause session (2026-07-10).
    "eigensolver_bound": r"2\times10^{-15}",
}


def pct(sorted_xs, p):
    return sorted_xs[min(int(p * (len(sorted_xs) - 1)), len(sorted_xs) - 1)]


def num(x):
    """LaTeX-format an integer with thin-space thousands separators via siunitx."""
    return rf"\num{{{x}}}"


def write(name, caption, label, colspec, header, rows, note=None):
    lines = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        rf"\begin{{tabular}}{{{colspec}}}",
        r"\toprule",
        header + r" \\",
        r"\midrule",
    ]
    lines += [r + r" \\" for r in rows]
    lines += [r"\bottomrule", r"\end{tabular}"]
    if note:
        lines.append(rf"\par\smallskip\footnotesize {note}")
    lines.append(r"\end{table}")
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote tables/{name}")


def tex_escape(s):
    """Escape the characters that actually occur in the env strings."""
    return s.replace("~", r"\textasciitilde{}").replace("_", r"\_")


def provenance(env, meta):
    """One generated sentence carried by every timing-table note (review #8)."""
    return (
        rf"Run: captured {env['Captured (UTC)'][:10]} (UTC), {env['CPU governor']} governor "
        rf"(container), {meta['iters']} aligns/fixture after {meta['warmup']} warmups, "
        rf"\texttt{{{tex_escape(env['CPU pinning'])}}}."
    )


def env_macros(env, meta):
    """Measurement-environment macros so Sec. V-A can never drift from the data."""
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\envCpu}}{{{tex_escape(env['CPU'])}}}",
        rf"\newcommand{{\envKernel}}{{{tex_escape(env['Kernel'])}}}",
        rf"\newcommand{{\envCppCompiler}}{{{tex_escape(env['C++ compiler'])}}}",
        rf"\newcommand{{\envRustCompiler}}{{{tex_escape(env['Rust compiler'])}}}",
        rf"\newcommand{{\envGovernor}}{{{env['CPU governor']}}}",
        rf"\newcommand{{\envPinning}}{{\texttt{{{tex_escape(env['CPU pinning'])}}}}}",
        rf"\newcommand{{\envDate}}{{{env['Captured (UTC)'][:10]}}}",
        rf"\newcommand{{\envIters}}{{{meta['iters']}}}",
        rf"\newcommand{{\envWarmup}}{{{meta['warmup']}}}",
    ]
    (OUT / "env_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/env_macros.tex")


def oneoff_macros():
    """Macros for the one-off side measurements (see the ONEOFF dict for provenance)."""
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        "% One-off side measurements not in data/*.json; sources documented at the ONEOFF",
        "% dict in scripts/gen_tables.py. C1 of plan/paper_fix.md re-measures/archives them.",
        rf"\newcommand{{\oneoffKdGenZeroM}}{{{ONEOFF['kd_gen_zero_m']:.2f}}}",
        rf"\newcommand{{\oneoffShellSubCpp}}{{{ONEOFF['shell_sub_cpp_ms']:.1f}}}",
        rf"\newcommand{{\oneoffShellCtrlCpp}}{{{ONEOFF['shell_ctrl_cpp_ms']:.1f}}}",
        rf"\newcommand{{\oneoffShellSubRust}}{{{ONEOFF['shell_sub_rust_ms']:.1f}}}",
        rf"\newcommand{{\oneoffShellCtrlRust}}{{{ONEOFF['shell_ctrl_rust_ms']:.1f}}}",
        rf"\newcommand{{\oneoffExpSubGlibc}}{{{ONEOFF['exp_sub_ratio_glibc']:.1f}}}",
        rf"\newcommand{{\oneoffExpSubLibm}}{{{ONEOFF['exp_sub_ratio_libm']:.1f}}}",
        rf"\newcommand{{\oneoffMallocPairNs}}{{{ONEOFF['malloc_pair_ns']:.1f}}}",
        rf"\newcommand{{\oneoffKdIterSpeedup}}{{{ONEOFF['kd_iter_speedup_pct']}}}",
        rf"\newcommand{{\oneoffLegalWorstProdEpsIters}}{{{ONEOFF['legal_worst_prod_eps_iters']}}}",
        rf"\newcommand{{\oneoffEigensolverBound}}{{{ONEOFF['eigensolver_bound']}}}",
    ]
    (OUT / "oneoff_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/oneoff_macros.tex")


def main():
    doc = json.loads((DATA / "wcet.json").read_text())
    timing = doc["fixtures"]
    env = doc.get("env", {})
    meta = doc.get("meta", {})
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    alloc = json.loads((DATA / "wcet_alloc.json").read_text())["fixtures"]
    names = [n for n in ORDER if n in timing]
    prov = provenance(env, meta)
    env_macros(env, meta)
    oneoff_macros()

    # ---- counters.tex ----
    rows = []
    for n in names:
        c = rust[n]["counters"]
        rows.append(
            f"{LABEL[n]} & {rust[n]['iteration_num']} & {num(c['sum_neighbors'])} "
            f"& {num(c['kd_nodes_visited'])} & {num(rust[n]['n_map'])} & {rust[n]['n_tiles']}"
        )
    write(
        "counters.tex",
        r"Frozen fixtures: deterministic work counters (platform-independent; "
        r"$P=2000$ for the search outputs).",
        "tab:counters",
        "lrrrrr",
        r"fixture & $N_{\mathrm{iter}}$ & \sumnbr{} & \kdnodes{} & map pts & tiles",
        rows,
        note=r"$\sumnbr = \num{3968000} = 2000 \cdot 64 \cdot 31$ on "
        r"\emph{search-00}: the analytic kernel-evaluation maximum, reached exactly. " + TIER_NOTE,
    )

    # ---- tails.tex ----
    rows = []
    ratios = {}
    p50 = {}  # (fixture, engine) -> p50 ms
    mx = {}  # (fixture, engine) -> max ms
    for n in names:
        fx = timing[n]
        cs = sorted(fx["cpp"]["samples_ms"])
        rs = sorted(fx["rust"]["samples_ms"])
        p50[(n, "cpp")], p50[(n, "rust")] = pct(cs, 0.5), pct(rs, 0.5)
        mx[(n, "cpp")], mx[(n, "rust")] = cs[-1], rs[-1]
        ratios[n] = rs[-1] / cs[-1]
        rows.append(
            f"{LABEL[n]} & {pct(cs, 0.5):.1f} & {cs[-1]:.1f} & {pct(rs, 0.5):.1f} "
            f"& {rs[-1]:.1f} & \\textbf{{{ratios[n]:.2f}}}"
        )
    write(
        "tails.tex",
        rf"Frame time per engine (\si{{ms}}; {meta['iters']} aligns/fixture, serial, "
        r"pinned core). Equal work certified per fixture (identical "
        r"\texttt{iteration\_num}).",
        "tab:tails",
        "lrrrrr",
        r"fixture & \multicolumn{2}{c}{C++ (p50 / max)} "
        r"& \multicolumn{2}{c}{Rust (p50 / max)} & ratio",
        rows,
        note=r"ratio = Rust max / C++ max; $<1$ everywhere. " + TIER_NOTE + " " + prov,
    )

    # ---- tails_macros.tex: timing/counter/alloc-derived prose numbers ----
    # Per-point-per-pass cost (us) on the neighbor-sparse fixtures; points_processed
    # already equals passes * P.
    def pt_pass_us(n, eng):
        return p50[(n, eng)] * 1000.0 / rust[n]["counters"]["points_processed"]

    def kbar_of(n):
        c = rust[n]["counters"]
        return c["sum_neighbors"] / c["points_processed"]

    gap_sub = pt_pass_us("subnormal", "cpp") - pt_pass_us("subnormal", "rust")
    gap_ch = pt_pass_us("cache_hostile", "cpp") - pt_pass_us("cache_hostile", "rust")
    # "reappears as the same constant on cache-hostile": the two gaps must stay close.
    if abs(gap_sub - gap_ch) > 0.15 * gap_sub:
        raise SystemExit(
            f"per-point overhead gap diverged (subnormal {gap_sub:.2f} vs "
            f"cache-hostile {gap_ch:.2f} us) -- prose claims 'the same constant'"
        )
    # Allocator share of the gap: ONEOFF fast-path pair cost x measured pairs per pt-pass.
    sub_pairs = alloc["subnormal"]["cpp"]["allocs_per_align"] / rust["subnormal"]["counters"][
        "points_processed"
    ]
    alloc_share = 100.0 * ONEOFF["malloc_pair_ns"] * sub_pairs / (gap_sub * 1000.0)
    # search-00 kd term and its growth over the ONEOFF search-log gen-0 baseline.
    kd_m = rust["search_00"]["counters"]["kd_nodes_visited"] / 1e6
    if abs(kd_m - 12.01) > 0.005:
        raise SystemExit(
            f"search-00 kd = {kd_m:.2f} M: fixture changed; the ONEOFF kd_gen_zero_m "
            "search-log baseline (and the derived growth %) no longer applies"
        )
    kd_growth = 100.0 * (kd_m / ONEOFF["kd_gen_zero_m"] - 1.0)
    # Two-tier kernel-evaluation drop.
    nbr_search = rust["search_00"]["counters"]["sum_neighbors"]
    nbr_legal = rust["legal_worst"]["counters"]["sum_neighbors"]
    # Alloc headline: worst fixture per align, and the per-(pt.pass) constant.
    alloc_worst = max(alloc[n]["cpp"]["allocs_per_align"] for n in names)
    app = alloc["search_00"]["cpp"]["allocs_per_align"] / rust["search_00"]["counters"][
        "points_processed"
    ]
    # "under 10 ms to over 600 ms" (intro spread claim).
    if not (min(p50.values()) < 10.0 and mx[("search_00", "cpp")] > 600.0
            and mx[("search_00", "rust")] > 600.0):
        raise SystemExit("intro spread claim (under 10 ms to over 600 ms) is stale")
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\tailsRatioMin}}{{{min(ratios.values()):.2f}}}",
        rf"\newcommand{{\tailsRatioMax}}{{{max(ratios.values()):.2f}}}",
        rf"\newcommand{{\tailsSearchMaxCpp}}{{{mx[('search_00', 'cpp')]:.1f}}}",
        rf"\newcommand{{\tailsSearchMaxRust}}{{{mx[('search_00', 'rust')]:.1f}}}",
        rf"\newcommand{{\subnormalMedianRatio}}{{{p50[('subnormal', 'cpp')] / p50[('subnormal', 'rust')]:.1f}}}",
        rf"\newcommand{{\subnormalPtPassCppUs}}{{{pt_pass_us('subnormal', 'cpp'):.1f}}}",
        rf"\newcommand{{\subnormalPtPassRustUs}}{{{pt_pass_us('subnormal', 'rust'):.2f}}}",
        rf"\newcommand{{\ptPassGapUs}}{{{gap_sub:.1f}}}",
        rf"\newcommand{{\subnormalKbar}}{{{kbar_of('subnormal'):.1f}}}",
        rf"\newcommand{{\cacheHostileKbar}}{{{kbar_of('cache_hostile'):.1f}}}",
        rf"\newcommand{{\subnormalAllocPairs}}{{{sub_pairs:.0f}}}",
        rf"\newcommand{{\subnormalAllocSharePct}}{{{alloc_share:.0f}}}",
        rf"\newcommand{{\searchZeroKdM}}{{{kd_m:.2f}}}",
        rf"\newcommand{{\searchKdGrowthPct}}{{{kd_growth:.0f}}}",
        rf"\newcommand{{\searchZeroSumNbrM}}{{{nbr_search / 1e6:.2f}}}",
        rf"\newcommand{{\legalWorstSumNbrK}}{{{nbr_legal / 1e3:.0f}}}",
        rf"\newcommand{{\twoTierKernelDrop}}{{{nbr_search / nbr_legal:.1f}}}",
        rf"\newcommand{{\allocWorstPerAlign}}{{\num{{{alloc_worst}}}}}",
        rf"\newcommand{{\allocPerPtPass}}{{{app:.0f}}}",
        rf"\newcommand{{\allocPerPtPassExact}}{{{app:.1f}}}",
    ]
    (OUT / "tails_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/tails_macros.tex")

    # ---- alloc.tex ----
    rows = []
    for n in names:
        fx = alloc[n]
        c = rust[n]["counters"]
        per_pp = fx["cpp"]["allocs_per_align"] / (
            c["derivative_passes"] * rust[n]["n_source"]
        )
        rows.append(
            f"{LABEL[n]} & {num(fx['cpp']['allocs_per_align'])} & {per_pp:.1f} "
            f"& {fx['rust']['allocs_per_align']}"
        )
    write(
        "alloc.tex",
        r"Heap allocations per align (\texttt{LD\_PRELOAD} interposer).",
        "tab:alloc",
        "lrrr",
        r"fixture & C++ / align & C++ / (pt$\cdot$pass) & Rust / align",
        rows,
        note=r"The constant ${\approx}11$ per point per pass locates the source in the "
        r"per-point inner loop (Sec.~\ref{sec:eval-alloc}). Rust: zero, matching the "
        r"allocation-freedom proof. " + TIER_NOTE + " " + prov,
    )

    # ---- regression.tex ----
    def fit(engine):
        rows_ = []
        for n in names:
            c = rust[n]["counters"]
            t50 = pct(sorted(timing[n][engine]["samples_ms"]), 0.5)
            rows_.append((float(c["sum_neighbors"]), float(c["kd_nodes_visited"]), t50))
        ata = [[0.0] * 3 for _ in range(3)]
        atb = [0.0] * 3
        for nbr, kd, t in rows_:
            x = (nbr, kd, 1.0)
            for i in range(3):
                for j in range(3):
                    ata[i][j] += x[i] * x[j]
                atb[i] += x[i] * t
        m = [row[:] + [atb[i]] for i, row in enumerate(ata)]
        for col in range(3):
            piv = max(range(col, 3), key=lambda r: abs(m[r][col]))
            m[col], m[piv] = m[piv], m[col]
            for r in range(3):
                if r != col:
                    f = m[r][col] / m[col][col]
                    for cc in range(col, 4):
                        m[r][cc] -= f * m[col][cc]
        a, b, c0 = (m[i][3] / m[i][i] for i in range(3))
        mean_t = sum(t for _, _, t in rows_) / len(rows_)
        ss_tot = sum((t - mean_t) ** 2 for _, _, t in rows_)
        ss_res = sum((t - (a * nbr + b * kd + c0)) ** 2 for nbr, kd, t in rows_)
        return a, b, c0, 1.0 - ss_res / ss_tot

    rows = []
    reg_macros = ["% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit."]
    reg_a = {}
    for eng, lab in (("cpp", "C++"), ("rust", "Rust")):
        a, b, c0, r2 = fit(eng)
        rows.append(f"{lab} & {a * 1e6:.1f} & {b * 1e6:.1f} & {c0:.2f} & {r2:.4f}")
        cap = eng.capitalize().replace("Cpp", "Cpp")
        cap = "Cpp" if eng == "cpp" else "Rust"
        reg_a[eng] = a
        reg_macros.append(rf"\newcommand{{\regKernelNs{cap}}}{{{a * 1e6:.0f}}}")
        reg_macros.append(rf"\newcommand{{\regKdNs{cap}}}{{{b * 1e6:.0f}}}")
        reg_macros.append(rf"\newcommand{{\regRsq{cap}}}{{{r2:.4f}}}")
    reg_macros.append(
        rf"\newcommand{{\regKernelRatio}}{{{reg_a['cpp'] / reg_a['rust']:.1f}}}"
    )
    (OUT / "regression_macros.tex").write_text("\n".join(reg_macros) + "\n", encoding="utf-8")
    print("wrote tables/regression_macros.tex")
    write(
        "regression.tex",
        rf"Unit-cost regression $T_{{p50}} \approx a\cdot\sumnbr + b\cdot\kdnodes + c$ "
        rf"over the fixture set ($n={len(names)}$).",
        "tab:regression",
        "lrrrr",
        r"engine & $a$ (\si{ns}/kernel eval) & $b$ (\si{ns}/kd node) & $c$ (\si{ms}) & $R^2$",
        rows,
        note=prov,
    )

    # ---- gumbel.tex ----
    def gumbel(xs, block=10):
        maxima = [max(xs[i : i + block]) for i in range(0, len(xs) - block + 1, block)]
        n = len(maxima)
        m = sum(maxima) / n
        s = math.sqrt(sum((x - m) ** 2 for x in maxima) / (n - 1))
        beta = s * math.sqrt(6.0) / math.pi
        return m - EULER_GAMMA * beta, beta

    rows = []
    betas = []
    exceed = {}  # engine -> % the 1e-9 quantile sits above the measured max (search_00)
    for n in names:
        for eng, lab in (("cpp", "C++"), ("rust", "Rust")):
            xs = timing[n][eng]["samples_ms"]
            mu, beta = gumbel(xs)
            q9 = mu - beta * math.log(-math.log(1.0 - 1e-9))
            betas.append(beta)
            if n == "search_00":
                exceed[eng] = 100.0 * (q9 / max(xs) - 1.0)
            first = LABEL[n] if eng == "cpp" else ""
            rows.append(
                f"{first} & {lab} & {mu:.1f} & {beta:.2f} & {q9:.1f} & {max(xs):.1f}"
            )
    write(
        "gumbel.tex",
        r"Gumbel block-maxima fit (moment estimator, $n{=}10$ blocks) and the "
        r"$10^{-9}$ per-block exceedance quantile (\si{ms}). Comparative, not certified "
        r"(Sec.~\ref{sec:threats}).",
        "tab:gumbel",
        "llrrrr",
        r"fixture & engine & $\mu$ & $\beta$ & $q_{10^{-9}}$ & max",
        rows,
        note=prov,
    )
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\gumbelBetaMin}}{{{min(betas):.2f}}}",
        rf"\newcommand{{\gumbelBetaMax}}{{{max(betas):.1f}}}",
        rf"\newcommand{{\gumbelExceedPctCpp}}{{{exceed['cpp']:.0f}}}",
        rf"\newcommand{{\gumbelExceedPctRust}}{{{exceed['rust']:.0f}}}",
    ]
    (OUT / "gumbel_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/gumbel_macros.tex")


def legal_macros(timing, rust):
    """Prose macros for the two-tier bound (skipped when legal_worst is absent)."""
    if "legal_worst" not in timing or "search_00" not in timing:
        print("legal_worst absent -- skipping legal macros")
        return
    lw = timing["legal_worst"]
    un = timing["search_00"]
    c = rust["legal_worst"]["counters"]
    kbar = c["sum_neighbors"] / c["points_processed"]
    lw_cpp = max(lw["cpp"]["samples_ms"])
    lw_rust = max(lw["rust"]["samples_ms"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\legalWorstMaxCpp}}{{{lw_cpp:.1f}}}",
        rf"\newcommand{{\legalWorstMaxRust}}{{{lw_rust:.1f}}}",
        rf"\newcommand{{\legalWorstKbar}}{{{kbar:.1f}}}",
        rf"\newcommand{{\legalWorstRatioRust}}{{{max(un['rust']['samples_ms']) / lw_rust:.1f}}}",
        rf"\newcommand{{\legalWorstRatioCpp}}{{{max(un['cpp']['samples_ms']) / lw_cpp:.1f}}}",
    ]
    if "legal_osc" in timing:
        lo = timing["legal_osc"]
        oc = rust["legal_osc"]["counters"]
        macros += [
            rf"\newcommand{{\legalOscMaxCpp}}{{{max(lo['cpp']['samples_ms']):.1f}}}",
            rf"\newcommand{{\legalOscMaxRust}}{{{max(lo['rust']['samples_ms']):.1f}}}",
            rf"\newcommand{{\legalOscKbar}}{{{oc['sum_neighbors'] / oc['points_processed']:.1f}}}",
        ]
    (OUT / "legal_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/legal_macros.tex")


def realdata():
    """Operational-envelope table + macros from the real-drive capture (skipped if absent)."""
    rj = DATA / "realdata.json"
    if not rj.exists():
        print("realdata absent -- skipping operational-envelope outputs")
        return
    allframes = json.loads(rj.read_text())["frames"]
    timing = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    # Envelope rows use the on-map frames (the vehicle leaves the benchmark's cropped map for
    # most of the 57-min bag); P and max-K contract checks use ALL frames.
    frames = [f for f in allframes if f["counters"]["sum_neighbors"] > 0]

    def series(f):
        return sorted(f(x) for x in frames)

    p = sorted(x["n_source"] for x in allframes)
    it = series(lambda x: x["iteration_num"])
    kbar = series(
        lambda x: x["counters"]["sum_neighbors"] / max(x["counters"]["points_processed"], 1)
    )
    kmax = sorted(x["counters"]["max_neighbors"] for x in allframes)
    kd = series(
        lambda x: x["counters"]["kd_nodes_visited"] / max(x["counters"]["points_processed"], 1)
    )
    cpp = series(lambda x: x["cpp_ms"])
    rust = series(lambda x: x["rust_ms"])
    match = sum(1 for x in allframes if x["match"])
    # Honest-denominator split (review #10): divergences counted against the on-map subset.
    onmap_match = sum(1 for x in frames if x["match"])
    div_all = len(allframes) - match
    div_onmap = len(frames) - onmap_match
    if div_onmap != div_all:
        # The prose claims every divergence is on-map; regenerate-or-break, never stale.
        raise SystemExit(
            f"realdata: {div_all - div_onmap} divergence(s) off-map -- "
            "prose claims all divergences are on-map; update the paper text"
        )
    offmap = [x for x in allframes if x["counters"]["sum_neighbors"] == 0]
    offmap_iter = sorted(x["iteration_num"] for x in offmap)
    offmap_cpp = sorted(x["cpp_ms"] for x in offmap)
    onmap_seq_max = max(x["seq"] for x in frames)
    # Share of on-map frames that hit the iteration cap (prose: "routinely reached").
    itercap = sum(1 for x in frames if x["iteration_num"] >= it[-1])
    # Prose claims the real worst C++ frame "grazes" the 100 ms budget.
    if not (90.0 < cpp[-1] < 100.0):
        raise SystemExit(
            f"real C++ max {cpp[-1]:.1f} ms no longer grazes the 100 ms budget -- "
            "update the Sec. V-G prose"
        )

    rows = []
    for label, xs, fmt in (
        (r"$P$ (points)", p, "{:.0f}"),
        (r"$N_{\mathrm{iter}}$", it, "{:.0f}"),
        (r"$\bar{K}$ (mean neighbors/pt)", kbar, "{:.2f}"),
        (r"max $K$ (per point)", kmax, "{:.0f}"),
        (r"kd nodes / pt", kd, "{:.1f}"),
        (r"C++ align (\si{ms})", cpp, "{:.2f}"),
        (r"Rust align (\si{ms})", rust, "{:.2f}"),
    ):
        rows.append(
            f"{label} & {fmt.format(pct(xs, 0.5))} & {fmt.format(pct(xs, 0.99))} "
            f"& {fmt.format(xs[-1])}"
        )
    write(
        "realdata.tex",
        rf"Real-data replay (İstanbul urban drive, open-loop frozen guess track): "
        r"per-frame distributions.",
        "tab:realdata",
        "lrrr",
        r"metric & p50 & p99 & max",
        rows,
        note=rf"$P$ and max $K$ over all \num{{{len(allframes)}}} frames; other rows over the "
        rf"\num{{{len(frames)}}} on-map frames (frames whose radius searches return any "
        rf"neighbor; the drive leaves the benchmark's cropped map after frame "
        rf"\num{{{onmap_seq_max}}}). Equal work: \num{{{match}}}/\num{{{len(allframes)}}} "
        rf"overall, on-map \num{{{onmap_match}}}/\num{{{len(frames)}}} "
        rf"({100.0 * onmap_match / len(frames):.1f}\%) --- all {div_all} divergences are "
        rf"on-map.",
    )

    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\realFrames}}{{\num{{{len(allframes)}}}}}",
        rf"\newcommand{{\realOnMap}}{{{len(frames)}}}",
        rf"\newcommand{{\realOffMap}}{{\num{{{len(allframes) - len(frames)}}}}}",
        rf"\newcommand{{\realMatch}}{{\num{{{match}}}}}",
        rf"\newcommand{{\realMatchPct}}{{{100.0 * match / len(allframes):.1f}}}",
        rf"\newcommand{{\realDivergences}}{{{div_all}}}",
        rf"\newcommand{{\realDivPctAll}}{{{100.0 * div_all / len(allframes):.2f}}}",
        rf"\newcommand{{\realOnMapMatch}}{{{onmap_match}}}",
        rf"\newcommand{{\realOnMapMatchPct}}{{{100.0 * onmap_match / len(frames):.1f}}}",
        rf"\newcommand{{\realOnMapDivPct}}{{{100.0 * div_onmap / len(frames):.1f}}}",
        rf"\newcommand{{\realOffMapIterMed}}{{{pct(offmap_iter, 0.5):.0f}}}",
        rf"\newcommand{{\realOffMapCppMed}}{{{pct(offmap_cpp, 0.5):.1f}}}",
        rf"\newcommand{{\realOnMapSeqMax}}{{{onmap_seq_max}}}",
        rf"\newcommand{{\realIterCapPct}}{{{100.0 * itercap / len(frames):.0f}}}",
        rf"\newcommand{{\realIterMax}}{{{it[-1]}}}",
        rf"\newcommand{{\realKmaxMax}}{{{kmax[-1]}}}",
        rf"\newcommand{{\realPMax}}{{{p[-1]}}}",
        rf"\newcommand{{\realRustMax}}{{{rust[-1]:.1f}}}",
        rf"\newcommand{{\realCppMax}}{{{cpp[-1]:.1f}}}",
    ]
    if "legal_worst" in timing and "search_00" in timing:
        lw = max(timing["legal_worst"]["rust"]["samples_ms"])
        un = max(timing["search_00"]["rust"]["samples_ms"])
        macros += [
            rf"\newcommand{{\realMarginDeploy}}{{{lw / rust[-1]:.1f}}}",
            rf"\newcommand{{\realMarginEngine}}{{{un / rust[-1]:.0f}}}",
        ]
    (OUT / "realdata_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/realdata_macros.tex")


def linfit(xs, ys):
    """Least-squares y = m*x + b; returns (m, b, r2)."""
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    m = sxy / sxx
    b = my - m * mx
    ss_res = sum((y - (m * x + b)) ** 2 for x, y in zip(xs, ys))
    ss_tot = sum((y - my) ** 2 for y in ys)
    return m, b, 1.0 - (ss_res / ss_tot if ss_tot > 0 else 0.0)


def psweep():
    """P-sweep table + pgfplots figure + prose macros (skipped if the data is absent)."""
    tj = DATA / "wcet_psweep.json"
    rj = DATA / "psweep_rust.json"
    if not (tj.exists() and rj.exists()):
        print("psweep data absent -- skipping psweep outputs")
        return
    timing = json.loads(tj.read_text())["fixtures"]
    rust = json.loads(rj.read_text())["fixtures"]
    names = sorted(timing, key=lambda n: rust[n]["n_source"])
    ps = [rust[n]["n_source"] for n in names]

    # Work-invariance check: sum_neighbors == P * 64 * 31 at every P.
    for n in names:
        c = rust[n]["counters"]
        assert c["sum_neighbors"] == rust[n]["n_source"] * 64 * 31, n
        assert rust[n]["iteration_num"] == 30, n

    stats = {}  # engine -> (p50s, maxs)
    for eng in ("cpp", "rust"):
        p50s, maxs = [], []
        for n in names:
            xs = sorted(timing[n][eng]["samples_ms"])
            p50s.append(pct(xs, 0.5))
            maxs.append(xs[-1])
        stats[eng] = (p50s, maxs)

    rows = []
    for i, n in enumerate(names):
        rows.append(
            f"{num(ps[i])} & {stats['cpp'][0][i]:.1f} & {stats['cpp'][1][i]:.1f} "
            f"& {stats['rust'][0][i]:.1f} & {stats['rust'][1][i]:.1f}"
        )
    write(
        "psweep.tex",
        r"$P$-sweep on the union-worst geometry (\si{ms}; work invariance verified: "
        r"$N_{\mathrm{iter}}{=}30$, $\sumnbr = P \cdot 64 \cdot 31$ exactly at every $P$).",
        "tab:psweep",
        "rrrrr",
        r"$P$ & \multicolumn{2}{c}{C++ (p50 / max)} & \multicolumn{2}{c}{Rust (p50 / max)}",
        rows,
        note=r"The sweep \emph{regenerates} the union-worst geometry at each $P$; its "
        r"$P{=}2000$ row is a distinct fixture instance from --- and so differs slightly "
        r"from --- the frozen \emph{search-00} of Table~\ref{tab:tails}. Same host and "
        r"protocol as Table~\ref{tab:tails} (Sec.~\ref{sec:evaluation}).",
    )

    # Fits on the max series (the WCET-relevant one) and p50 for the macros.
    fits = {}
    for eng in ("cpp", "rust"):
        m50, b50, r50 = linfit(ps, stats[eng][0])
        mmx, bmx, rmx = linfit(ps, stats[eng][1])
        fits[eng] = {"m50": m50, "b50": b50, "r50": r50, "mmx": mmx, "bmx": bmx, "rmx": rmx}

    # Prose macros (\psweep...) so the section text never hand-types a number.
    def us_per_pt(m):
        return f"{m * 1000:.0f}"

    pmax_cpp = int((100.0 - fits["cpp"]["bmx"]) / fits["cpp"]["mmx"])
    pmax_rust = int((100.0 - fits["rust"]["bmx"]) / fits["rust"]["mmx"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\psweepSlopeCpp}}{{{us_per_pt(fits['cpp']['mmx'])}}}",
        rf"\newcommand{{\psweepSlopeRust}}{{{us_per_pt(fits['rust']['mmx'])}}}",
        rf"\newcommand{{\psweepInterceptCpp}}{{{fits['cpp']['bmx']:.1f}}}",
        rf"\newcommand{{\psweepInterceptRust}}{{{fits['rust']['bmx']:.1f}}}",
        rf"\newcommand{{\psweepRsqCpp}}{{{fits['cpp']['rmx']:.4f}}}",
        rf"\newcommand{{\psweepRsqRust}}{{{fits['rust']['rmx']:.4f}}}",
        rf"\newcommand{{\psweepPmaxCpp}}{{{num(pmax_cpp)}}}",
        rf"\newcommand{{\psweepPmaxRust}}{{{num(pmax_rust)}}}",
        rf"\newcommand{{\psweepPmin}}{{{num(min(ps))}}}",
        rf"\newcommand{{\psweepPmax}}{{{num(max(ps))}}}",
    ]
    (OUT / "psweep_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/psweep_macros.tex")

    # pgfplots figure: max latency vs P, measured points + fitted lines.
    fig_dir = ROOT / "figures"
    fig_dir.mkdir(exist_ok=True)

    def coords(ys):
        return " ".join(f"({p},{y:.2f})" for p, y in zip(ps, ys))

    def fitline(f):
        return f"({min(ps)},{f['mmx'] * min(ps) + f['bmx']:.2f}) ({max(ps)},{f['mmx'] * max(ps) + f['bmx']:.2f})"

    fig = rf"""% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.
\begin{{figure}}[t]
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
  width=\columnwidth, height=0.62\columnwidth,
  xlabel={{source points $P$}}, ylabel={{max align time (ms)}},
  xmin=0, ymin=0, legend pos=north west, legend cell align=left,
  grid=major, tick label style={{font=\footnotesize}}, label style={{font=\footnotesize}},
  legend style={{font=\footnotesize}},
]
\addplot[only marks, mark=square*, color=blue] coordinates {{ {coords(stats['cpp'][1])} }};
\addlegendentry{{C++ (measured max)}}
\addplot[no marks, color=blue, dashed] coordinates {{ {fitline(fits['cpp'])} }};
\addlegendentry{{C++ fit ($R^2={fits['cpp']['rmx']:.4f}$)}}
\addplot[only marks, mark=*, color=red] coordinates {{ {coords(stats['rust'][1])} }};
\addlegendentry{{Rust (measured max)}}
\addplot[no marks, color=red, dashed] coordinates {{ {fitline(fits['rust'])} }};
\addlegendentry{{Rust fit ($R^2={fits['rust']['rmx']:.4f}$)}}
\end{{axis}}
\end{{tikzpicture}}
\caption{{Max align latency vs.\ source-point count $P$ on the union-worst geometry
(work per point held invariant; counters verified). Both engines are affine in $P$.}}
\label{{fig:psweep}}
\end{{figure}}
"""
    (fig_dir / "psweep.tex").write_text(fig, encoding="utf-8")
    print("wrote figures/psweep.tex")

    # Residual report (stdout only): flag a cache knee if the largest relative residual is big.
    for eng in ("cpp", "rust"):
        f = fits[eng]
        res = [
            (p, y - (f["mmx"] * p + f["bmx"])) for p, y in zip(ps, stats[eng][1])
        ]
        worst = max(res, key=lambda t: abs(t[1]))
        print(f"psweep {eng}: slope {f['mmx']*1000:.0f} us/pt, intercept {f['bmx']:.1f} ms, "
              f"R2(max) {f['rmx']:.4f}, worst residual {worst[1]:+.1f} ms at P={worst[0]}")


def main_extra():
    timing = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    legal_macros(timing, rust)


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    main()
    main_extra()
    realdata()
    psweep()
