#!/usr/bin/env python3
"""Generate the paper's LaTeX tables from the frozen measurement JSONs (stdlib-only).

Inputs (paper/data/): wcet.json (replay timing, both engines), wcet_rust.json (counters),
wcet_alloc.json (LD_PRELOAD allocation pass); optionally wcet_psweep.json + psweep_rust.json
(the P-sweep replay + counters).
Outputs (paper/tables/): counters.tex, tails.tex, frontier_timing.tex, alloc.tex, regression.tex;
prose-macro files (*_macros.tex: tails, regression, legal, realdata, psweep, env,
oneoff) so no measurement number is ever hand-typed in the .tex sources; with psweep data
also tables/psweep.tex and figures/psweep.tex (pgfplots).

Regenerate after any re-measurement:  python3 scripts/gen_tables.py
Never hand-edit tables/*.tex or figures/*.tex — they are build products (kept in git so the
paper builds without re-running the benchmark).

The generator also *asserts* the rounded qualitative claims the prose makes (the intro
spread claim, "grazing the 100 ms budget", "the same per-point constant", the search-log kd
baseline): if a re-measurement falsifies one, generation fails instead of leaving stale prose.
wcet.json must carry the Isolated meta.manifest emitted by scripts/integrate_campaign.py.
"""

import json
import math
import pathlib
import random

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "tables"

EULER_GAMMA = 0.5772156649015329
# Display order: worst first.
ORDER = [
    "search_00",
    "search_01",
    "dense_neighbors",
    "max_iterations",
    "cache_hostile",
    "subnormal",
    "legal_worst",
    "legal_osc",
]
LABEL = {
    "search_00": r"\emph{search-00}",
    "search_01": r"\emph{search-01}",
    "dense_neighbors": r"\emph{dense-nbrs}",
    "max_iterations": r"\emph{max-iters}",
    "cache_hostile": r"\emph{cache-hostile}",
    "subnormal": r"\emph{subnormal}",
    "legal_worst": r"\emph{legal-worst}$^\dagger$",
    "legal_osc": r"\emph{legal-osc}$^\dagger$",
}
# Shared table footnote for the tier markers.
TIER_NOTE = (r"\emph{search-00} is the Rust-search champion transferred to both engines; "
             r"$^\dagger$\,deployment-tier fixtures.")

# One-off side measurements quoted in the prose but not captured in data/*.json.
# Each entry documents its source; C1 of plan/paper_fix.md re-measures or archives them.
# Emitted as \oneoff* macros (tables/oneoff_macros.tex) so the .tex sources never hand-type
# them; where a derived quantity depends on one (kd growth %, allocator share), the
# derivation lives here too and is guarded by an assertion against the frozen data.
ONEOFF = {
    # Counter-guided search log (2026-07-10 session, not archived): kd_nodes_visited of the
    # generation-0 candidate. The gen-23 output is the frozen search-00; its kd value is
    # derived from wcet_rust.json and asserted below so this baseline cannot silently pair
    # with a different search run.
    "kd_gen_zero_m": 8.88,
    # (Subnormal shell A/B moved to data/subnormal_ab.json, C5: re-measured under Isolated
    # from the reproducible subnormal / subnormal_ctrl fixtures; \oneoffShell* now generated.)
    # exp() microbenchmark (2026-07-10 session): subnormal-result vs normal-result cost per
    # call, glibc exp vs the port's pure-Rust libm.
    "exp_sub_ratio_glibc": 2.9,
    "exp_sub_ratio_libm": 5.1,
    # Allocator fast-path microbenchmark (2026-07-10 session): one malloc/free pair, ns,
    # thread-cache hit, same host.
    "malloc_pair_ns": 11.3,
    # Iterative vs recursive kd radius search (port development, same day / same core), %.
    "kd_iter_speedup_pct": 12,
    # legal-worst rerun at the shipped epsilon = 0.01: converges in this many iterations
    # (2026-07-10 session; motivates the epsilon-pinned iteration axis).
    "legal_worst_prod_eps_iters": 2,
    # Differential-test bound on the eigensolver deviation over the inverse covariances
    # (glibc/LAPACK vs the port), from the divergence root-cause session (2026-07-10).
    "eigensolver_bound": r"2\times10^{-15}",
}


def pct(sorted_xs, p):
    return sorted_xs[min(int(p * (len(sorted_xs) - 1)), len(sorted_xs) - 1)]


def num(x):
    """LaTeX-format an integer with thin-space thousands separators via siunitx."""
    return rf"\num{{{x}}}"


def write(name, caption, label, colspec, header, rows, note=None, tabcolsep="4pt",
          size=r"\footnotesize"):
    lines = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        size,
        rf"\setlength{{\tabcolsep}}{{{tabcolsep}}}",
        rf"\begin{{tabular}}{{{colspec}}}",
        r"\toprule",
        header + r" \\",
        r"\midrule",
    ]
    lines += [r + r" \\" for r in rows]
    lines += [r"\bottomrule", r"\end{tabular}"]
    if note:
        lines.append(rf"\par\smallskip\footnotesize {note}")
    lines.append(r"\end{table}")
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote tables/{name}")


def tex_escape(s):
    """Escape the characters that actually occur in the env strings."""
    return s.replace("~", r"\textasciitilde{}").replace("_", r"\_")


def provenance(manifest, meta):
    """One generated sentence carried by every timing-table note (review #8).

    Built from the policy-schema meta.manifest of the campaign integration; names the
    measurement configuration so no table can be read without its protocol.
    """
    sessions = manifest.get("sessions") or [manifest.get("experiment_id", "?")]
    dates = sorted({m["run_timestamp"][:10]
                    for m in manifest.get("session_manifests", [manifest])})
    configuration = {"A": "Replay", "B": "Isolated"}.get(
        manifest["measurement_profile"], manifest["measurement_profile"])
    return (
        rf"{configuration}: {len(sessions)} "
        rf"session(s), {'/'.join(dates)}, isolated pinned core "
        rf"(\texttt{{{tex_escape(manifest.get('affinity_mask', '?'))}}}), "
        rf"{meta['iters']} aligns/fixture."
    )


def kernel_disp(v):
    """'Linux <hostname> <release>' -> 'Linux <release>' for display."""
    parts = v.split()
    return f"{parts[0]} {parts[-1]}" if len(parts) == 3 else v


def env_macros(manifest, meta):
    """Measurement-environment macros so Sec. V-A can never drift from the data."""
    cv = manifest.get("compiler_versions") or {}
    flags = manifest.get("compiler_flags") or {}
    if flags.get("CMAKE_BUILD_TYPE") != "Release":
        raise SystemExit("env: expected CMAKE_BUILD_TYPE=Release")
    if flags.get("CMAKE_CXX_FLAGS_RELEASE") != "-O3 -DNDEBUG":
        raise SystemExit("env: expected CMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG")
    if manifest.get("cargo_profile") != "[profile.release]\noverflow-checks = true":
        raise SystemExit("env: unexpected Cargo release profile")
    dates = sorted({m["run_timestamp"][:10]
                    for m in manifest.get("session_manifests", [manifest])})
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\envCpu}}{{{tex_escape(manifest.get('cpu_model') or '?')}}}",
        rf"\newcommand{{\envKernel}}{{{tex_escape(kernel_disp(manifest.get('kernel_version') or '?'))}}}",
        rf"\newcommand{{\envCppCompiler}}{{{tex_escape(cv.get('cxx') or '?')}}}",
        rf"\newcommand{{\envRustCompiler}}{{{tex_escape(cv.get('rustc') or '?')}}}",
        r"\newcommand{\envCppReleaseFlags}{\texttt{-O3 -DNDEBUG}}",
        rf"\newcommand{{\envGovernor}}{{{manifest.get('governor') or '?'}}}",
        rf"\newcommand{{\envPinning}}{{\texttt{{{tex_escape(manifest.get('affinity_mask') or '?')}}}}}",
        rf"\newcommand{{\envDate}}{{{'/'.join(dates)}}}",
        rf"\newcommand{{\envIters}}{{{meta['iters']}}}",
        rf"\newcommand{{\envWarmup}}{{{meta['warmup']}}}",
        rf"\newcommand{{\envSessions}}{{{len(manifest.get('sessions', [1]))}}}",
    ]
    # Decode the pooled sample accounting (review2 #7): "<warm>+<tail> pooled across
    # sessions" with the session count -- emitted as per-session macros so the prose and
    # captions can spell out 3 x (100 warm + 1000 tail) without hand-typing it.
    import re as _re
    n_sessions = len(manifest.get("sessions", [1]))
    m = _re.match(r"(\d+)\+(\d+) pooled", str(meta["iters"]))
    if not m or int(m.group(1)) % n_sessions or int(m.group(2)) % n_sessions:
        raise SystemExit(f"env: cannot decode iters {meta['iters']!r} over "
                         f"{n_sessions} sessions -- update the decode or the prose")
    macros += [
        rf"\newcommand{{\envItersWarmPerSession}}{{{int(m.group(1)) // n_sessions}}}",
        rf"\newcommand{{\envItersTailPerSession}}{{{int(m.group(2)) // n_sessions}}}",
        rf"\newcommand{{\envIsolated}}{{{manifest.get('isolated_cpus') or 'none'}}}",
        rf"\newcommand{{\envCommit}}{{{(manifest.get('cpp_commit') or '?')[:8]}}}",
    ]
    (OUT / "env_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/env_macros.tex")


def oneoff_macros():
    """Macros for the one-off side measurements (see the ONEOFF dict for provenance)."""
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        "% One-off side measurements not in data/*.json; sources documented at the ONEOFF",
        "% dict in scripts/gen_tables.py. C1 of plan/paper_fix.md re-measures/archives them.",
        rf"\newcommand{{\oneoffKdGenZeroM}}{{{ONEOFF['kd_gen_zero_m']:.2f}}}",
        rf"\newcommand{{\oneoffExpSubGlibc}}{{{ONEOFF['exp_sub_ratio_glibc']:.1f}}}",
        rf"\newcommand{{\oneoffExpSubLibm}}{{{ONEOFF['exp_sub_ratio_libm']:.1f}}}",
        rf"\newcommand{{\oneoffMallocPairNs}}{{{ONEOFF['malloc_pair_ns']:.1f}}}",
        rf"\newcommand{{\oneoffKdIterSpeedup}}{{{ONEOFF['kd_iter_speedup_pct']}}}",
        rf"\newcommand{{\oneoffLegalWorstProdEpsIters}}{{{ONEOFF['legal_worst_prod_eps_iters']}}}",
        rf"\newcommand{{\oneoffEigensolverBound}}{{{ONEOFF['eigensolver_bound']}}}",
    ]
    (OUT / "oneoff_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/oneoff_macros.tex")


def legal_k_macros():
    """Macros for the max-K legal-search result (skipped if absent)."""
    kj = DATA / "legal_k_search.json"
    if not kj.exists():
        print("legal_k_search absent -- skipping max-K search macros")
        return
    r = json.loads(kj.read_text())["result"]
    seeds = len(json.loads(kj.read_text())["meta"]["seeds"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\legalKSearchMax}}{{{r['max_k_reached']}}}",
        rf"\newcommand{{\legalKSearchSeeds}}{{{seeds}}}",
    ]
    (OUT / "legal_k_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/legal_k_macros.tex")


def ablation():
    """Search-ablation table + macros (review #9) from data/search_ablation.json:
    hill vs budget-matched random over seeds, wall-clock-fitness reproducibility, and
    Isolated timing of the counter-Pareto frontier against an in-session search-00 anchor."""
    doc = json.loads((DATA / "search_ablation.json").read_text())
    meta, runs = doc["meta"], doc["runs"]
    nbr_max = meta["analytic_nbr_max"]
    if nbr_max != 2000 * 64 * 31:
        raise SystemExit("search_ablation.json: analytic nbr max != 2000*64*31 -- "
                         "budget/fixture family changed; regenerate the ablation data")
    # Guard: the frontier's search_00 triple must match the frozen counter baseline.
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]["search_00"]
    f00 = next(f for f in doc["frontier"] if f["name"] == "search_00")
    if (f00["iter"], f00["nbr"], f00["kd"]) != (
            rust["iteration_num"], rust["counters"]["sum_neighbors"],
            rust["counters"]["kd_nodes_visited"]):
        raise SystemExit("search_ablation.json frontier search_00 counters != wcet_rust.json "
                         "-- stale ablation data; regenerate")
    for r in runs:
        if r["mode"] == "hill" and r["fitness"] == "counters" and r["best"]["nbr"] != nbr_max:
            raise SystemExit(f"hill run seed={r['seed']} did not saturate sum-neighbors -- "
                             "the saturation claim in the prose is void; re-examine")

    rows = []
    for r in runs:
        mode = {"counters": r["mode"], "time": "hill (time)"}[r["fitness"]]
        sat = str(r["saturation_eval"])
        pct_max = f"{r['nbr_pct_of_max']:.1f}"
        rows.append(f"{mode} & \\texttt{{{r['seed']:#010x}}} & {sat} & {pct_max} "
                    f"& {num(r['best']['kd'])}")
    write(
        "ablation.tex",
        r"Search ablation: hill-climb vs budget-matched random sampling "
        rf"({meta['budget_evaluations']} evaluations each) and wall-clock fitness, per seed. "
        r"``at final \sumnbr{}'' = first evaluation reaching the run's final \sumnbr{}.",
        "tab:ablation",
        "llrrr",
        r"mode & seed & at final \sumnbr & \sumnbr{} (\% of max) & \kdnodes",
        rows,
        note=r"Hill-climb saturates \sumnbr{} at the analytic maximum on every seed (the "
        r"domain-informed seed genome already attains it; the search then grows the Rust "
        r"traversal counter \kdnodes); "
        r"random sampling never reaches it. The random arms start from \emph{random} "
        r"genomes, so the comparison bundles seed quality with search strategy. The two "
        r"wall-clock-fitness runs share a seed yet return different champions --- counter "
        r"fitness is bit-reproducible.",
        tabcolsep="3pt",
    )

    # Frontier timing macros, anchored on the same-series search_00 cells.
    ft = doc["frontier_timing"]
    anchor = ft["search_00"]
    cand_names = [n for n in ft if n != "search_00"]
    for n, fx in ft.items():
        if not fx["iter_match"]:
            raise SystemExit(f"frontier timing {n}: engine iteration mismatch -- "
                             "equal-work invariant violated; investigate before publishing")
    ratios = {eng: max(ft[n][eng]["max_ms"] / anchor[eng]["max_ms"] for n in cand_names)
              for eng in ("cpp", "rust")}
    frontier_order = ["search_00", "pareto_01", "pareto_02"]
    frontier_labels = {
        "search_00": "search-00",
        "pareto_01": "pareto-01",
        "pareto_02": "pareto-02",
    }
    frontier_ns = {ft[n][eng]["n"] for n in frontier_order for eng in ("cpp", "rust")}
    if len(frontier_ns) != 1:
        raise SystemExit("frontier timing sample counts differ across fixtures or engines")
    frontier_rows = []
    for n in frontier_order:
        cpp, rust_t = ft[n]["cpp"], ft[n]["rust"]
        frontier_rows.append(
            f"{frontier_labels[n]} & {cpp['p50_ms']:.1f} & {cpp['max_ms']:.1f} "
            f"& {rust_t['p50_ms']:.1f} & {rust_t['max_ms']:.1f}"
        )
    write(
        "frontier_timing.tex",
        f"Counter-Pareto frontier timing (ms; {next(iter(frontier_ns))} samples per "
        "fixture and engine; serial, isolated pinned core).",
        "tab:frontier-timing",
        "lrrrr",
        "fixture & C++ p50 & C++ max & Rust p50 & Rust max",
        frontier_rows,
        note="The search-00 row is the same-session anchor for the frontier comparison; "
        "it is separate from the larger pooled primary campaign.",
    )

    primary = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    primary_max = {
        eng: max(max(fx[eng]["samples_ms"]) for fx in primary.values())
        for eng in ("cpp", "rust")
    }
    frontier_max = {
        eng: max(ft[n][eng]["max_ms"] for n in frontier_order)
        for eng in ("cpp", "rust")
    }
    combined_max = {
        eng: max(primary_max[eng], frontier_max[eng]) for eng in ("cpp", "rust")
    }
    if combined_max["rust"] != ft["pareto_01"]["rust"]["max_ms"]:
        raise SystemExit("pareto-01 is no longer the Rust union maximum -- revise the prose")
    t1, t2 = doc["time_fitness_ablation"]["champion_kd"]
    if doc["time_fitness_ablation"]["reproducible"]:
        raise SystemExit("time-fitness runs reproduced identically -- the irreproducibility "
                         "sentence in the prose is void; re-examine")
    rand_pcts = [r["nbr_pct_of_max"] for r in runs
                 if r["mode"] == "random" and r["fitness"] == "counters"]
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\ablationBudget}}{{{meta['budget_evaluations']}}}",
        rf"\newcommand{{\ablationSeeds}}{{{len([r for r in runs if r['mode'] == 'hill' and r['fitness'] == 'counters'])}}}",
        rf"\newcommand{{\ablationRandomWorstPct}}{{{min(rand_pcts):.1f}}}",
        rf"\newcommand{{\ablationRandomBestPct}}{{{max(rand_pcts):.1f}}}",
        rf"\newcommand{{\ablationFrontierSize}}{{{len(doc['frontier'])}}}",
        rf"\newcommand{{\ablationFrontierCppRatio}}{{{ratios['cpp']:.3f}}}",
        rf"\newcommand{{\ablationFrontierRustRatio}}{{{ratios['rust']:.3f}}}",
        rf"\newcommand{{\ablationFrontierRustExcessPct}}{{{(ratios['rust'] - 1) * 100:.1f}}}",
        f"{chr(92)}newcommand{{{chr(92)}primaryFixtureMaxCpp}}{{{primary_max['cpp']:.1f}}}",
        f"{chr(92)}newcommand{{{chr(92)}primaryFixtureMaxRust}}{{{primary_max['rust']:.1f}}}",
        f"{chr(92)}newcommand{{{chr(92)}combinedFixtureMaxCpp}}{{{combined_max['cpp']:.1f}}}",
        f"{chr(92)}newcommand{{{chr(92)}combinedFixtureMaxRust}}{{{combined_max['rust']:.1f}}}",
        rf"\newcommand{{\ablationTimeKdA}}{{{num(t1)}}}",
        rf"\newcommand{{\ablationTimeKdB}}{{{num(t2)}}}",
        rf"\newcommand{{\ablationTimeKdDeltaPct}}{{{100.0 * abs(t1 - t2) / max(t1, t2):.3f}}}",
    ]
    (OUT / "ablation_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/ablation.tex + ablation_macros.tex")


def raspi4():
    """On-target counter check (Raspberry Pi 4, bare-metal): table + macros from the
    frozen serial log data/raspi4.txt (skipped if absent).

    Guards recompute the host comparison from wcet_rust.json (the app's own OK verdicts
    are not trusted) and pin the known divergence to exactly search_01 with the exact
    deltas the prose documents; anything else fails generation.
    """
    rj = DATA / "raspi4.txt"
    if not rj.exists():
        print("raspi4 log absent -- skipping on-target outputs")
        return
    import re

    host = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    line_re = re.compile(
        r"NDT (\w+): iter=(\d+) passes=(\d+) pts=(\d+) nbr=(\d+) kd=(\d+) maxk=(\d+) "
        r"build_ms=(\d+) align_ms=(\d+) (OK|MISMATCH)"
    )
    target = {}
    summary = None
    for line in rj.read_text().splitlines():
        m = line_re.search(line)
        if m:
            target[m.group(1)] = {
                "iter": int(m.group(2)),
                "passes": int(m.group(3)),
                "pts": int(m.group(4)),
                "nbr": int(m.group(5)),
                "kd": int(m.group(6)),
                "maxk": int(m.group(7)),
                "align_ms": int(m.group(9)),
            }
        s = re.search(r"NDT COUNTER CHECK: (\d+)/(\d+) OK", line)
        if s:
            summary = (int(s.group(1)), int(s.group(2)))
    if summary is None or len(target) != summary[1]:
        raise SystemExit("raspi4: log truncated or summary missing")
    # Recompute equality against the (current) host baseline. The log's own OK/MISMATCH
    # verdicts are historical: the on-device expected table at run time was the stale
    # 2026-07-10 snapshot, which predated the two port-fidelity fixes; against the refreshed
    # baseline (see data/wcet_rust.json meta) every fixture is exact.
    mismatch = {}
    for n, t in target.items():
        h = host[n]
        hc = h["counters"]
        deltas = {
            "iter": t["iter"] - h["iteration_num"],
            "passes": t["passes"] - hc["derivative_passes"],
            "pts": t["pts"] - hc["points_processed"],
            "nbr": t["nbr"] - hc["sum_neighbors"],
            "kd": t["kd"] - hc["kd_nodes_visited"],
        }
        if any(v != 0 for v in deltas.values()):
            mismatch[n] = deltas
    if mismatch:
        raise SystemExit(
            f"raspi4: target counters diverge from the host baseline ({mismatch}) -- "
            "the Secs. III-E/V/VI prose claims exact transfer on every fixture"
        )
    # Pin the on-device verdict of the frozen log (re-captured 2026-07-12 after the
    # baseline refresh -> 8/8; the first run's 7/8 log lives in git history and is narrated
    # as history in Sec. V).
    if summary != (8, 8):
        raise SystemExit(
            f"raspi4: on-device summary changed to {summary} -- update the pinned "
            "verdict and the Sec. V prose"
        )
    # The historical skew the on-device check flagged (target/current values vs the stale
    # 2026-07-10 baseline; bisected to commit 7caf44d7 -- see data/wcet_rust.json meta).
    hist_nbr_delta = 2
    hist_kd_delta = -1

    # The table (tab:raspi4) is emitted by raspi4_timing() from the timing-protocol log;
    # this emitter keeps the counter-transfer guards + the version-skew history macros.
    worst_s = max(t["align_ms"] for t in target.values()) / 1000.0
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\raspiTotal}}{{{len(target)}}}",
        rf"\newcommand{{\raspiExact}}{{{len(target) - len(mismatch)}}}",
        rf"\newcommand{{\raspiDeviceOk}}{{{summary[0]}}}",
        rf"\newcommand{{\raspiNbrDelta}}{{{hist_nbr_delta}}}",
        rf"\newcommand{{\raspiKdDelta}}{{{-hist_kd_delta}}}",
        rf"\newcommand{{\raspiMismatchNbrM}}{{{host['search_01']['counters']['sum_neighbors'] / 1e6:.1f}}}",
        rf"\newcommand{{\raspiAlignWorstS}}{{{worst_s:.1f}}}",
    ]
    (OUT / "raspi4_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/raspi4_macros.tex")


def raspi4_timing():
    """On-target timing series (Raspberry Pi 4, Bare-metal): table + macros from
    the frozen serial log data/raspi4_timing.txt (skipped if absent).

    Protocol (kernel app, FEATURES=ndt): per fixture, 3 warmups (the first is the counted
    conformance-check align), 100 warm samples, 20 cold samples each preceded by an 8 MiB write
    sweep, the series bracketed by a fixed-work calibration spin (throttle guard). Guards
    recompute the counter transfer against wcet_rust.json, require the completion marker,
    and pin the no-throttling and spread claims the prose makes.
    """
    tj = DATA / "raspi4_timing.txt"
    if not tj.exists():
        print("raspi4 timing log absent -- skipping on-target timing outputs")
        return
    import re

    host = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    text = tj.read_text()
    if "NDT TIMING SERIES: COMPLETE" not in text:
        raise SystemExit("raspi4_timing: log lacks the completion marker -- truncated run")
    proto = re.search(r"protocol: warmup=(\d+) samples=(\d+) cold=(\d+)", text)
    if not proto or (proto.group(1), proto.group(2), proto.group(3)) != ("3", "100", "20"):
        raise SystemExit("raspi4_timing: unexpected protocol constants -- update the prose")
    cnt_re = re.compile(
        r"NDT (\w+): iter=(\d+) passes=(\d+) pts=(\d+) nbr=(\d+) kd=(\d+) maxk=\d+ "
        r"build_ms=\d+ (OK|MISMATCH)")
    stat_re = re.compile(
        r"NDT (\w+) (warm|cold): n=(\d+) min_us=(\d+) p50_us=(\d+) p99_us=(\d+) max_us=(\d+)")
    calib_re = re.compile(r"NDT (\w+) calib: before_ns=(\d+) after_ns=(\d+)")
    counters, stats, calib = {}, {}, {}
    for line in text.splitlines():
        m = cnt_re.search(line)
        if m:
            counters[m.group(1)] = tuple(int(m.group(i)) for i in range(2, 7))
        m = stat_re.search(line)
        if m:
            stats[(m.group(1), m.group(2))] = {
                "n": int(m.group(3)), "min": int(m.group(4)), "p50": int(m.group(5)),
                "p99": int(m.group(6)), "max": int(m.group(7))}
        m = calib_re.search(line)
        if m:
            calib[m.group(1)] = (int(m.group(2)), int(m.group(3)))
    if len(counters) != 8 or len(calib) != 8 or len(stats) != 16:
        raise SystemExit(
            f"raspi4_timing: incomplete log (counters={len(counters)} stats={len(stats)} "
            f"calib={len(calib)})")
    for n, (it, passes, pts, nbr, kd) in counters.items():
        h, hc = host[n], host[n]["counters"]
        if (it, passes, pts, nbr, kd) != (
                h["iteration_num"], hc["derivative_passes"], hc["points_processed"],
                hc["sum_neighbors"], hc["kd_nodes_visited"]):
            raise SystemExit(f"raspi4_timing: counter transfer broken on {n}")
    # No-throttling claim: worst calibration drift across the ~55-minute sustained run.
    drift = max(abs(a - b) / b for b, a in calib.values())
    if drift > 0.01:
        raise SystemExit(
            f"raspi4_timing: calibration drift {drift:.2%} -- the no-throttling claim is "
            "void; investigate the run before publishing")
    # Spread claim: warm max/p50 across fixtures.
    spread = max(s["max"] / s["p50"] for (n, kind), s in stats.items() if kind == "warm")
    cold_delta = max(
        stats[(n, "cold")]["max"] / stats[(n, "warm")]["max"] for n in counters)
    if spread > 1.005:
        raise SystemExit(
            f"raspi4_timing: warm max/p50 {spread:.4f} exceeds the sub-0.5% spread claim")

    rows = []
    for n in ORDER:
        if n not in counters:
            continue
        w, c = stats[(n, "warm")], stats[(n, "cold")]
        rows.append(
            f"{LABEL[n]} & {w['p50'] / 1000.0:.1f} & {w['max'] / 1000.0:.1f} "
            f"& {c['max'] / 1000.0:.1f} & exact")
    write(
        "raspi4.tex",
        r"On-target \emph{Bare-metal} series: Raspberry Pi 4 (Cortex-A72), bare-metal "
        r"\texttt{no\_std} kernel; per fixture 100 warm + 20 cold (8\,MiB evict) samples "
        r"after 3 warmups.",
        "tab:raspi4",
        "lrrrl",
        r"fixture & warm p50 & warm max & cold max (\si{ms}) & counters",
        rows,
        note=r"Counters match the host reference for all eight fixtures. A fixed-work "
        r"calibration spin brackets every series: "
        r"worst drift \raspiCalibDriftPct\% over the sustained run --- no thermal "
        r"throttling. Firmware-default clock; single core active, no interrupts routed to "
        r"the benchmark task's core.",
    )
    s00 = stats[("search_00", "warm")]
    factor = None
    wb = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    if "search_00" in wb:
        factor = (s00["max"] / 1000.0) / max(wb["search_00"]["rust"]["samples_ms"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\raspiTimingSamples}}{{100}}",
        rf"\newcommand{{\raspiTimingCold}}{{20}}",
        rf"\newcommand{{\raspiCalibDriftPct}}{{{100.0 * drift:.2f}}}",
        rf"\newcommand{{\raspiSpreadWorstPct}}{{{100.0 * (spread - 1.0):.2f}}}",
        rf"\newcommand{{\raspiColdDeltaWorstPct}}{{{100.0 * (cold_delta - 1.0):.2f}}}",
        rf"\newcommand{{\raspiSearchWarmMaxS}}{{{s00['max'] / 1e6:.2f}}}",
    ]
    if factor is not None:
        macros.append(rf"\newcommand{{\raspiHostFactor}}{{{factor:.1f}}}")
    # Review2 #9 / A7 framing: the 10 Hz budget multiple of the deployment-tier witness on
    # this target, and the per-fixture host-vs-A72 per-unit-work factor range (Rust max
    # over Rust max on the same frozen inputs).
    if "legal_worst" in counters:
        lw_budget = (stats[("legal_worst", "warm")]["max"] / 1000.0) / 100.0
        macros.append(rf"\newcommand{{\raspiLegalWorstBudgetX}}{{{lw_budget:.0f}}}")
    host_factors = [
        (stats[(n, "warm")]["max"] / 1000.0) / max(wb[n]["rust"]["samples_ms"])
        for n in counters if n in wb
    ]
    if host_factors:
        macros.append(rf"\newcommand{{\raspiHostFactorMin}}{{{min(host_factors):.0f}}}")
        macros.append(rf"\newcommand{{\raspiHostFactorMax}}{{{max(host_factors):.0f}}}")
    (OUT / "raspi4_timing_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/raspi4.tex + raspi4_timing_macros.tex")


def interference():
    """Cache- and interference-sensitivity table + macros from the campaign's cold and
    co-runner series (skipped if the files are absent)."""
    cj, oj = DATA / "wcet_cold.json", DATA / "wcet_corunner.json"
    if not (cj.exists() and oj.exists()):
        print("cold/corunner data absent -- skipping interference outputs")
        return
    warm = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    cold = json.loads(cj.read_text())["fixtures"]
    co = json.loads(oj.read_text())["modes"]

    def med(fx, eng):
        xs = sorted(fx[eng]["samples_ms"])
        return xs[len(xs) // 2]

    # Table: the two co-runner fixtures, delta of median and max vs the warm series.
    rows = []
    co_worst = {}
    for n in ("search_00", "legal_worst"):
        cells = [LABEL[n]]
        for eng in ("cpp", "rust"):
            base_max = max(warm[n][eng]["samples_ms"])
            dc = 100.0 * (med(cold[n], eng) / med(warm[n], eng) - 1.0)
            cells.append(f"{dc:+.1f}")
            for mode in ("membw", "llc", "fp"):
                dm = 100.0 * (max(co[mode][n][eng]["samples_ms"]) / base_max - 1.0)
                cells.append(f"{dm:+.1f}")
                co_worst[n] = max(co_worst.get(n, 0.0), dm)
        rows.append(" & ".join(cells))
    write(
        "interference.tex",
        r"Cache and interference sensitivity: relative change vs.\ the warm series "
        r"(\%; cold = median shift under between-sample eviction; co-runner columns = "
        r"max shift with the named one-resource co-runner on an L3-sharing core).",
        "tab:interference",
        "lrrrrrrrr",
        r"fixture & \multicolumn{4}{c}{C++ (cold/membw/llc/fp)} "
        r"& \multicolumn{4}{c}{Rust (cold/membw/llc/fp)}",
        rows,
        tabcolsep="2pt",
        note=r"Positive = slower than warm. \emph{search-00} is kernel-evaluation-bound "
        r"(cache-resident); \emph{legal-worst} is kd-traversal/memory-bound --- the "
        r"deployment tier is the interference-sensitive one.",
    )
    # Cold worst across ALL fixtures (prose macro).
    cold_worst = 0.0
    for n in cold:
        for eng in ("cpp", "rust"):
            cold_worst = max(
                cold_worst, 100.0 * (med(cold[n], eng) / med(warm[n], eng) - 1.0))
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\coldWorstPct}}{{{cold_worst:.1f}}}",
        rf"\newcommand{{\coWorstSearch}}{{{co_worst.get('search_00', 0):.1f}}}",
        rf"\newcommand{{\coWorstLegal}}{{{co_worst.get('legal_worst', 0):.1f}}}",
    ]
    (OUT / "interference_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/interference_macros.tex")


def cert_macros():
    """Pose/score agreement macros from wcet_cert.json (skipped if absent).

    The agreement check is deterministic per input (poses do not depend on the timing-run
    sample count), so it is re-runnable independently of the frozen timing data.
    """
    cj = DATA / "wcet_cert.json"
    if not cj.exists():
        print("wcet_cert absent -- skipping agreement macros")
        return
    fx = json.loads(cj.read_text())["fixtures"]
    bad = [n for n, c in fx.items() if not c["pose_match"]]
    if bad:
        raise SystemExit(
            f"pose/score agreement FAILED on {bad} -- "
            "the Sec. III-C/V-B agreement claims no longer hold"
        )
    max_trans = max(c["trans_delta_m"] for c in fx.values())
    max_score = max(max(c["tp_delta"], c["nvtl_delta"]) for c in fx.values())
    score_exact = sum(
        1 for c in fx.values() if c["tp_delta"] == 0.0 and c["nvtl_delta"] == 0.0
    )
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\certFixtures}}{{{len(fx)}}}",
        rf"\newcommand{{\certScoreExact}}{{{score_exact}}}",
        rf"\newcommand{{\certMaxTransDelta}}{{\num{{{max_trans:.0e}}}}}",
        rf"\newcommand{{\certMaxScoreDelta}}{{\num{{{max_score:.0e}}}}}",
    ]
    (OUT / "cert_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/cert_macros.tex")


def main():
    doc = json.loads((DATA / "wcet.json").read_text())
    timing = doc["fixtures"]
    meta = doc.get("meta", {})
    manifest = meta.get("manifest")
    if not manifest or manifest.get("measurement_profile") != "B":
        raise SystemExit(
            "wcet.json lacks an Isolated meta.manifest -- regenerate it via "
            "scripts/integrate_campaign.py (tables must not mix measurement profiles)")
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    alloc = json.loads((DATA / "wcet_alloc.json").read_text())["fixtures"]
    names = [n for n in ORDER if n in timing]
    prov = provenance(manifest, meta)
    env_macros(manifest, meta)
    oneoff_macros()

    # ---- counters.tex ----
    rows = []
    for n in names:
        c = rust[n]["counters"]
        rows.append(
            f"{LABEL[n]} & {rust[n]['iteration_num']} & {num(c['sum_neighbors'])} "
            f"& {num(c['kd_nodes_visited'])} & {num(rust[n]['n_map'])} & {rust[n]['n_tiles']}"
        )
    write(
        "counters.tex",
        r"Frozen fixtures: deterministic work counters (platform-independent; "
        r"$P=2000$ for the search outputs).",
        "tab:counters",
        "lrrrrr",
        r"fixture & $N_{\mathrm{iter}}$ & \sumnbr{} & \kdnodes{} & map pts & tiles",
        rows,
        note=r"$\sumnbr = \num{3968000} = 2000 \cdot 64 \cdot 31$ on "
        r"\emph{search-00}: the analytic kernel-evaluation maximum, reached exactly. " + TIER_NOTE,
    )

    # ---- tails.tex ----
    rows = []
    ratios = {}
    p50 = {}  # (fixture, engine) -> p50 ms
    mx = {}  # (fixture, engine) -> max ms
    for n in names:
        fx = timing[n]
        cs = sorted(fx["cpp"]["samples_ms"])
        rs = sorted(fx["rust"]["samples_ms"])
        p50[(n, "cpp")], p50[(n, "rust")] = pct(cs, 0.5), pct(rs, 0.5)
        mx[(n, "cpp")], mx[(n, "rust")] = cs[-1], rs[-1]
        ratios[n] = rs[-1] / cs[-1]
        rows.append(
            f"{LABEL[n]} & {pct(cs, 0.5):.1f} & {cs[-1]:.1f} & {pct(rs, 0.5):.1f} "
            f"& {rs[-1]:.1f} & \\textbf{{{ratios[n]:.2f}}}"
        )
    write(
        "tails.tex",
        r"Frame time per engine (\si{ms}; \envSessions{} sessions $\times$ "
        r"(\envItersWarmPerSession{} warm ${+}$ \envItersTailPerSession{} tail) samples "
        r"per fixture per engine, pooled; serial, isolated pinned core). "
        r"Each fixture satisfies work-trace conformance.",
        "tab:tails",
        "lrrrrr",
        r"fixture & \multicolumn{2}{c}{C++ (p50 / max)} "
        r"& \multicolumn{2}{c}{Rust (p50 / max)} & ratio",
        rows,
        note=r"ratio = Rust max / C++ max; $<1$ everywhere. " + TIER_NOTE + " " + prov,
    )

    # ---- tails_macros.tex: timing/counter/alloc-derived prose numbers ----
    # Per-point-per-pass cost (us) on the neighbor-sparse fixtures; points_processed
    # already equals passes * P.
    def pt_pass_us(n, eng):
        return p50[(n, eng)] * 1000.0 / rust[n]["counters"]["points_processed"]

    def kbar_of(n):
        c = rust[n]["counters"]
        return c["sum_neighbors"] / c["points_processed"]

    gap_sub = pt_pass_us("subnormal", "cpp") - pt_pass_us("subnormal", "rust")
    gap_ch = pt_pass_us("cache_hostile", "cpp") - pt_pass_us("cache_hostile", "rust")
    # "reappears as the same constant on cache-hostile": the two gaps must stay close.
    if abs(gap_sub - gap_ch) > 0.15 * gap_sub:
        raise SystemExit(
            f"per-point overhead gap diverged (subnormal {gap_sub:.2f} vs "
            f"cache-hostile {gap_ch:.2f} us) -- prose claims 'the same constant'"
        )
    # Allocator share of the gap: ONEOFF fast-path pair cost x measured pairs per pt-pass.
    sub_pairs = alloc["subnormal"]["cpp"]["allocs_per_align"] / rust["subnormal"]["counters"][
        "points_processed"
    ]
    alloc_share = 100.0 * ONEOFF["malloc_pair_ns"] * sub_pairs / (gap_sub * 1000.0)
    # search-00 kd term and its growth over the ONEOFF search-log gen-0 baseline.
    kd_m = rust["search_00"]["counters"]["kd_nodes_visited"] / 1e6
    if abs(kd_m - 12.01) > 0.005:
        raise SystemExit(
            f"search-00 kd = {kd_m:.2f} M: fixture changed; the ONEOFF kd_gen_zero_m "
            "search-log baseline (and the derived growth %) no longer applies"
        )
    kd_growth = 100.0 * (kd_m / ONEOFF["kd_gen_zero_m"] - 1.0)
    # Two-tier kernel-evaluation drop.
    nbr_search = rust["search_00"]["counters"]["sum_neighbors"]
    nbr_legal = rust["legal_worst"]["counters"]["sum_neighbors"]
    # Alloc headline: worst fixture per align, and the per-(pt.pass) constant.
    alloc_worst = max(alloc[n]["cpp"]["allocs_per_align"] for n in names)
    app = alloc["search_00"]["cpp"]["allocs_per_align"] / rust["search_00"]["counters"][
        "points_processed"
    ]
    # B1a: the interposer counts double as an independent C++-side work check ---
    # allocs/(pt.pass) must be constant wherever radius queries return neighbors, since the
    # numerator comes from the untouched C++ binary and the denominator from Rust counters.
    cert = {
        n: alloc[n]["cpp"]["allocs_per_align"]
        / rust[n]["counters"]["points_processed"]
        for n in names
    }
    cert_dense = [
        v
        for n, v in cert.items()
        if rust[n]["counters"]["sum_neighbors"] >= rust[n]["counters"]["points_processed"]
    ]
    cert_lo, cert_hi = min(cert_dense), max(cert_dense)
    if (cert_hi - cert_lo) / cert_lo > 0.005:
        raise SystemExit(
            f"alloc work-check spread {(cert_hi - cert_lo) / cert_lo:.3%} > 0.5% -- "
            "the C++-side P*N_pass cross-check claim in Secs. III-C/V-C no longer holds"
        )
    # Intro spread claim: "from under 10 ms to nearly a second ... two orders of magnitude".
    spread = max(mx.values()) / min(p50.values())
    if not (min(p50.values()) < 10.0 and max(mx.values()) > 900.0 and spread > 100.0):
        raise SystemExit(
            f"intro spread claim is stale (min p50 {min(p50.values()):.1f} ms, "
            f"max {max(mx.values()):.1f} ms, spread {spread:.0f}x)")
    # Cross-session stability (review #8): worst relative spread of per-session medians,
    # and the spread of the Rust/C++ max ratio, across the campaign sessions.
    med_spread_worst = 0.0
    ratio_spread_worst = 0.0
    for n in names:
        psm = timing[n].get("per_session_median")
        if not psm:
            continue
        for eng in ("cpp", "rust"):
            ms = psm[eng]
            med_spread_worst = max(
                med_spread_worst, 100.0 * (max(ms) - min(ms)) / min(ms))
        # ratio per session from the per-session medians
        rr = [r / c for c, r in zip(psm["cpp"], psm["rust"])]
        ratio_spread_worst = max(ratio_spread_worst, max(rr) - min(rr))
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\tailsRatioMin}}{{{min(ratios.values()):.2f}}}",
        rf"\newcommand{{\tailsRatioMax}}{{{max(ratios.values()):.2f}}}",
        rf"\newcommand{{\sessMedSpreadWorstPct}}{{{med_spread_worst:.1f}}}",
        rf"\newcommand{{\sessRatioSpreadWorst}}{{{ratio_spread_worst:.2f}}}",
        rf"\newcommand{{\tailsSearchMaxCpp}}{{{mx[('search_00', 'cpp')]:.1f}}}",
        rf"\newcommand{{\tailsSearchMaxRust}}{{{mx[('search_00', 'rust')]:.1f}}}",
        rf"\newcommand{{\subnormalMedianRatio}}{{{p50[('subnormal', 'cpp')] / p50[('subnormal', 'rust')]:.1f}}}",
        rf"\newcommand{{\subnormalPtPassCppUs}}{{{pt_pass_us('subnormal', 'cpp'):.1f}}}",
        rf"\newcommand{{\subnormalPtPassRustUs}}{{{pt_pass_us('subnormal', 'rust'):.2f}}}",
        rf"\newcommand{{\ptPassGapUs}}{{{gap_sub:.1f}}}",
        rf"\newcommand{{\subnormalKbar}}{{{kbar_of('subnormal'):.1f}}}",
        rf"\newcommand{{\cacheHostileKbar}}{{{kbar_of('cache_hostile'):.1f}}}",
        rf"\newcommand{{\subnormalAllocPairs}}{{{sub_pairs:.0f}}}",
        rf"\newcommand{{\subnormalAllocSharePct}}{{{alloc_share:.0f}}}",
        rf"\newcommand{{\searchZeroKdM}}{{{kd_m:.2f}}}",
        rf"\newcommand{{\searchKdGrowthPct}}{{{kd_growth:.0f}}}",
        rf"\newcommand{{\searchZeroSumNbrM}}{{{nbr_search / 1e6:.2f}}}",
        rf"\newcommand{{\legalWorstSumNbrK}}{{{nbr_legal / 1e3:.0f}}}",
        rf"\newcommand{{\twoTierKernelDrop}}{{{nbr_search / nbr_legal:.1f}}}",
        rf"\newcommand{{\allocWorstPerAlign}}{{\num{{{alloc_worst}}}}}",
        rf"\newcommand{{\allocPerPtPass}}{{{app:.0f}}}",
        rf"\newcommand{{\allocPerPtPassExact}}{{{app:.1f}}}",
        rf"\newcommand{{\allocCertMin}}{{{cert_lo:.3f}}}",
        rf"\newcommand{{\allocCertMax}}{{{cert_hi:.3f}}}",
        rf"\newcommand{{\allocCertSpreadPct}}{{{100.0 * (cert_hi - cert_lo) / cert_lo:.2f}}}",
        rf"\newcommand{{\allocCertSparse}}{{{cert['subnormal']:.1f}}}",
    ]
    (OUT / "tails_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/tails_macros.tex")

    # ---- alloc.tex ----
    rows = []
    for n in names:
        fx = alloc[n]
        c = rust[n]["counters"]
        per_pp = fx["cpp"]["allocs_per_align"] / (
            c["derivative_passes"] * rust[n]["n_source"]
        )
        rows.append(
            f"{LABEL[n]} & {num(fx['cpp']['allocs_per_align'])} & {per_pp:.1f} "
            f"& {fx['rust']['allocs_per_align']}"
        )
    write(
        "alloc.tex",
        r"Heap allocations per align (\texttt{LD\_PRELOAD} interposer).",
        "tab:alloc",
        "lrrr",
        r"fixture & C++ / align & C++ / (pt$\cdot$pass) & Rust / align",
        rows,
        note=r"The constant ${\approx}11$ per point per pass locates the source in the "
        r"per-point inner loop (Sec.~\ref{sec:eval-alloc}). Rust: zero, matching the "
        r"counting-allocator-verified allocation-freedom contract. " + TIER_NOTE + " " + prov,
    )

    # ---- regression.tex ----
    # Pooled design (review #11 + review2 #3): the 8 fixtures plus the 6 P-sweep points
    # (same counters/timing protocol) -> n = 14 per engine. Two nested models per engine:
    #   2-term: T ~ a*sum_nbr + b*kd + c
    #   4-term: T ~ c_pt*points + a*sum_nbr + b*kd + c   (review2 #3's per-point axis)
    # Engine-specific model selection, guarded below: the per-point term is resolved and
    # physical for C++ (allocator + per-query machinery, corroborating Sec. V-C) and
    # degenerate for Rust (CI covers zero, LOO worsens) -- the port removes that axis.
    # C1: each engine's kd regressor is its OWN traversal counter -- Rust: nodes examined
    # (wcet counters); C++: FLANN distance+plane evaluations from the traced analysis build
    # (data/trace_cert.json). Before C1 the Rust counter served as a proxy for both.
    tj = DATA / "trace_cert.json"
    if not tj.exists():
        raise SystemExit("regression: data/trace_cert.json missing -- the C++ kd regressor "
                         "comes from the traced analysis build (C1); rerun it")
    trace_fx = json.loads(tj.read_text())["fixtures"]

    def kd_of(engine, name, rust_counters):
        if engine == "rust":
            return float(rust_counters["kd_nodes_visited"])
        tr = trace_fx.get(name, {}).get("trace")
        if tr is None:
            raise SystemExit(f"regression: no C++ trace counters for {name}; rerun the "
                             "traced replay over this fixture")
        return float(int(tr["cpp_kd_dist"]) + int(tr["cpp_kd_accum"]))

    def reg_rows(engine):
        rows_ = []
        for n in names:
            c = rust[n]["counters"]
            t50 = pct(sorted(timing[n][engine]["samples_ms"]), 0.5)
            rows_.append((float(c["points_processed"]), float(c["sum_neighbors"]),
                          kd_of(engine, n, c), t50, n))
        pj, prj = DATA / "wcet_psweep.json", DATA / "psweep_rust.json"
        if pj.exists() and prj.exists():
            pt = json.loads(pj.read_text())["fixtures"]
            pr = json.loads(prj.read_text())["fixtures"]
            for n in pt:
                c = pr[n]["counters"]
                t50 = pct(sorted(pt[n][engine]["samples_ms"]), 0.5)
                rows_.append((float(c["points_processed"]), float(c["sum_neighbors"]),
                              kd_of(engine, n, c), t50, n))
        return rows_

    def reg_features(row, nterms):
        pts, nbr, kd, _t, _n = row
        return (pts, nbr, kd, 1.0) if nterms == 4 else (nbr, kd, 1.0)

    def fit(rows_, nterms):
        k = 4 if nterms == 4 else 3
        ata = [[0.0] * k for _ in range(k)]
        atb = [0.0] * k
        for row in rows_:
            x = reg_features(row, nterms)
            t = row[3]
            for i in range(k):
                for j in range(k):
                    ata[i][j] += x[i] * x[j]
                atb[i] += x[i] * t
        m = [ata[i][:] + [atb[i]] for i in range(k)]
        for col in range(k):
            piv = max(range(col, k), key=lambda r: abs(m[r][col]))
            m[col], m[piv] = m[piv], m[col]
            for r in range(k):
                if r != col:
                    f = m[r][col] / m[col][col]
                    for cc in range(col, k + 1):
                        m[r][cc] -= f * m[col][cc]
        coef = [m[i][k] / m[i][i] for i in range(k)]

        def pred(row):
            return sum(c * v for c, v in zip(coef, reg_features(row, nterms)))

        mean_t = sum(r[3] for r in rows_) / len(rows_)
        ss_tot = sum((r[3] - mean_t) ** 2 for r in rows_)
        ss_res = sum((r[3] - pred(r)) ** 2 for r in rows_)
        return coef, 1.0 - ss_res / ss_tot, pred

    def loo_stats(rows_, nterms):
        errs = []
        for i in range(len(rows_)):
            _c2, _r2, pred2 = fit(rows_[:i] + rows_[i + 1 :], nterms)
            errs.append(
                (100.0 * abs(pred2(rows_[i]) - rows_[i][3]) / rows_[i][3], rows_[i][4])
            )
        errs.sort()
        return errs[len(errs) // 2][0], errs[-1][0], errs[-1][1]

    def boot_cis(rows_, nterms):
        rng = random.Random(20260712)
        k = 4 if nterms == 4 else 3
        boots = [[] for _ in range(k)]
        n_ = len(rows_)
        for _ in range(2000):
            sample = [rows_[rng.randrange(n_)] for _ in range(n_)]
            try:
                coef, _, _ = fit(sample, nterms)
            except ZeroDivisionError:
                continue  # degenerate resample
            for i in range(k):
                boots[i].append(coef[i])
        cis = []
        for xs in boots:
            xs.sort()
            cis.append((xs[int(0.025 * len(xs))], xs[int(0.975 * len(xs))]))
        return cis

    # Engine-specific adopted model (guarded: regenerate-or-break if the data stops
    # supporting the asymmetry Sec. V-F narrates).
    REG_SELECTED = {"cpp": 4, "rust": 2}
    rows = []
    reg_macros = ["% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit."]
    reg_sel_a = {}
    reg_loo_max = {}
    reg_n = None
    for eng, lab in (("cpp", "C++"), ("rust", "Rust")):
        data_rows = reg_rows(eng)
        reg_n = len(data_rows)
        cap = "Cpp" if eng == "cpp" else "Rust"
        for nterms in (2, 4):
            coef, r2, _pred = fit(data_rows, nterms)
            cis = boot_cis(data_rows, nterms)
            loo_med, loo_max, loo_worst = loo_stats(data_rows, nterms)
            reg_loo_max[(eng, nterms)] = loo_max
            if nterms == 4:
                cpt, a, b, c0 = coef
                (cpt_lo, cpt_hi), (a_lo, a_hi), (b_lo, b_hi), (c_lo, c_hi) = cis
                cpt_cell = f"{cpt * 1e3:.2f} [{cpt_lo * 1e3:.1f},\\,{cpt_hi * 1e3:.1f}]"
            else:
                a, b, c0 = coef
                (a_lo, a_hi), (b_lo, b_hi), (c_lo, c_hi) = cis
                cpt = cpt_lo = cpt_hi = None
                cpt_cell = "---"
            sel = REG_SELECTED[eng] == nterms
            star = r"\,$\star$" if sel else ""
            eng_cell = lab if nterms == 2 else ""
            rows.append(
                f"{eng_cell} & {nterms}-term"
                f"{star} & {cpt_cell} "
                f"& {a * 1e6:.1f} [{a_lo * 1e6:.0f},\\,{a_hi * 1e6:.0f}] "
                f"& {b * 1e6:.1f} [{b_lo * 1e6:.0f},\\,{b_hi * 1e6:.0f}] "
                f"& {c0:.1f} [{c_lo:.0f},\\,{c_hi:.0f}] & {r2:.4f}"
            )
            term_tag = "FourTerm" if nterms == 4 else "TwoTerm"
            reg_macros.append(
                rf"\newcommand{{\regLooMax{cap}{term_tag}}}{{{loo_max:.0f}}}"
            )
            if nterms == 4:
                if eng == "cpp":
                    # With the C++-own FLANN kd counter (C1), the per-point coefficient is
                    # no longer separately identified (FLANN per-query work is itself nearly
                    # proportional to points): the prose claims a positive point estimate
                    # whose CI covers zero.
                    if cpt <= 0.0 or cpt_lo > 0.0:
                        raise SystemExit(
                            "regression: C++ per-point coefficient no longer matches the "
                            "Sec. V-F story (positive point estimate, CI covering zero); "
                            "update the prose")
                    reg_macros.append(rf"\newcommand{{\regPtUsCpp}}{{{cpt * 1e3:.1f}}}")
                    reg_macros.append(
                        rf"\newcommand{{\regPtUsCppLo}}{{{cpt_lo * 1e3:.1f}}}")
                    reg_macros.append(
                        rf"\newcommand{{\regPtUsCppHi}}{{{cpt_hi * 1e3:.1f}}}")
                else:
                    # Degeneracy check: a *physical* (resolved-positive) Rust per-point
                    # coefficient would invalidate the Sec. V-F story. The observed fit is
                    # nonphysical (negative, sign-inverted by the collinear design).
                    if cpt_lo > 0.0:
                        raise SystemExit(
                            "regression: Rust per-point coefficient resolved positive -- "
                            "the Sec. V-F degenerate-for-Rust story is stale; update the prose")
                    reg_macros.append(
                        rf"\newcommand{{\regPtUsRustFour}}{{{cpt * 1e3:.1f}}}")
                    reg_macros.append(
                        rf"\newcommand{{\regPtUsRustFourLo}}{{{cpt_lo * 1e3:.1f}}}")
                    reg_macros.append(
                        rf"\newcommand{{\regPtUsRustFourHi}}{{{cpt_hi * 1e3:.1f}}}")
            if sel:
                reg_sel_a[eng] = a
                reg_macros.append(rf"\newcommand{{\regKernelNs{cap}}}{{{a * 1e6:.0f}}}")
                reg_macros.append(rf"\newcommand{{\regKdNs{cap}}}{{{b * 1e6:.0f}}}")
                reg_macros.append(rf"\newcommand{{\regRsq{cap}}}{{{r2:.4f}}}")
                reg_macros.append(rf"\newcommand{{\regLooMed{cap}}}{{{loo_med:.0f}}}")
                reg_macros.append(rf"\newcommand{{\regLooMax{cap}}}{{{loo_max:.0f}}}")
                reg_macros.append(
                    rf"\newcommand{{\regLooWorst{cap}}}{{{LABEL.get(loo_worst, loo_worst)}}}"
                )
        # NOTE: coefficient-level engine comparisons remain indicative only (Sec. V-F);
        # the resolved comparison is the direct per-fixture one (Table tails).
    # Guard: the adopted-model asymmetry claims the per-point term fixes the C++ worst
    # miss and worsens the Rust one.
    if not reg_loo_max[("cpp", 4)] < reg_loo_max[("cpp", 2)]:
        raise SystemExit("regression: 4-term does not improve the C++ worst LOO miss -- "
                         "the Sec. V-F model-selection story is stale; update the prose")
    if not reg_loo_max[("rust", 4)] > reg_loo_max[("rust", 2)]:
        raise SystemExit("regression: 4-term no longer worsens the Rust worst LOO miss -- "
                         "the Sec. V-F degenerate-for-Rust story is stale; update the prose")
    # Worst pairwise collinearity among the three regressors over the pooled design
    # (engine-independent; points/sum_nbr are exactly proportional on the P-sweep subset).
    cols = list(zip(*[(r[0], r[1], r[2]) for r in reg_rows("cpp")]))

    def pearson(xs, ys):
        mx, my = sum(xs) / len(xs), sum(ys) / len(ys)
        return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / math.sqrt(
            sum((x - mx) ** 2 for x in xs) * sum((y - my) ** 2 for y in ys)
        )

    corr = max(
        abs(pearson(cols[i], cols[j])) for i in range(3) for j in range(i + 1, 3)
    )
    reg_macros.append(rf"\newcommand{{\regN}}{{{reg_n}}}")
    reg_macros.append(rf"\newcommand{{\regCorr}}{{{corr:.2f}}}")
    reg_macros.append(
        rf"\newcommand{{\regKernelRatio}}{{{reg_sel_a['cpp'] / reg_sel_a['rust']:.1f}}}"
    )
    (OUT / "regression_macros.tex").write_text("\n".join(reg_macros) + "\n", encoding="utf-8")
    print("wrote tables/regression_macros.tex")
    write(
        "regression.tex",
        rf"Diagnostic regression ($n={reg_n}$ per engine; brackets: 95\% bootstrap CIs; "
        rf"worst regressor correlation {corr:.2f}). The kd regressor is engine-specific; "
        r"coefficients are not cross-engine unit costs.",
        "tab:regression",
        "llrrrrr",
        r"engine & model & $c_{\mathrm{pt}}$ (\si{\micro\second}/pt) "
        r"& $a$ (\si{ns}/kern.) & $b$ (\si{ns}/kd op) "
        r"& $c$ (\si{ms}) & $R^2$",
        rows,
        note=prov,
        tabcolsep="1.5pt",
        size=r"\scriptsize",
    )
    # (The exploratory Gumbel block-maxima table was replaced by scripts/evt.py's
    # diagnostics-gated POT/GPD analysis -- roadmap C2.)


def legal_macros(timing, rust):
    """Prose macros for the two-tier bound (skipped when legal_worst is absent)."""
    if "legal_worst" not in timing or "search_00" not in timing:
        print("legal_worst absent -- skipping legal macros")
        return
    lw = timing["legal_worst"]
    un = timing["search_00"]
    c = rust["legal_worst"]["counters"]
    kbar = c["sum_neighbors"] / c["points_processed"]
    lw_cpp = max(lw["cpp"]["samples_ms"])
    lw_rust = max(lw["rust"]["samples_ms"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\legalWorstMaxCpp}}{{{lw_cpp:.1f}}}",
        rf"\newcommand{{\legalWorstMaxRust}}{{{lw_rust:.1f}}}",
        rf"\newcommand{{\legalWorstKbar}}{{{kbar:.1f}}}",
        rf"\newcommand{{\legalWorstRatioRust}}{{{max(un['rust']['samples_ms']) / lw_rust:.1f}}}",
        rf"\newcommand{{\legalWorstRatioCpp}}{{{max(un['cpp']['samples_ms']) / lw_cpp:.1f}}}",
        # Budget multiple of the 100 ms (10 Hz) period on the host (review2 #9 framing).
        rf"\newcommand{{\legalWorstBudgetXRust}}{{{lw_rust / 100.0:.1f}}}",
    ]
    if "legal_osc" in timing:
        lo = timing["legal_osc"]
        oc = rust["legal_osc"]["counters"]
        macros += [
            rf"\newcommand{{\legalOscMaxCpp}}{{{max(lo['cpp']['samples_ms']):.1f}}}",
            rf"\newcommand{{\legalOscMaxRust}}{{{max(lo['rust']['samples_ms']):.1f}}}",
            rf"\newcommand{{\legalOscKbar}}{{{oc['sum_neighbors'] / oc['points_processed']:.1f}}}",
        ]
    (OUT / "legal_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/legal_macros.tex")


def _frames_by_seq(frames, source):
    """Index frozen replay frames and reject ambiguous joins."""
    indexed = {}
    for frame in frames:
        seq = frame.get("seq")
        if seq in indexed:
            raise SystemExit(f"{source}: duplicate seq {seq}")
        indexed[seq] = frame
    return indexed


def load_real_evidence():
    """Join the base and trace replays by seq and derive comparison partitions."""
    rj = DATA / "realdata.json"
    tj = DATA / "trace_real.json"
    if not (rj.exists() and tj.exists()):
        raise SystemExit("real-data evidence requires realdata.json and trace_real.json")

    rdoc = json.loads(rj.read_text())
    tdoc = json.loads(tj.read_text())
    real = _frames_by_seq(rdoc["frames"], "realdata.json")
    trace = _frames_by_seq(tdoc["frames"], "trace_real.json")
    if set(real) != set(trace):
        missing_trace = sorted(set(real) - set(trace))
        missing_real = sorted(set(trace) - set(real))
        raise SystemExit(
            "real-data seq sets differ: "
            f"missing trace={missing_trace[:5]}, missing real={missing_real[:5]}"
        )

    joined = []
    for seq in sorted(real):
        rframe, tframe = real[seq], trace[seq]
        if tframe["iter_rust"] != rframe["iteration_num"]:
            raise SystemExit(f"seq {seq}: Rust iteration count differs between captures")
        if bool(tframe["iteration_match"]) != bool(rframe["match"]):
            raise SystemExit(f"seq {seq}: iteration verdict differs between captures")
        joined.append((rframe, tframe))

    def onmap(pair):
        return pair[0]["counters"]["sum_neighbors"] > 0

    def base(pair):
        return bool(pair[1]["base_match"])

    def trace_certified(pair):
        trace_block = pair[1]["trace"]
        return (
            base(pair)
            and bool(trace_block["valid"])
            and bool(trace_block["structural_match"])
        )

    def partition(pairs):
        trace_count = sum(trace_certified(pair) for pair in pairs)
        base_only = sum(
            base(pair) and not trace_certified(pair) for pair in pairs
        )
        divergent = sum(not base(pair) for pair in pairs)
        if trace_count + base_only + divergent != len(pairs):
            raise SystemExit("real-data comparison partition is not exhaustive")
        return trace_count, base_only, divergent

    all_partition = partition(joined)
    onmap_joined = [pair for pair in joined if onmap(pair)]
    onmap_partition = partition(onmap_joined)
    if (len(joined), all_partition) != (22416, (22178, 5, 233)):
        raise SystemExit(
            f"unexpected all-frame comparison partition: {len(joined)}, {all_partition}"
        )
    if (len(onmap_joined), onmap_partition) != (501, (263, 5, 233)):
        raise SystemExit(
            f"unexpected on-map comparison partition: {len(onmap_joined)}, "
            f"{onmap_partition}"
        )
    return rdoc, joined, onmap_joined, base, trace_certified


def realdata():
    """Operational-envelope table + macros from the real-drive capture (skipped if absent)."""
    rj = DATA / "realdata.json"
    if not rj.exists():
        print("realdata absent -- skipping operational-envelope outputs")
        return
    rdoc, joined, onmap_joined, base_certified, trace_certified = load_real_evidence()
    if rdoc.get("meta", {}).get("measurement_profile") != "A":
        raise SystemExit(
            "realdata.json lacks the Replay meta -- Sec. V-G presents Replay results; "
            "regenerate via the open-loop replay protocol (tables must not mix configurations)")
    allframes = [real for real, _ in joined]
    timing = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    # Envelope rows use the on-map frames (the vehicle leaves the benchmark's cropped map for
    # most of the 57-min bag); P and max-K contract checks use ALL frames.
    frames = [real for real, _ in onmap_joined]

    def series(f):
        return sorted(f(x) for x in frames)

    p = sorted(x["n_source"] for x in allframes)
    it = series(lambda x: x["iteration_num"])
    kbar = series(
        lambda x: x["counters"]["sum_neighbors"] / max(x["counters"]["points_processed"], 1)
    )
    kmax = sorted(x["counters"]["max_neighbors"] for x in allframes)
    kd = series(
        lambda x: x["counters"]["kd_nodes_visited"] / max(x["counters"]["points_processed"], 1)
    )
    cpp = series(lambda x: x["cpp_ms"])
    rust = series(lambda x: x["rust_ms"])
    base_all = sum(base_certified(pair) for pair in joined)
    trace_all = sum(trace_certified(pair) for pair in joined)
    base_only_all = sum(
        base_certified(pair) and not trace_certified(pair) for pair in joined
    )
    base_divergent_all = sum(not base_certified(pair) for pair in joined)
    iteration_divergent_all = sum(not pair[1]["iteration_match"] for pair in joined)
    output_divergent_all = base_divergent_all - iteration_divergent_all
    # Honest-denominator split (review #10): divergences counted against the on-map subset.
    base_onmap = sum(base_certified(pair) for pair in onmap_joined)
    trace_onmap = sum(trace_certified(pair) for pair in onmap_joined)
    base_only_onmap = sum(
        base_certified(pair) and not trace_certified(pair) for pair in onmap_joined
    )
    base_divergent_onmap = sum(not base_certified(pair) for pair in onmap_joined)
    iteration_divergent_onmap = sum(
        not pair[1]["iteration_match"] for pair in onmap_joined
    )
    output_divergent_onmap = base_divergent_onmap - iteration_divergent_onmap
    shape_structural_onmap = sum(
        bool(trace["trace"]["valid"] and trace["trace"]["structural_match"])
        for _, trace in onmap_joined
    )
    if base_divergent_onmap != base_divergent_all:
        raise SystemExit(
            f"realdata: {base_divergent_all - base_divergent_onmap} base divergence(s) "
            "off-map -- update the paper text"
        )
    if iteration_divergent_onmap != iteration_divergent_all:
        raise SystemExit("realdata: an iteration divergence occurred off-map")
    offmap = [x for x in allframes if x["counters"]["sum_neighbors"] == 0]
    offmap_iter = sorted(x["iteration_num"] for x in offmap)
    offmap_cpp = sorted(x["cpp_ms"] for x in offmap)
    onmap_seq_max = max(x["seq"] for x in frames)
    # Share of on-map frames that hit the iteration cap (prose: "routinely reached").
    itercap = sum(1 for x in frames if x["iteration_num"] >= it[-1])
    # B5 scenario breakdown: on-map segment structure + where the divergences sit.
    seqs = sorted(x["seq"] for x in frames)
    seg_bounds = []
    start = prev = seqs[0]
    for s in seqs[1:]:
        if s == prev + 1:
            prev = s
            continue
        seg_bounds.append((start, prev))
        start = prev = s
    seg_bounds.append((start, prev))
    mism = [real for real, trace in joined if not trace["iteration_match"]]
    div_segs = len(
        {
            next(i for i, (a, b) in enumerate(seg_bounds) if a <= x["seq"] <= b)
            for x in mism
        }
    )
    mism_iters = sorted(x["iteration_num"] for x in mism)
    mism_at_cap = sum(1 for x in mism if x["iteration_num"] >= it[-1])
    mism_cpp_max = max(x["cpp_ms"] for x in mism)
    mism_cpp = sorted(x["cpp_ms"] for x in mism)
    mism_rust = sorted(x["rust_ms"] for x in mism)
    mism_kbar = sorted(
        x["counters"]["sum_neighbors"] / max(x["counters"]["points_processed"], 1)
        for x in mism
    )
    strict = [
        real
        for real, trace in onmap_joined
        if trace_certified((real, trace))
    ]
    if len(strict) != trace_onmap:
        raise SystemExit("realdata: work-trace-conformant timing count is inconsistent")
    strict_cpp = sorted(x["cpp_ms"] for x in strict)
    strict_rust = sorted(x["rust_ms"] for x in strict)
    # Deadline overruns at 10 Hz (policy: report frames > 100 ms). The prose claims C++
    # overruns exist under Replay while Rust never overruns; regenerate-or-break.
    over_cpp = sum(1 for x in allframes if x["cpp_ms"] > 100.0)
    over_cpp_onmap = sum(1 for x in frames if x["cpp_ms"] > 100.0)
    over_rust = sum(1 for x in allframes if x["rust_ms"] > 100.0)
    if over_cpp == 0:
        raise SystemExit(
            "no C++ frame exceeds 100 ms in realdata.json -- the Sec. V-G Replay "
            "overrun paragraph is stale; update the prose")
    if over_rust != 0:
        raise SystemExit(
            f"{over_rust} Rust frames exceed 100 ms -- the prose claims zero Rust "
            "overruns; update Sec. V-G")

    def dist_row(population, label, xs, fmt):
        return (
            f"{population} & {label} & {num(len(xs))} & {fmt.format(pct(xs, 0.5))} "
            f"& {fmt.format(pct(xs, 0.99))} & {fmt.format(xs[-1])}"
        )

    def count_row(label, count):
        return rf"all & {label} & {num(count)} & --- & --- & ---"

    rows = [
        r"\multicolumn{6}{l}{\emph{All-frame contract observations}}",
        dist_row("all", r"$P$ (points)", p, "{:.0f}"),
        dist_row("all", r"max $K$ (per point)", kmax, "{:.0f}"),
        count_row(r"$E_{\mathrm{base}}$", base_all),
        count_row(r"$E_{\mathrm{shape}}$", trace_all),
        count_row("base-only", base_only_all),
        count_row(r"outside $E_{\mathrm{base}}$", base_divergent_all),
        r"\midrule \multicolumn{6}{l}{\emph{On-map timing observations}}",
        dist_row("all on-map", r"C++ align (\si{ms})", cpp, "{:.2f}"),
        dist_row("all on-map", r"Rust align (\si{ms})", rust, "{:.2f}"),
        dist_row(r"$E_{\mathrm{shape}}$", r"C++ align (\si{ms})", strict_cpp, "{:.2f}"),
        dist_row(r"$E_{\mathrm{shape}}$", r"Rust align (\si{ms})", strict_rust, "{:.2f}"),
    ]
    write(
        "realdata.tex",
        rf"Real-data replay (İstanbul urban drive, open-loop frozen guess track), "
        r"the \emph{Replay} configuration (CFS, unpinned, one align per "
        r"frame): per-frame distributions.",
        "tab:realdata",
        "llrrrr",
        r"population & metric & $n$ & p50 & p99 & max",
        rows,
        note=rf"On-map means at least one radius query returned a neighbor; "
        rf"\num{{{len(frames)}}} frames qualify. The on-map partition is "
        rf"$E_{{\mathrm{{shape}}}}={trace_onmap}$, base-only={base_only_onmap}, and "
        rf"outside $E_{{\mathrm{{base}}}}$={base_divergent_onmap}. Of the latter, "
        rf"{iteration_divergent_onmap} differ in iteration count. Strict cross-language timing "
        rf"uses only $E_{{\mathrm{{shape}}}}$; all-on-map timing is a system-level observation.",
        tabcolsep="2pt",
        size=r"\scriptsize",
    )

    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\realFrames}}{{\num{{{len(allframes)}}}}}",
        rf"\newcommand{{\realOnMap}}{{{len(frames)}}}",
        rf"\newcommand{{\realOffMap}}{{\num{{{len(allframes) - len(frames)}}}}}",
        rf"\newcommand{{\realBaseAll}}{{\num{{{base_all}}}}}",
        rf"\newcommand{{\realBaseOnMap}}{{{base_onmap}}}",
        rf"\newcommand{{\realBaseOnMapPct}}{{{100.0 * base_onmap / len(frames):.1f}}}",
        rf"\newcommand{{\realShapeAll}}{{\num{{{trace_all}}}}}",
        rf"\newcommand{{\realShapeOnMap}}{{{trace_onmap}}}",
        rf"\newcommand{{\realShapeOnMapPct}}{{{100.0 * trace_onmap / len(frames):.1f}}}",
        rf"\newcommand{{\realBaseOnly}}{{{base_only_all}}}",
        rf"\newcommand{{\realBaseDivergent}}{{{base_divergent_all}}}",
        rf"\newcommand{{\realBaseDivergentOnMap}}{{{base_divergent_onmap}}}",
        rf"\newcommand{{\realIterationDivergent}}{{{iteration_divergent_all}}}",
        rf"\newcommand{{\realOutputDivergent}}{{{output_divergent_all}}}",
        rf"\newcommand{{\realOutputDivergentOnMap}}{{{output_divergent_onmap}}}",
        rf"\newcommand{{\realShapeStructuralOnMap}}{{{shape_structural_onmap}}}",
        rf"\newcommand{{\realNotShapeOnMap}}{{{base_only_onmap + base_divergent_onmap}}}",
        rf"\newcommand{{\realNotShapeOnMapPct}}{{{100.0 * (base_only_onmap + base_divergent_onmap) / len(frames):.1f}}}",
        rf"\newcommand{{\realBaseDivPctAll}}{{{100.0 * base_divergent_all / len(allframes):.2f}}}",
        rf"\newcommand{{\realOnMapBaseDivPct}}{{{100.0 * base_divergent_onmap / len(frames):.1f}}}",
        rf"\newcommand{{\realDivPctAll}}{{{100.0 * iteration_divergent_all / len(allframes):.2f}}}",
        rf"\newcommand{{\realOnMapDivPct}}{{{100.0 * iteration_divergent_onmap / len(frames):.1f}}}",
        rf"\newcommand{{\realOffMapIterMed}}{{{pct(offmap_iter, 0.5):.0f}}}",
        rf"\newcommand{{\realOffMapCppMed}}{{{pct(offmap_cpp, 0.5):.1f}}}",
        rf"\newcommand{{\realOnMapSeqMax}}{{{onmap_seq_max}}}",
        rf"\newcommand{{\realIterCapPct}}{{{100.0 * itercap / len(frames):.0f}}}",
        rf"\newcommand{{\realSegments}}{{{len(seg_bounds)}}}",
        rf"\newcommand{{\realDivSegments}}{{{div_segs}}}",
        rf"\newcommand{{\realDivIterMin}}{{{mism_iters[0]}}}",
        rf"\newcommand{{\realDivIterMax}}{{{mism_iters[-1]}}}",
        rf"\newcommand{{\realDivAtCap}}{{{mism_at_cap}}}",
        rf"\newcommand{{\realDivCppMax}}{{{mism_cpp_max:.1f}}}",
        rf"\newcommand{{\realDivCppMed}}{{{pct(mism_cpp, 0.5):.1f}}}",
        rf"\newcommand{{\realDivRustMed}}{{{pct(mism_rust, 0.5):.1f}}}",
        rf"\newcommand{{\realDivRustMax}}{{{mism_rust[-1]:.1f}}}",
        rf"\newcommand{{\realDivKbarMin}}{{{mism_kbar[0]:.1f}}}",
        rf"\newcommand{{\realDivKbarMax}}{{{mism_kbar[-1]:.1f}}}",
        rf"\newcommand{{\realTraceCppMax}}{{{strict_cpp[-1]:.1f}}}",
        rf"\newcommand{{\realTraceRustMax}}{{{strict_rust[-1]:.1f}}}",
        rf"\newcommand{{\realIterMax}}{{{it[-1]}}}",
        rf"\newcommand{{\realKmaxMax}}{{{kmax[-1]}}}",
        rf"\newcommand{{\realPMax}}{{{p[-1]}}}",
        rf"\newcommand{{\realRustMax}}{{{rust[-1]:.1f}}}",
        rf"\newcommand{{\realCppMax}}{{{cpp[-1]:.1f}}}",
        rf"\newcommand{{\realOverrunsCpp}}{{{over_cpp}}}",
        rf"\newcommand{{\realOverrunsCppOnMapPct}}{{{100.0 * over_cpp_onmap / len(frames):.0f}}}",
        rf"\newcommand{{\realCppMedOnMap}}{{{pct(cpp, 0.5):.1f}}}",
    ]
    if "legal_worst" in timing and "search_00" in timing:
        lw = max(timing["legal_worst"]["rust"]["samples_ms"])
        un = max(timing["search_00"]["rust"]["samples_ms"])
        macros += [
            rf"\newcommand{{\realMarginDeploy}}{{{lw / rust[-1]:.1f}}}",
            rf"\newcommand{{\realMarginEngine}}{{{un / rust[-1]:.0f}}}",
        ]
    (OUT / "realdata_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/realdata_macros.tex")


def bridge():
    """Bridge table + macros (policy: Bridge Experiment) from data/bridge.json.

    The same five frozen inputs run under Replay and Isolated, with per-engine ratios.
    """
    bj = DATA / "bridge.json"
    if not bj.exists():
        print("bridge data absent -- skipping bridge outputs")
        return
    doc = json.loads(bj.read_text())
    inputs = doc["inputs"]
    order = ["search_00", "legal_worst", "legal_osc", "real_slowest", "real_median"]
    label = {"search_00": r"\emph{search-00}", "legal_worst": r"\emph{legal-worst}",
             "legal_osc": r"\emph{legal-osc}", "real_slowest": r"\emph{real-slowest}",
             "real_median": r"\emph{real-median}"}
    rows = []
    infl = {"cpp": [], "rust": []}
    for fx in order:
        e = inputs[fx]
        for eng in ("cpp", "rust"):
            v = e[eng]
            infl[eng].append(v["inflation_max"])
            a, b = v["profile_a"], v["profile_b"]
            rows.append(
                f"{label[fx] if eng == 'cpp' else ''} & {eng} & "
                f"{b['p50_ms']:.1f} & {b['max_ms']:.1f} & "
                f"{a['p50_ms']:.1f} & {a['max_ms']:.1f} & "
                f"\\textbf{{{v['inflation_max']:.2f}}}"
            )
    # Guards: the prose claims Rust Replay/Isolated ~= 1 and a C++ isolation tax (< 1).
    if not all(0.95 <= r <= 1.05 for r in infl["rust"]):
        raise SystemExit(f"bridge: Rust inflation outside ~1 ({infl['rust']}) -- "
                         "the Sec. V bridge prose claims ~=1.01; update it")
    if not all(r < 1.0 for r in infl["cpp"]):
        raise SystemExit(f"bridge: C++ inflation not uniformly < 1 ({infl['cpp']}) -- "
                         "the controlled-environment-tax story is stale; update the prose")
    # Cross-engine gap per profile (Rust max / C++ max). The Sec. V prose (review2 #6)
    # claims the conclusions survive under Replay while the relative gap narrows:
    # regenerate-or-break on both directions.
    gaps = {}
    for fx in order:
        e = inputs[fx]
        gb = e["rust"]["profile_b"]["max_ms"] / e["cpp"]["profile_b"]["max_ms"]
        ga = e["rust"]["profile_a"]["max_ms"] / e["cpp"]["profile_a"]["max_ms"]
        if ga >= 1.0:
            raise SystemExit(f"bridge: Rust max >= C++ max under Replay on {fx} -- "
                             "the cross-engine conclusion does not survive; update the prose")
        if ga <= gb:
            raise SystemExit(f"bridge: gap does not narrow under Replay on {fx} "
                             f"({gb:.3f} -> {ga:.3f}) -- the narrowing sentence is stale")
        gaps[fx] = (gb, ga)
    write(
        "bridge.tex",
        r"Bridge experiment on the same frozen inputs under \emph{Isolated}, with an "
        r"isolated core, its SMT sibling offline, and IRQs moved, and under \emph{Replay}, "
        r"with normal CFS, no pinning, and SMT enabled. Both use the same "
        r"\SI{3.2}{GHz} reference clock. The ratio is Replay maximum divided by "
        r"Isolated maximum and is descriptive only.",
        "tab:bridge",
        "llrrrrr",
        r"input & engine & \multicolumn{2}{c}{Isolated (\si{ms})} "
        r"& \multicolumn{2}{c}{Replay (\si{ms})} & ratio \\ "
        r"\cmidrule(lr){3-4} \cmidrule(lr){5-6} "
        r"& & p50 & max & p50 & max &",
        rows,
        note=r"Iteration counts are identical across configurations on every input. "
        r"Synthetic legs are matched-$n$ pooled 3-session campaigns ($n{=}3000$) on both "
        r"configurations (so the max-vs-max ratios are same-$n$); real-frame legs are dedicated "
        r"controlled sessions ($n{=}100$ each).",
    )
    # C++ per-align controlled-environment tax on the three P=2000/31-pass synthetics.
    syn = ["search_00", "legal_worst", "legal_osc"]
    taxes = [inputs[fx]["cpp"]["profile_b"]["max_ms"] - inputs[fx]["cpp"]["profile_a"]["max_ms"]
             for fx in syn]
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\bridgeCppInflMin}}{{{min(infl['cpp']):.2f}}}",
        rf"\newcommand{{\bridgeCppInflMax}}{{{max(infl['cpp']):.2f}}}",
        rf"\newcommand{{\bridgeRustInflMin}}{{{min(infl['rust']):.2f}}}",
        rf"\newcommand{{\bridgeRustInflMax}}{{{max(infl['rust']):.2f}}}",
        rf"\newcommand{{\bridgeCppTaxMinMs}}{{{min(taxes):.0f}}}",
        rf"\newcommand{{\bridgeCppTaxMaxMs}}{{{max(taxes):.0f}}}",
        rf"\newcommand{{\bridgeGapBLegalWorst}}{{{gaps['legal_worst'][0]:.2f}}}",
        rf"\newcommand{{\bridgeGapALegalWorst}}{{{gaps['legal_worst'][1]:.2f}}}",
    ]
    (OUT / "bridge_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/bridge.tex + bridge_macros.tex")


def linfit(xs, ys):
    """Least-squares y = m*x + b; returns (m, b, r2)."""
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    m = sxy / sxx
    b = my - m * mx
    ss_res = sum((y - (m * x + b)) ** 2 for x, y in zip(xs, ys))
    ss_tot = sum((y - my) ** 2 for y in ys)
    return m, b, 1.0 - (ss_res / ss_tot if ss_tot > 0 else 0.0)


def psweep():
    """P-sweep table + pgfplots figure + prose macros (skipped if the data is absent)."""
    tj = DATA / "wcet_psweep.json"
    rj = DATA / "psweep_rust.json"
    if not (tj.exists() and rj.exists()):
        print("psweep data absent -- skipping psweep outputs")
        return
    timing = json.loads(tj.read_text())["fixtures"]
    rust = json.loads(rj.read_text())["fixtures"]
    names = sorted(timing, key=lambda n: rust[n]["n_source"])
    ps = [rust[n]["n_source"] for n in names]

    # Work-invariance check: sum_neighbors == P * 64 * 31 at every P.
    for n in names:
        c = rust[n]["counters"]
        assert c["sum_neighbors"] == rust[n]["n_source"] * 64 * 31, n
        assert rust[n]["iteration_num"] == 30, n

    stats = {}  # engine -> (p50s, maxs)
    for eng in ("cpp", "rust"):
        p50s, maxs = [], []
        for n in names:
            xs = sorted(timing[n][eng]["samples_ms"])
            p50s.append(pct(xs, 0.5))
            maxs.append(xs[-1])
        stats[eng] = (p50s, maxs)

    rows = []
    for i, n in enumerate(names):
        rows.append(
            f"{num(ps[i])} & {stats['cpp'][0][i]:.1f} & {stats['cpp'][1][i]:.1f} "
            f"& {stats['rust'][0][i]:.1f} & {stats['rust'][1][i]:.1f}"
        )
    write(
        "psweep.tex",
        r"$P$-sweep on the Rust-search geometry (\si{ms}; work invariance verified: "
        r"$N_{\mathrm{iter}}{=}30$, $\sumnbr = P \cdot 64 \cdot 31$ exactly at every $P$).",
        "tab:psweep",
        "rrrrr",
        r"$P$ & \multicolumn{2}{c}{C++ (p50 / max)} & \multicolumn{2}{c}{Rust (p50 / max)}",
        rows,
        note=r"The sweep \emph{regenerates} the Rust-search geometry at each $P$; its "
        r"$P{=}2000$ row is a distinct fixture instance from --- and so differs slightly "
        r"from --- the frozen \emph{search-00} of Table~\ref{tab:tails}. Same host and "
        r"protocol as Table~\ref{tab:tails} (Sec.~\ref{sec:evaluation}).",
    )

    # Fits on the max series (the WCET-relevant one) and p50 for the macros.
    fits = {}
    for eng in ("cpp", "rust"):
        m50, b50, r50 = linfit(ps, stats[eng][0])
        mmx, bmx, rmx = linfit(ps, stats[eng][1])
        fits[eng] = {"m50": m50, "b50": b50, "r50": r50, "mmx": mmx, "bmx": bmx, "rmx": rmx}

    # Descriptive OLS intervals for the line through the six observed maxima. These
    # characterize line-fit uncertainty only; they are not bounds on unobserved maxima.
    def line_diagnostics(xs, ys, m, b):
        n = len(xs)
        dof = n - 2
        if dof != 4:
            raise ValueError("update the t critical value for the P-sweep sample count")
        mean_x = sum(xs) / n
        sxx = sum((x - mean_x) ** 2 for x in xs)
        residuals = [(x, y - (m * x + b)) for x, y in zip(xs, ys)]
        mse = sum(residual * residual for _, residual in residuals) / dof
        t95 = 2.7764451051977987
        slope_half = t95 * math.sqrt(mse / sxx)
        intercept_half = t95 * math.sqrt(mse * (1.0 / n + mean_x * mean_x / sxx))
        worst = max(residuals, key=lambda item: abs(item[1]))
        return {
            "slope_lo": m - slope_half,
            "slope_hi": m + slope_half,
            "intercept_lo": b - intercept_half,
            "intercept_hi": b + intercept_half,
            "worst_p": worst[0],
            "worst_residual": worst[1],
        }

    diagnostics = {
        eng: line_diagnostics(ps, stats[eng][1], fits[eng]["mmx"], fits[eng]["bmx"])
        for eng in ("cpp", "rust")
    }

    # Prose macros (\psweep...) so the section text never hand-types a number.
    def us_per_pt(m):
        return f"{m * 1000:.0f}"

    cross_cpp = int((100.0 - fits["cpp"]["bmx"]) / fits["cpp"]["mmx"])
    cross_rust = int((100.0 - fits["rust"]["bmx"]) / fits["rust"]["mmx"])
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\psweepSlopeCpp}}{{{us_per_pt(fits['cpp']['mmx'])}}}",
        rf"\newcommand{{\psweepSlopeRust}}{{{us_per_pt(fits['rust']['mmx'])}}}",
        rf"\newcommand{{\psweepInterceptCpp}}{{{fits['cpp']['bmx']:.1f}}}",
        rf"\newcommand{{\psweepInterceptRust}}{{{fits['rust']['bmx']:.1f}}}",
        rf"\newcommand{{\psweepRsqCpp}}{{{fits['cpp']['rmx']:.4f}}}",
        rf"\newcommand{{\psweepRsqRust}}{{{fits['rust']['rmx']:.4f}}}",
        rf"\newcommand{{\psweepCrossCpp}}{{{num(cross_cpp)}}}",
        rf"\newcommand{{\psweepCrossRust}}{{{num(cross_rust)}}}",
        rf"\newcommand{{\psweepResidualCpp}}{{{abs(diagnostics['cpp']['worst_residual']):.1f}}}",
        rf"\newcommand{{\psweepResidualRust}}{{{abs(diagnostics['rust']['worst_residual']):.1f}}}",
        rf"\newcommand{{\psweepResidualPCpp}}{{{num(diagnostics['cpp']['worst_p'])}}}",
        rf"\newcommand{{\psweepResidualPRust}}{{{num(diagnostics['rust']['worst_p'])}}}",
        rf"\newcommand{{\psweepPmin}}{{{num(min(ps))}}}",
        rf"\newcommand{{\psweepPmax}}{{{num(max(ps))}}}",
    ]
    (OUT / "psweep_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/psweep_macros.tex")

    fit_rows = []
    for eng, label in (("cpp", "C++"), ("rust", "Rust")):
        f = fits[eng]
        d = diagnostics[eng]
        fit_rows.append(
            f"{label} & {f['mmx'] * 1000:.1f} "
            f"[{d['slope_lo'] * 1000:.1f},\\,{d['slope_hi'] * 1000:.1f}] & "
            f"{f['bmx']:.1f} [{d['intercept_lo']:.1f},\\,{d['intercept_hi']:.1f}] & "
            f"{d['worst_residual']:+.1f} ($P={d['worst_p']}$) & {f['rmx']:.4f}"
        )
    write(
        "psweep_fit.tex",
        r"Descriptive affine fit to the six observed maxima; brackets are 95\% OLS "
        r"line-fit intervals, not confidence bounds on worst-case latency.",
        "tab:psweep-fit",
        "lrrrr",
        r"engine & slope (\si{\micro\second}/pt) & intercept (\si{ms}) & worst residual (\si{ms}) & $R^2$",
        fit_rows,
        size=r"\scriptsize",
        tabcolsep="2pt",
    )

    # pgfplots figure: max latency vs P, measured points + fitted lines.
    fig_dir = ROOT / "figures"
    fig_dir.mkdir(exist_ok=True)

    def coords(ys):
        return " ".join(f"({p},{y:.2f})" for p, y in zip(ps, ys))

    def fitline(f):
        return f"({min(ps)},{f['mmx'] * min(ps) + f['bmx']:.2f}) ({max(ps)},{f['mmx'] * max(ps) + f['bmx']:.2f})"

    fig = rf"""% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.
\begin{{figure}}[t]
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
  width=\columnwidth, height=0.62\columnwidth,
  xlabel={{source points $P$}}, ylabel={{max align time (ms)}},
  xmin=0, ymin=0, legend pos=north west, legend cell align=left,
  grid=major, tick label style={{font=\footnotesize}}, label style={{font=\footnotesize}},
  legend style={{font=\footnotesize}},
]
\addplot[only marks, mark=square*, color=blue] coordinates {{ {coords(stats['cpp'][1])} }};
\addlegendentry{{C++ (measured max)}}
\addplot[no marks, color=blue, dashed] coordinates {{ {fitline(fits['cpp'])} }};
\addlegendentry{{C++ fit ($R^2={fits['cpp']['rmx']:.4f}$)}}
\addplot[only marks, mark=*, color=red] coordinates {{ {coords(stats['rust'][1])} }};
\addlegendentry{{Rust (measured max)}}
\addplot[no marks, color=red, dashed] coordinates {{ {fitline(fits['rust'])} }};
\addlegendentry{{Rust fit ($R^2={fits['rust']['rmx']:.4f}$)}}
\end{{axis}}
\end{{tikzpicture}}
\caption{{Observed maximum align latency vs.\ source-point count $P$ on the
Rust-search geometry
(work per point held invariant; counters verified). Dashed lines are descriptive affine fits
through the six observed maxima, not hard latency bounds.}}
\label{{fig:psweep}}
\end{{figure}}
"""
    (fig_dir / "psweep.tex").write_text(fig, encoding="utf-8")
    print("wrote figures/psweep.tex")

    # Residual report (stdout only): flag a cache knee if the largest relative residual is big.
    for eng in ("cpp", "rust"):
        f = fits[eng]
        res = [
            (p, y - (f["mmx"] * p + f["bmx"])) for p, y in zip(ps, stats[eng][1])
        ]
        worst = max(res, key=lambda t: abs(t[1]))
        print(f"psweep {eng}: slope {f['mmx']*1000:.0f} us/pt, intercept {f['bmx']:.1f} ms, "
              f"R2(max) {f['rmx']:.4f}, worst residual {worst[1]:+.1f} ms at P={worst[0]}")


def trace_cert():
    """C1 work-trace conformance table + macros from data/trace_cert.json (fixture leg) and
    data/trace_real.json (real-drive leg, optional until captured).

    Guards (regenerate-or-break): on every fixture the STRUCTURAL legs must be exact
    (equal pass count, per-pass points/neighbors, per-point neighbor sets), the line-search
    entry counter must be zero, and the measured C++ pass count must equal iteration_num+1.
    """
    tj = DATA / "trace_cert.json"
    if not tj.exists():
        print("trace_cert absent -- skipping work-trace conformance outputs")
        return
    doc = json.loads(tj.read_text())
    fixtures = doc["fixtures"]
    ulps = {}
    rows = []
    table_names = [n for n in ORDER if n in fixtures]
    table_names += sorted(n for n in fixtures if n not in ORDER and not n.startswith("psweep"))
    for n, fx in fixtures.items():
        tr = fx.get("trace")
        if tr is None:
            raise SystemExit(f"trace_cert: fixture {n} lacks a trace block -- rerun the traced replay")
        if not fx["cert"]["base_match"]:
            raise SystemExit(f"trace_cert: base agreement broken on fixture {n}")
        if not (tr["valid"] and tr["structural_match"]):
            raise SystemExit(f"trace_cert: work-shape leg broken on {n} -- the Sec. III/V "
                             "conformance claim is void; investigate before publishing")
        if tr["line_search_loops"] != 0:
            raise SystemExit(f"trace_cert: line-search entered on {n} -- N_pass = N_iter+1 is void")
        if tr["passes_cpp"] != fx["cpp"]["iteration_num"] + 1:
            raise SystemExit(f"trace_cert: C++ passes != iterations+1 on {n}")
        ulps[n] = int(tr["score_max_ulp"])
    for n in table_names:
        tr = fixtures[n]["trace"]
        kd_cpp = int(tr["cpp_kd_dist"]) + int(tr["cpp_kd_accum"])
        rows.append(
            f"{LABEL.get(n, tex_escape(n))} & {tr['passes_cpp']} & exact & "
            f"{'exact' if tr['payload_match'] else 'different'} & "
            f"${ulp_tex(int(tr['score_max_ulp']))}$ & {num(kd_cpp)} & {num(int(tr['rust_kd']))}"
        )
    write(
        "tracecert.tex",
        r"Per-input work-trace conformance (traced analysis build vs.\ the Rust engine's mirrored "
        r"trace; deterministic, environment-independent). \emph{shape} compares pass count, "
        r"per-pass point/neighbor counts, and SHA-256 digests of sorted canonical leaf IDs. "
        r"\emph{payload} additionally digests each leaf's mean and regularized inverse covariance. "
        r"Score ULP is the maximum per-pass f64 ULP distance of the score handed to "
        r"the Newton step. $\Sigma_{\mathrm{kd}}$ columns are each engine's \emph{own} "
        r"traversal counter and are not mutually comparable.",
        "tab:tracecert",
        "lrrrrrr",
        r"fixture & passes & shape & payload & score ULP & $\Sigma_{\mathrm{kd}}^{\mathrm{C++}}$ "
        r"& $\Sigma_{\mathrm{kd}}^{\mathrm{Rust}}$",
        rows,
        note=r"Line-search entries: 0 on every input (measured); C++ passes = "
        r"$N_{\mathrm{iter}}{+}1$ exactly on every input. The 6 $P$-sweep instances (not "
        r"shown) also satisfy the work-shape criterion. " + TIER_NOTE,
        size=r"\scriptsize",
        tabcolsep="3pt",
    )
    conv = [v for v in ulps.values() if v < 1000]
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\traceFixtures}}{{{len(fixtures)}}}",
        rf"\newcommand{{\traceUlpZeroCount}}{{{sum(1 for v in ulps.values() if v == 0)}}}",
        rf"\newcommand{{\traceUlpConvMax}}{{{max(conv)}}}",
        rf"\newcommand{{\traceUlpWorstTex}}{{{ulp_tex(max(ulps.values()))}}}",
        rf"\newcommand{{\tracePayloadExactFixtures}}{{{sum(1 for fx in fixtures.values() if fx['trace']['payload_match'])}}}",
    ]

    _, joined, onmap_joined, base_certified, trace_certified = load_real_evidence()
    base_divergent = [
        trace for pair, trace in onmap_joined if not base_certified((pair, trace))
    ]
    iteration_divergent = [
        trace for _, trace in onmap_joined if not trace["iteration_match"]
    ]
    base_only = [
        trace
        for pair, trace in onmap_joined
        if base_certified((pair, trace)) and not trace_certified((pair, trace))
    ]
    trace_onmap = [
        trace for pair, trace in onmap_joined if trace_certified((pair, trace))
    ]
    if any(
        trace["trace"]["first_div_leg"] != "passes" for trace in iteration_divergent
    ):
        raise SystemExit(
            "trace_real: an iteration-divergent frame diverges before the pass-count leg"
        )

    gap_abs = sorted(
        abs(int(frame["trace"]["cpp_nbr"]) - int(frame["trace"]["rust_nbr"]))
        for frame in base_only
    )
    gap_rel = sorted(
        abs(int(frame["trace"]["cpp_nbr"]) - int(frame["trace"]["rust_nbr"]))
        / max(int(frame["trace"]["cpp_nbr"]), 1)
        for frame in base_only
    )
    fd = sorted(frame["trace"]["first_div_pass"] for frame in iteration_divergent)
    iter_delta = sorted(
        abs(frame["iter_cpp"] - frame["iter_rust"]) for frame in iteration_divergent
    )

    def trans_delta(frames):
        return sorted(frame.get("trans_delta_m", 0.0) for frame in frames)

    def trans_macros(prefix, values):
        return [
            rf"\newcommand{{\{prefix}Median}}{{{pct(values, 0.5):.6g}}}",
            rf"\newcommand{{\{prefix}High}}{{{pct(values, 0.99):.6g}}}",
            rf"\newcommand{{\{prefix}Max}}{{{values[-1]:.6g}}}",
        ]

    td_trace = trans_delta(trace_onmap)
    td_base_only = trans_delta(base_only)
    td_divergent = trans_delta(iteration_divergent)
    td_base_divergent = trans_delta(base_divergent)
    macros += [
        rf"\newcommand{{\traceRealWorkGapFrames}}{{{len(base_only)}}}",
        rf"\newcommand{{\traceRealWorkGapNbrMed}}{{{gap_abs[len(gap_abs) // 2]}}}",
        rf"\newcommand{{\traceRealWorkGapNbrMax}}{{{gap_abs[-1]}}}",
        rf"\newcommand{{\traceRealWorkGapRelMaxPct}}{{{100.0 * gap_rel[-1]:.2f}}}",
        rf"\newcommand{{\traceRealDivFirstMin}}{{{fd[0]}}}",
        rf"\newcommand{{\traceRealDivFirstMed}}{{{fd[len(fd) // 2]}}}",
        rf"\newcommand{{\traceRealDivFirstMax}}{{{fd[-1]}}}",
        rf"\newcommand{{\traceRealDivIterDeltaMax}}{{{iter_delta[-1]}}}",
        rf"\newcommand{{\tracePayloadExactOnMap}}{{{sum(1 for frame in onmap_joined if frame[1]['trace']['payload_match'])}}}",
    ]
    macros += trans_macros("traceRealTraceTransDelta", td_trace)
    macros += trans_macros("traceRealBaseOnlyTransDelta", td_base_only)
    macros += trans_macros("traceRealDivergentTransDelta", td_divergent)
    macros += trans_macros("traceRealBaseDivergentTransDelta", td_base_divergent)
    (OUT / "tracecert_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/tracecert.tex + tracecert_macros.tex")


def ulp_tex(v):
    """Render a ULP count for prose: exact when small, mantissa*10^e when large."""
    v = int(v)
    if v < 10000:
        return str(v)
    import math as _m
    e = int(_m.floor(_m.log10(v)))
    return rf"{v / 10 ** e:.1f}\times 10^{{{e}}}"


def subnormal_ab():
    """Subnormal shell A/B macros from data/subnormal_ab.json (C5, Isolated): the \\oneoffShell*
    p50 times, re-measured on-protocol from the reproducible subnormal / subnormal_ctrl fixtures.
    Guard (regenerate-or-break): moving out of the subnormal band must NOT reduce the time (the
    control is >= the in-band shell), so the "subnormals are not the mechanism" null holds."""
    aj = DATA / "subnormal_ab.json"
    if not aj.exists():
        print("subnormal_ab absent -- skipping shell A/B macros")
        return
    doc = json.loads(aj.read_text())
    fx = doc["fixtures"]

    def p50(name, eng):
        return pct(sorted(fx[name][eng]["samples_ms"]), 0.5)

    sub_cpp, ctrl_cpp = p50("subnormal", "cpp"), p50("subnormal_ctrl", "cpp")
    sub_rust, ctrl_rust = p50("subnormal", "rust"), p50("subnormal_ctrl", "rust")
    # The null test: removing subnormals (the control) must not be faster than the in-band shell.
    if ctrl_cpp < sub_cpp or ctrl_rust < sub_rust:
        raise SystemExit(
            "subnormal_ab: the out-of-band control is faster than the in-band shell -- the "
            "Sec. V-C 'subnormals are not the mechanism' null no longer holds; update the prose")
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\oneoffShellSubCpp}}{{{sub_cpp:.1f}}}",
        rf"\newcommand{{\oneoffShellCtrlCpp}}{{{ctrl_cpp:.1f}}}",
        rf"\newcommand{{\oneoffShellSubRust}}{{{sub_rust:.1f}}}",
        rf"\newcommand{{\oneoffShellCtrlRust}}{{{ctrl_rust:.1f}}}",
    ]
    (OUT / "subnormal_ab_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/subnormal_ab_macros.tex")


def parallel():
    """C8 parallel-feasibility table + macros from data/parallel.json (skipped if absent).

    Guards (regenerate-or-break): the Rust deployment witness must fit the 100 ms budget at
    the k the prose names, and Rust must scale (k=4 speedup > 1.5x) so the "closes the gap"
    claim cannot go stale.
    """
    pj = DATA / "parallel.json"
    if not pj.exists():
        print("parallel data absent -- skipping C8 outputs")
        return
    doc = json.loads(pj.read_text())
    inputs = doc["inputs"]
    label = {"search_00": r"\emph{search-00}", "legal_worst": r"\emph{legal-worst}",
             "legal_osc": r"\emph{legal-osc}$^\dagger$"}
    rows = []
    for fx in ("legal_worst",):
        cells = inputs[fx]
        for eng, name in (("cpp", "C++"), ("rust", "Rust")):
            r = [cells[str(k)][eng] for k in (1, 2, 4)]
            rows.append(
                f"{label[fx] if eng == 'cpp' else ''} & {name} & "
                f"{r[0]['max_ms']:.1f} & {r[1]['max_ms']:.1f} ({r[1]['speedup_max']:.1f}$\\times$) "
                f"& {r[2]['max_ms']:.1f} ({r[2]['speedup_max']:.1f}$\\times$)"
            )
    write(
        "parallel.tex",
        r"Host parallel feasibility for the deployment-tier witness (maximum align \si{ms}; "
        r"one pinned worker per isolated physical core). Not a multi-core WCET result.",
        "tab:parallel",
        "llrrr",
        r"fixture & engine & $k{=}1$ & $k{=}2$ & $k{=}4$",
        rows,
        note=r"Rust iteration counts are $k$-invariant; calibration drift: "
        r"\parCalibDriftPct\% (no throttling).",
    )
    lw = inputs["legal_worst"]
    # First k at which the Rust deployment witness fits the 100 ms budget.
    fit_k = next((k for k in (1, 2, 4) if lw[str(k)]["rust"]["max_ms"] < 100.0), None)
    if fit_k is None:
        raise SystemExit("parallel: Rust legal-worst never fits 100 ms in {1,2,4} -- the "
                         "Sec. V-parallel 'closes the gap' claim is stale; update the prose")
    if inputs["search_00"]["4"]["rust"]["speedup_max"] < 1.5:
        raise SystemExit("parallel: Rust k=4 speedup < 1.5x -- the scaling claim is stale")
    macros = [
        "% AUTO-GENERATED by scripts/gen_tables.py -- do not hand-edit.",
        rf"\newcommand{{\parCalibDriftPct}}{{{doc['meta']['calib_drift_pct']:.1f}}}",
        rf"\newcommand{{\parRustLegalFitK}}{{{fit_k}}}",
        rf"\newcommand{{\parRustLegalFitMaxMs}}{{{lw[str(fit_k)]['rust']['max_ms']:.1f}}}",
        rf"\newcommand{{\parRustLegalSerialMs}}{{{lw['1']['rust']['max_ms']:.1f}}}",
        rf"\newcommand{{\parRustSpeedupFour}}{{{inputs['search_00']['4']['rust']['speedup_max']:.1f}}}",
        rf"\newcommand{{\parCppSpeedupFour}}{{{inputs['search_00']['4']['cpp']['speedup_max']:.1f}}}",
        rf"\newcommand{{\parRustLegalSpeedupFour}}{{{lw['4']['rust']['speedup_max']:.1f}}}",
    ]
    (OUT / "parallel_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")
    print("wrote tables/parallel.tex + parallel_macros.tex")


def main_extra():
    timing = json.loads((DATA / "wcet.json").read_text())["fixtures"]
    rust = json.loads((DATA / "wcet_rust.json").read_text())["fixtures"]
    legal_macros(timing, rust)


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    main()
    main_extra()
    realdata()
    trace_cert()
    parallel()
    subnormal_ab()
    psweep()
    cert_macros()
    legal_k_macros()
    ablation()
    bridge()
    raspi4()
    raspi4_timing()
    interference()
